# coding: utf-8

"""
    slug-loves-beans

    this description is required

    The version of the OpenAPI document: 13.0.4+gitea-1.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.file_links_response import FileLinksResponse

class TestFileLinksResponse(unittest.TestCase):
    """FileLinksResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FileLinksResponse:
        """Test FileLinksResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FileLinksResponse`
        """
        model = FileLinksResponse()
        if include_optional:
            return FileLinksResponse(
                git = '',
                html = '',
                var_self = ''
            )
        else:
            return FileLinksResponse(
        )
        """

    def testFileLinksResponse(self):
        """Test FileLinksResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
