# coding: utf-8

"""
    slug-loves-beans

    this description is required

    The version of the OpenAPI document: 13.0.4+gitea-1.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.action_run_job import ActionRunJob

class TestActionRunJob(unittest.TestCase):
    """ActionRunJob unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActionRunJob:
        """Test ActionRunJob
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActionRunJob`
        """
        model = ActionRunJob()
        if include_optional:
            return ActionRunJob(
                id = 56,
                name = '',
                needs = [
                    ''
                    ],
                owner_id = 56,
                repo_id = 56,
                runs_on = [
                    ''
                    ],
                status = '',
                task_id = 56
            )
        else:
            return ActionRunJob(
        )
        """

    def testActionRunJob(self):
        """Test ActionRunJob"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
