# coding: utf-8

"""
    slug-loves-beans

    this description is required

    The version of the OpenAPI document: 13.0.4+gitea-1.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.activitypub_api import ActivitypubApi


class TestActivitypubApi(unittest.TestCase):
    """ActivitypubApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ActivitypubApi()

    def tearDown(self) -> None:
        pass

    def test_activitypub_instance_actor(self) -> None:
        """Test case for activitypub_instance_actor

        Returns the instance's Actor
        """
        pass

    def test_activitypub_instance_actor_inbox(self) -> None:
        """Test case for activitypub_instance_actor_inbox

        Send to the inbox
        """
        pass

    def test_activitypub_person(self) -> None:
        """Test case for activitypub_person

        Returns the Person actor for a user
        """
        pass

    def test_activitypub_person_activity(self) -> None:
        """Test case for activitypub_person_activity

        Get a specific activity of the user
        """
        pass

    def test_activitypub_person_activity_note(self) -> None:
        """Test case for activitypub_person_activity_note

        Get a specific activity object of the user
        """
        pass

    def test_activitypub_person_feed(self) -> None:
        """Test case for activitypub_person_feed

        List the user's recorded activity
        """
        pass

    def test_activitypub_person_inbox(self) -> None:
        """Test case for activitypub_person_inbox

        Send to the inbox
        """
        pass

    def test_activitypub_repository(self) -> None:
        """Test case for activitypub_repository

        Returns the Repository actor for a repo
        """
        pass

    def test_activitypub_repository_inbox(self) -> None:
        """Test case for activitypub_repository_inbox

        Send to the inbox
        """
        pass


if __name__ == '__main__':
    unittest.main()
