# coding: utf-8

"""
    slug-loves-beans

    this description is required

    The version of the OpenAPI document: 13.0.4+gitea-1.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.settings_api import SettingsApi


class TestSettingsApi(unittest.TestCase):
    """SettingsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SettingsApi()

    def tearDown(self) -> None:
        pass

    def test_get_general_api_settings(self) -> None:
        """Test case for get_general_api_settings

        Get instance's global settings for api
        """
        pass

    def test_get_general_attachment_settings(self) -> None:
        """Test case for get_general_attachment_settings

        Get instance's global settings for Attachment
        """
        pass

    def test_get_general_repository_settings(self) -> None:
        """Test case for get_general_repository_settings

        Get instance's global settings for repositories
        """
        pass

    def test_get_general_ui_settings(self) -> None:
        """Test case for get_general_ui_settings

        Get instance's global settings for ui
        """
        pass


if __name__ == '__main__':
    unittest.main()
