# coding: utf-8

"""
    slug-loves-beans

    this description is required

    The version of the OpenAPI document: 13.0.4+gitea-1.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.notification_api import NotificationApi


class TestNotificationApi(unittest.TestCase):
    """NotificationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NotificationApi()

    def tearDown(self) -> None:
        pass

    def test_notify_get_list(self) -> None:
        """Test case for notify_get_list

        List users's notification threads
        """
        pass

    def test_notify_get_repo_list(self) -> None:
        """Test case for notify_get_repo_list

        List users's notification threads on a specific repo
        """
        pass

    def test_notify_get_thread(self) -> None:
        """Test case for notify_get_thread

        Get notification thread by ID
        """
        pass

    def test_notify_new_available(self) -> None:
        """Test case for notify_new_available

        Check if unread notifications exist
        """
        pass

    def test_notify_read_list(self) -> None:
        """Test case for notify_read_list

        Mark notification threads as read, pinned or unread
        """
        pass

    def test_notify_read_repo_list(self) -> None:
        """Test case for notify_read_repo_list

        Mark notification threads as read, pinned or unread on a specific repo
        """
        pass

    def test_notify_read_thread(self) -> None:
        """Test case for notify_read_thread

        Mark notification thread as read by ID
        """
        pass


if __name__ == '__main__':
    unittest.main()
