# coding: utf-8

"""
    slug-loves-beans

    this description is required

    The version of the OpenAPI document: 13.0.4+gitea-1.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_variable_option import CreateVariableOption

class TestCreateVariableOption(unittest.TestCase):
    """CreateVariableOption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateVariableOption:
        """Test CreateVariableOption
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateVariableOption`
        """
        model = CreateVariableOption()
        if include_optional:
            return CreateVariableOption(
                value = ''
            )
        else:
            return CreateVariableOption(
                value = '',
        )
        """

    def testCreateVariableOption(self):
        """Test CreateVariableOption"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
