# coding: utf-8

"""
    slug-loves-beans

    this description is required

    The version of the OpenAPI document: 13.0.4+gitea-1.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.generate_repo_option import GenerateRepoOption

class TestGenerateRepoOption(unittest.TestCase):
    """GenerateRepoOption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GenerateRepoOption:
        """Test GenerateRepoOption
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GenerateRepoOption`
        """
        model = GenerateRepoOption()
        if include_optional:
            return GenerateRepoOption(
                avatar = True,
                default_branch = '',
                description = '',
                git_content = True,
                git_hooks = True,
                labels = True,
                name = '',
                owner = '',
                private = True,
                protected_branch = True,
                topics = True,
                webhooks = True
            )
        else:
            return GenerateRepoOption(
                name = '',
                owner = '',
        )
        """

    def testGenerateRepoOption(self):
        """Test GenerateRepoOption"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
