# coding: utf-8

"""
    slug-loves-beans

    this description is required

    The version of the OpenAPI document: 13.0.4+gitea-1.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.license_template_info import LicenseTemplateInfo

class TestLicenseTemplateInfo(unittest.TestCase):
    """LicenseTemplateInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LicenseTemplateInfo:
        """Test LicenseTemplateInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LicenseTemplateInfo`
        """
        model = LicenseTemplateInfo()
        if include_optional:
            return LicenseTemplateInfo(
                body = '',
                implementation = '',
                key = '',
                name = '',
                url = ''
            )
        else:
            return LicenseTemplateInfo(
        )
        """

    def testLicenseTemplateInfo(self):
        """Test LicenseTemplateInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
