# coding: utf-8

"""
    slug-loves-beans

    this description is required

    The version of the OpenAPI document: 13.0.4+gitea-1.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.quota_used_size import QuotaUsedSize

class TestQuotaUsedSize(unittest.TestCase):
    """QuotaUsedSize unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QuotaUsedSize:
        """Test QuotaUsedSize
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QuotaUsedSize`
        """
        model = QuotaUsedSize()
        if include_optional:
            return QuotaUsedSize(
                assets = openapi_client.models.quota_used_size_assets.QuotaUsedSizeAssets(
                    artifacts = 56, 
                    attachments = openapi_client.models.quota_used_size_assets_attachments.QuotaUsedSizeAssetsAttachments(
                        issues = 56, 
                        releases = 56, ), 
                    packages = openapi_client.models.quota_used_size_assets_packages.QuotaUsedSizeAssetsPackages(
                        all = 56, ), ),
                git = openapi_client.models.quota_used_size_git.QuotaUsedSizeGit(
                    lfs = 56, ),
                repos = openapi_client.models.quota_used_size_repos.QuotaUsedSizeRepos(
                    private = 56, 
                    public = 56, )
            )
        else:
            return QuotaUsedSize(
        )
        """

    def testQuotaUsedSize(self):
        """Test QuotaUsedSize"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
