# coding: utf-8

"""
    slug-loves-beans

    this description is required

    The version of the OpenAPI document: 13.0.4+gitea-1.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.api_internal_server_error import APIInternalServerError

class TestAPIInternalServerError(unittest.TestCase):
    """APIInternalServerError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> APIInternalServerError:
        """Test APIInternalServerError
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `APIInternalServerError`
        """
        model = APIInternalServerError()
        if include_optional:
            return APIInternalServerError(
                message = '',
                url = ''
            )
        else:
            return APIInternalServerError(
        )
        """

    def testAPIInternalServerError(self):
        """Test APIInternalServerError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
