# coding: utf-8

"""
    slug-loves-beans

    this description is required

    The version of the OpenAPI document: 13.0.4+gitea-1.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.edit_issue_option import EditIssueOption

class TestEditIssueOption(unittest.TestCase):
    """EditIssueOption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EditIssueOption:
        """Test EditIssueOption
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EditIssueOption`
        """
        model = EditIssueOption()
        if include_optional:
            return EditIssueOption(
                assignee = '',
                assignees = [
                    ''
                    ],
                body = '',
                due_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                milestone = 56,
                ref = '',
                state = '',
                title = '',
                unset_due_date = True,
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return EditIssueOption(
        )
        """

    def testEditIssueOption(self):
        """Test EditIssueOption"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
