# coding: utf-8

"""
    slug-loves-beans

    this description is required

    The version of the OpenAPI document: 13.0.4+gitea-1.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.o_auth2_application import OAuth2Application

class TestOAuth2Application(unittest.TestCase):
    """OAuth2Application unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OAuth2Application:
        """Test OAuth2Application
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OAuth2Application`
        """
        model = OAuth2Application()
        if include_optional:
            return OAuth2Application(
                client_id = '',
                client_secret = '',
                confidential_client = True,
                created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = 56,
                name = '',
                redirect_uris = [
                    ''
                    ]
            )
        else:
            return OAuth2Application(
        )
        """

    def testOAuth2Application(self):
        """Test OAuth2Application"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
