# coding: utf-8

"""
    slug-loves-beans

    this description is required

    The version of the OpenAPI document: 13.0.4+gitea-1.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.dispatch_workflow_option import DispatchWorkflowOption

class TestDispatchWorkflowOption(unittest.TestCase):
    """DispatchWorkflowOption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DispatchWorkflowOption:
        """Test DispatchWorkflowOption
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DispatchWorkflowOption`
        """
        model = DispatchWorkflowOption()
        if include_optional:
            return DispatchWorkflowOption(
                inputs = {
                    'key' : ''
                    },
                ref = '',
                return_run_info = True
            )
        else:
            return DispatchWorkflowOption(
                ref = '',
        )
        """

    def testDispatchWorkflowOption(self):
        """Test DispatchWorkflowOption"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
