# coding: utf-8

"""
    slug-loves-beans

    this description is required

    The version of the OpenAPI document: 13.0.4+gitea-1.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.sync_fork_info import SyncForkInfo

class TestSyncForkInfo(unittest.TestCase):
    """SyncForkInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SyncForkInfo:
        """Test SyncForkInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SyncForkInfo`
        """
        model = SyncForkInfo()
        if include_optional:
            return SyncForkInfo(
                allowed = True,
                base_commit = '',
                commits_behind = 56,
                fork_commit = ''
            )
        else:
            return SyncForkInfo(
        )
        """

    def testSyncForkInfo(self):
        """Test SyncForkInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
