// This file is auto-generated by @hey-api/openapi-ts

export type ArchetypeCreate = {
  title: string
  description?: string | null
}

/**
 * Public model for Archetype API responses.
 */
export type ArchetypePublic = {
  title: string
  description?: string | null
  id: string
  created_at: string
}

/**
 * Collection model for Archetype API responses.
 */
export type ArchetypesPublic = {
  data: Array<ArchetypePublic>
  count: number
}

export type ArchetypeUpdate = {
  title?: string | null
  description?: string | null
}

export type Body_login_login_access_token = {
  grant_type?: string | null
  username: string
  password: string
  scope?: string
  client_id?: string | null
  client_secret?: string | null
}

/**
 * Model for creating events
 */
export type EventCreate = {
  name: string
  description?: string | null
  event_type: string
}

/**
 * Public model for Event API responses.
 */
export type EventPublic = {
  name: string
  description?: string | null
  event_type: string
  id: string
  created_at: string
}

/**
 * Collection model for Event API responses.
 */
export type EventsPublic = {
  data: Array<EventPublic>
  count: number
}

/**
 * Model for updating events
 */
export type EventUpdate = {
  name?: string | null
  description?: string | null
  event_type?: string | null
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type ItemCreate = {
  title: string
  description?: string | null
}

export type ItemPublic = {
  title: string
  description?: string | null
  id: string
  owner_id: string
}

export type ItemsPublic = {
  data: Array<ItemPublic>
  count: number
}

export type ItemUpdate = {
  title?: string | null
  description?: string | null
}

export type Message = {
  message: string
}

export type NewPassword = {
  token: string
  new_password: string
}

/**
 * Database model for Persona.
 * Relationships defined after model declarations.
 */
export type Persona = {
  title: string
  description?: string | null
  id?: string
  created_at?: string
}

export type PersonaCreate = {
  title: string
  description?: string | null
}

/**
 * Public model for Persona API responses.
 */
export type PersonaPublic = {
  title: string
  description?: string | null
  id: string
  created_at: string
}

/**
 * Collection model for Personas API responses.
 */
export type PersonasPublic = {
  data: Array<PersonaPublic>
  count: number
}

export type PersonaUpdate = {
  title?: string | null
  description?: string | null
}

export type PrivateUserCreate = {
  email: string
  password: string
  full_name: string
  is_verified?: boolean
}

/**
 * Collection model for Quality API responses.
 */
export type QualitiesPublic = {
  data: Array<QualityPublic>
  count: number
}

export type QualityCreate = {
  title: string
  description?: string | null
}

/**
 * Public model for Quality API responses.
 */
export type QualityPublic = {
  title: string
  description?: string | null
  id: string
  created_at: string
}

export type QualityTraitLinkCreate = {
  quality_id: string
  trait_id: string
  auto_enable?: boolean
  is_required?: boolean
}

export type QualityTraitLinkPublic = {
  quality_id: string
  trait_id: string
  id: string
  created_at: string
  auto_enable: boolean
  is_required: boolean
  trait?: TraitPublic | null
  quality?: QualityPublic | null
}

export type QualityUpdate = {
  title?: string | null
  description?: string | null
}

export type Token = {
  access_token: string
  token_type?: string
}

export type TraitCreate = {
  title: string
  description?: string | null
}

/**
 * Public model for Trait API responses.
 */
export type TraitPublic = {
  title: string
  description?: string | null
  id: string
  created_at: string
}

/**
 * Collection model for Trait API responses.
 */
export type TraitsPublic = {
  data: Array<TraitPublic>
  count: number
}

export type TraitUpdate = {
  title?: string | null
}

export type UpdatePassword = {
  current_password: string
  new_password: string
}

export type UserCreate = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  password: string
}

export type UserPublic = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  id: string
}

export type UserRegister = {
  email: string
  password: string
  full_name?: string | null
}

export type UsersPublic = {
  data: Array<UserPublic>
  count: number
}

export type UserUpdate = {
  email?: string | null
  is_active?: boolean | null
  is_superuser?: boolean | null
  full_name?: string | null
  password?: string | null
}

export type UserUpdateMe = {
  full_name?: string | null
  email?: string | null
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type ArchetypesReadArchetypesData = {
  limit?: number
  skip?: number
}

export type ArchetypesReadArchetypesResponse = ArchetypesPublic

export type ArchetypesCreateArchetypeData = {
  requestBody: ArchetypeCreate
}

export type ArchetypesCreateArchetypeResponse = ArchetypePublic

export type ArchetypesReadArchetypeData = {
  id: string
}

export type ArchetypesReadArchetypeResponse = ArchetypePublic

export type ArchetypesUpdateArchetypeData = {
  id: string
  requestBody: ArchetypeUpdate
}

export type ArchetypesUpdateArchetypeResponse = ArchetypePublic

export type ArchetypesDeleteArchetypeData = {
  id: string
}

export type ArchetypesDeleteArchetypeResponse = Message

export type EventsReadEventsData = {
  limit?: number
  skip?: number
}

export type EventsReadEventsResponse = EventsPublic

export type EventsCreateEventData = {
  requestBody: EventCreate
}

export type EventsCreateEventResponse = EventPublic

export type EventsReadEventData = {
  id: string
}

export type EventsReadEventResponse = EventPublic

export type EventsUpdateEventData = {
  id: string
  requestBody: EventUpdate
}

export type EventsUpdateEventResponse = EventPublic

export type EventsDeleteEventData = {
  id: string
}

export type EventsDeleteEventResponse = Message

export type ItemsReadItemsData = {
  limit?: number
  skip?: number
}

export type ItemsReadItemsResponse = ItemsPublic

export type ItemsCreateItemData = {
  requestBody: ItemCreate
}

export type ItemsCreateItemResponse = ItemPublic

export type ItemsReadItemData = {
  id: string
}

export type ItemsReadItemResponse = ItemPublic

export type ItemsUpdateItemData = {
  id: string
  requestBody: ItemUpdate
}

export type ItemsUpdateItemResponse = ItemPublic

export type ItemsDeleteItemData = {
  id: string
}

export type ItemsDeleteItemResponse = Message

export type LoginLoginAccessTokenData = {
  formData: Body_login_login_access_token
}

export type LoginLoginAccessTokenResponse = Token

export type LoginTestTokenResponse = UserPublic

export type LoginRecoverPasswordData = {
  email: string
}

export type LoginRecoverPasswordResponse = Message

export type LoginResetPasswordData = {
  requestBody: NewPassword
}

export type LoginResetPasswordResponse = Message

export type LoginRecoverPasswordHtmlContentData = {
  email: string
}

export type LoginRecoverPasswordHtmlContentResponse = string

export type PersonaEventsProcessPersonaEventData = {
  eventId: string
  personaId: string
}

export type PersonaEventsProcessPersonaEventResponse = Message

export type PersonaQualitiesReadPersonaQualitiesData = {
  personaId: string
}

export type PersonaQualitiesReadPersonaQualitiesResponse = Array<QualityPublic>

export type PersonaQualitiesAddQualityToPersonaData = {
  personaId: string
  qualityId: string
}

export type PersonaQualitiesAddQualityToPersonaResponse = Message

export type PersonaQualitiesRemoveQualityFromPersonaData = {
  personaId: string
  qualityId: string
}

export type PersonaQualitiesRemoveQualityFromPersonaResponse = Message

export type PersonasReadPersonasData = {
  limit?: number
  skip?: number
}

export type PersonasReadPersonasResponse = PersonasPublic

export type PersonasCreatePersonaData = {
  requestBody: PersonaCreate
}

export type PersonasCreatePersonaResponse = PersonaPublic

export type PersonasReadPersonaData = {
  id: string
}

export type PersonasReadPersonaResponse = Persona

export type PersonasUpdatePersonaData = {
  id: string
  requestBody: PersonaUpdate
}

export type PersonasUpdatePersonaResponse = PersonaPublic

export type PersonasDeletePersonaData = {
  id: string
}

export type PersonasDeletePersonaResponse = Message

export type PersonasCreatePersonaFromArchetypeData = {
  archetypeId: string
  requestBody: PersonaCreate
}

export type PersonasCreatePersonaFromArchetypeResponse = PersonaPublic

export type PrivateCreateUserData = {
  requestBody: PrivateUserCreate
}

export type PrivateCreateUserResponse = UserPublic

export type QualitiesReadQualitiesData = {
  limit?: number
  skip?: number
}

export type QualitiesReadQualitiesResponse = QualitiesPublic

export type QualitiesCreateQualityData = {
  requestBody: QualityCreate
}

export type QualitiesCreateQualityResponse = QualityPublic

export type QualitiesReadQualityData = {
  id: string
}

export type QualitiesReadQualityResponse = QualityPublic

export type QualitiesUpdateQualityData = {
  id: string
  requestBody: QualityUpdate
}

export type QualitiesUpdateQualityResponse = QualityPublic

export type QualitiesDeleteQualityData = {
  id: string
}

export type QualitiesDeleteQualityResponse = Message

export type QualityTraitLinksReadQualityTraitsData = {
  qualityId: string
}

export type QualityTraitLinksReadQualityTraitsResponse = Array<TraitPublic>

export type QualityTraitLinksReadTraitQualitiesData = {
  traitId: string
}

export type QualityTraitLinksReadTraitQualitiesResponse = Array<QualityPublic>

export type QualityTraitLinksCreateQualityTraitLinkData = {
  requestBody: QualityTraitLinkCreate
}

export type QualityTraitLinksCreateQualityTraitLinkResponse =
  QualityTraitLinkPublic

export type QualityTraitLinksDeleteQualityTraitLinkData = {
  qualityId: string
  traitId: string
}

export type QualityTraitLinksDeleteQualityTraitLinkResponse = Message

export type TraitsReadTraitsData = {
  limit?: number
  skip?: number
}

export type TraitsReadTraitsResponse = TraitsPublic

export type TraitsCreateTraitData = {
  requestBody: TraitCreate
}

export type TraitsCreateTraitResponse = TraitPublic

export type TraitsReadTraitData = {
  id: string
}

export type TraitsReadTraitResponse = TraitPublic

export type TraitsUpdateTraitData = {
  id: string
  requestBody: TraitUpdate
}

export type TraitsUpdateTraitResponse = TraitPublic

export type TraitsDeleteTraitData = {
  id: string
}

export type TraitsDeleteTraitResponse = Message

export type UsersReadUsersData = {
  limit?: number
  skip?: number
}

export type UsersReadUsersResponse = UsersPublic

export type UsersCreateUserData = {
  requestBody: UserCreate
}

export type UsersCreateUserResponse = UserPublic

export type UsersReadUserMeResponse = UserPublic

export type UsersDeleteUserMeResponse = Message

export type UsersUpdateUserMeData = {
  requestBody: UserUpdateMe
}

export type UsersUpdateUserMeResponse = UserPublic

export type UsersUpdatePasswordMeData = {
  requestBody: UpdatePassword
}

export type UsersUpdatePasswordMeResponse = Message

export type UsersRegisterUserData = {
  requestBody: UserRegister
}

export type UsersRegisterUserResponse = UserPublic

export type UsersReadUserByIdData = {
  userId: string
}

export type UsersReadUserByIdResponse = UserPublic

export type UsersUpdateUserData = {
  requestBody: UserUpdate
  userId: string
}

export type UsersUpdateUserResponse = UserPublic

export type UsersDeleteUserData = {
  userId: string
}

export type UsersDeleteUserResponse = Message

export type UtilsTestEmailData = {
  emailTo: string
}

export type UtilsTestEmailResponse = Message

export type UtilsHealthCheckResponse = boolean
