// This file is auto-generated by @hey-api/openapi-ts

export type AgentConfigCreate = {
    /**
     * Display name
     */
    name: string;
    /**
     * Unique identifier/registry key
     */
    slug: string;
    description?: (string | null);
    model_name?: string;
    system_prompt?: (string | null);
    tool_config?: ({
    [key: string]: unknown;
} | null);
    deps_config?: ({
    [key: string]: unknown;
} | null);
    agent_metadata?: ({
    [key: string]: unknown;
} | null);
    is_enabled?: boolean;
    scope?: string;
    participation_mode?: string;
    is_coordinator?: boolean;
    capabilities?: Array<(string)>;
};

export type AgentConfigPublic = {
    /**
     * Display name
     */
    name: string;
    /**
     * Unique identifier/registry key
     */
    slug: string;
    description?: (string | null);
    model_name?: string;
    system_prompt?: (string | null);
    tool_config?: ({
    [key: string]: unknown;
} | null);
    deps_config?: ({
    [key: string]: unknown;
} | null);
    agent_metadata?: ({
    [key: string]: unknown;
} | null);
    is_enabled?: boolean;
    scope?: string;
    participation_mode?: string;
    is_coordinator?: boolean;
    capabilities?: Array<(string)>;
    id: string;
    owner_id: (string | null);
    created_at: string;
    updated_at: (string | null);
    version: number;
};

export type AgentConfigsPublic = {
    data: Array<AgentConfigPublic>;
    count: number;
};

export type AgentConfigUpdate = {
    name?: (string | null);
    description?: (string | null);
    model_name?: (string | null);
    system_prompt?: (string | null);
    tool_config?: ({
    [key: string]: unknown;
} | null);
    deps_config?: ({
    [key: string]: unknown;
} | null);
    agent_metadata?: ({
    [key: string]: unknown;
} | null);
    is_enabled?: (boolean | null);
    participation_mode?: (string | null);
    is_coordinator?: (boolean | null);
    capabilities?: (Array<(string)> | null);
};

export type AgentPersonaCreate = {
    nickname?: (string | null);
    is_active?: boolean;
    persona_id: string;
};

/**
 * Public model for AgentPersona API responses.
 */
export type AgentPersonaPublic = {
    nickname?: (string | null);
    is_active?: boolean;
    id: string;
    agent_id: string;
    persona_id: string;
    created_at: string;
    updated_at: string;
};

/**
 * Collection model for AgentPersona API responses.
 */
export type AgentPersonasPublic = {
    data: Array<AgentPersonaPublic>;
    count: number;
};

export type AgentPersonaUpdate = {
    nickname?: (string | null);
    is_active?: (boolean | null);
};

export type ArchetypeCreate = {
    name: string;
    description?: (string | null);
};

/**
 * Public model for Archetype API responses.
 */
export type ArchetypePublic = {
    name: string;
    description?: (string | null);
    id: string;
    created_at: string;
};

/**
 * Collection model for Archetype API responses.
 */
export type ArchetypesPublic = {
    data: Array<ArchetypePublic>;
    count: number;
};

export type ArchetypeUpdate = {
    name?: (string | null);
    description?: (string | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ContentFormat = 'text' | 'html' | 'markdown' | 'json';

/**
 * Response model for getting current node with available choices.
 * Used by players to understand their current position in a story.
 */
export type CurrentNodePublic = {
    node: StoryNodePublic;
    available_choices: Array<NodeChoicePublic>;
    story_state: ({
    [key: string]: unknown;
} | null);
};

/**
 * Model for creating events
 */
export type EventCreate = {
    name: string;
    description?: (string | null);
    event_type: string;
};

/**
 * Public model for Event API responses.
 */
export type EventPublic = {
    name: string;
    description?: (string | null);
    event_type: string;
    id: string;
    created_at: string;
};

/**
 * Collection model for Event API responses.
 */
export type EventsPublic = {
    data: Array<EventPublic>;
    count: number;
};

/**
 * Model for updating events
 */
export type EventUpdate = {
    name?: (string | null);
    description?: (string | null);
    event_type?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    name: string;
    description?: (string | null);
};

export type ItemPublic = {
    name: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    name?: (string | null);
    description?: (string | null);
};

/**
 * Request model for jumping to ancestor choice.
 *
 * Used by jump endpoint to specify target and optimistic concurrency check.
 */
export type JumpRequest = {
    /**
     * Target choice to jump to (null = jump to story start)
     */
    choice_id?: (string | null);
    /**
     * Optimistic concurrency check - must match current head_version
     */
    expected_head_version: number;
};

/**
 * Input model for creating a model catalog entry.
 */
export type LLMModelCreate = {
    /**
     * Model identifier (e.g., 'gpt-4o', no provider prefix)
     */
    model_id: string;
    display_name?: (string | null);
    description?: (string | null);
    /**
     * Max tokens in context window
     */
    context_window?: (number | null);
    /**
     * system model
     */
    is_system?: boolean;
    /**
     * Default/cheapest model for this provider
     */
    is_default?: boolean;
    /**
     * Whether model is available for use
     */
    is_enabled?: boolean;
    /**
     * Model is deprecated (still works)
     */
    is_deprecated?: boolean;
    /**
     * Display ordering within provider
     */
    sort_order?: number;
    /**
     * Supports image input
     */
    has_vision?: (boolean | null);
    /**
     * Supports function/tool calling
     */
    has_function_calling?: (boolean | null);
    /**
     * Supports streaming responses
     */
    has_streaming?: (boolean | null);
    /**
     * Supports JSON output mode
     */
    has_json_mode?: (boolean | null);
    /**
     * Additional capability flags as JSON
     */
    secondary_capabilities?: ({
    [key: string]: unknown;
} | null);
    provider_id: string;
};

/**
 * Public API response for a model catalog entry.
 */
export type LLMModelPublic = {
    /**
     * Model identifier (e.g., 'gpt-4o', no provider prefix)
     */
    model_id: string;
    /**
     * Human-friendly name (e.g., 'GPT-4o')
     */
    display_name: string;
    description?: (string | null);
    /**
     * Max tokens in context window
     */
    context_window?: (number | null);
    is_system: boolean;
    /**
     * Default/cheapest model for this provider
     */
    is_default?: boolean;
    /**
     * Whether model is available for use
     */
    is_enabled?: boolean;
    /**
     * Model is deprecated (still works)
     */
    is_deprecated?: boolean;
    /**
     * Display ordering within provider
     */
    sort_order?: number;
    /**
     * Supports image input
     */
    has_vision?: (boolean | null);
    /**
     * Supports function/tool calling
     */
    has_function_calling?: (boolean | null);
    /**
     * Supports streaming responses
     */
    has_streaming?: (boolean | null);
    /**
     * Supports JSON output mode
     */
    has_json_mode?: (boolean | null);
    /**
     * Additional capability flags as JSON
     */
    secondary_capabilities?: ({
    [key: string]: unknown;
} | null);
    id: string;
    provider_id: string;
    deprecated_at: (string | null);
    sunset_at: (string | null);
    is_deleted: boolean;
    created_at: string;
    updated_at: string;
    provider_type?: (LLMProviderType | null);
    provider_name?: (string | null);
};

/**
 * Models grouped by provider for UI display.
 */
export type LLMModelsGrouped = {
    providers: Array<LLMProviderWithModels>;
    total_models: number;
};

/**
 * Collection response for LLMModels.
 */
export type LLMModelsPublic = {
    data: Array<LLMModelPublic>;
    count: number;
};

/**
 * Public API response for a provider catalog entry.
 */
export type LLMProviderPublic = {
    /**
     * Display name like 'OpenAI', 'Anthropic'
     */
    name: string;
    /**
     * Provider type enum value
     */
    provider_type?: LLMProviderType;
    /**
     * Default base URL (for openai_compatible)
     */
    base_url?: (string | null);
    description?: (string | null);
    /**
     * Whether this provider is available
     */
    is_enabled?: boolean;
    /**
     * True for built-in, False for user-created (future)
     */
    is_system?: boolean;
    id: string;
    is_deleted: boolean;
    created_at: string;
    updated_at: string;
    /**
     * Number of active models for this provider
     */
    model_count?: number;
};

/**
 * Collection response for LLMProviders.
 */
export type LLMProvidersPublic = {
    data: Array<LLMProviderPublic>;
    count: number;
};

/**
 * Supported LLM provider types.
 */
export type LLMProviderType = 'empty' | 'openai' | 'anthropic' | 'google' | 'openai_compatible';

/**
 * Provider with nested list of its models.
 */
export type LLMProviderWithModels = {
    /**
     * Display name like 'OpenAI', 'Anthropic'
     */
    name: string;
    /**
     * Provider type enum value
     */
    provider_type?: LLMProviderType;
    /**
     * Default base URL (for openai_compatible)
     */
    base_url?: (string | null);
    description?: (string | null);
    /**
     * Whether this provider is available
     */
    is_enabled?: boolean;
    /**
     * True for built-in, False for user-created (future)
     */
    is_system?: boolean;
    id: string;
    is_deleted: boolean;
    created_at: string;
    updated_at: string;
    /**
     * Number of active models for this provider
     */
    model_count?: number;
    models?: Array<LLMModelPublic>;
};

export type Message = {
    message: string;
};

/**
 * Request model for toggling message context inclusion.
 */
export type MessageContextToggle = {
    active_for_context: boolean;
};

/**
 * Request model for editing message content.
 */
export type MessageEdit = {
    content: string;
};

/**
 * Generic success message response.
 *
 * Used for operations that need to return a simple success message.
 */
export type MessageResponse = {
    /**
     * Success message
     */
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * Base model for NodeChoice (decision branch in story template)
 */
export type NodeChoiceBase = {
    text: string;
    order?: number;
    requires_state?: ({
    [key: string]: unknown;
} | null);
    sets_state?: ({
    [key: string]: unknown;
} | null);
};

/**
 * Input model for creating a NodeChoice
 */
export type NodeChoiceCreate = {
    text: string;
    order?: number;
    requires_state?: ({
    [key: string]: unknown;
} | null);
    sets_state?: ({
    [key: string]: unknown;
} | null);
    from_node_id: string;
    to_node_id: string;
};

/**
 * Public API response model for NodeChoice
 */
export type NodeChoicePublic = {
    text: string;
    order?: number;
    requires_state?: ({
    [key: string]: unknown;
} | null);
    sets_state?: ({
    [key: string]: unknown;
} | null);
    id: string;
    from_node_id: string;
    to_node_id: string;
};

/**
 * Collection response for NodeChoices
 */
export type NodeChoicesPublic = {
    data: Array<NodeChoicePublic>;
    count: number;
};

/**
 * Input model for updating NodeChoice (all fields optional)
 */
export type NodeChoiceUpdate = {
    text?: (string | null);
    order?: (number | null);
    to_node_id?: (string | null);
    requires_state?: ({
    [key: string]: unknown;
} | null);
    sets_state?: ({
    [key: string]: unknown;
} | null);
};

/**
 * Request model for adding a participant to a room.
 *
 * Used by: POST /rooms/{room_id}/participants
 */
export type ParticipantAddRequest = {
    /**
     * UUID string for users, AgentConfig.slug for agents
     */
    participant_id: string;
    /**
     * Type of participant (user or agent)
     */
    participant_type: 'user' | 'agent';
    /**
     * Participant role (default: member)
     */
    role?: 'owner' | 'member';
};

/**
 * Type of participant (user or agent)
 */
export type participant_type = 'user' | 'agent';

/**
 * Participant role (default: member)
 */
export type role = 'owner' | 'member';

/**
 * Request model for setting a participant's active binding in a room.
 *
 * Payload is event-sourced via participant.binding_changed.
 */
export type ParticipantBindingChangeRequest = {
    participant_type: 'user' | 'agent';
    persona_id?: (string | null);
    model_name?: (string | null);
    user_llm_provider_id?: (string | null);
};

/**
 * Request model for changing a participant's role.
 *
 * Used by: PATCH /rooms/{room_id}/participants/{participant_id}/role
 */
export type ParticipantRoleChangeRequest = {
    /**
     * New role for the participant
     */
    new_role: 'owner' | 'member';
};

/**
 * New role for the participant
 */
export type new_role = 'owner' | 'member';

/**
 * Database model for Persona.
 * Relationships defined after model declarations.
 */
export type Persona = {
    name: string;
    description?: (string | null);
    long_description?: (string | null);
    general_domain?: (string | null);
    specific_domain?: (string | null);
    general_domain_high?: (string | null);
    specific_domain_high?: (string | null);
    id?: string;
    created_at?: string;
};

export type PersonaCreate = {
    name: string;
    description?: (string | null);
    long_description?: (string | null);
    general_domain?: (string | null);
    specific_domain?: (string | null);
    general_domain_high?: (string | null);
    specific_domain_high?: (string | null);
};

/**
 * Public model for Persona API responses.
 */
export type PersonaPublic = {
    name: string;
    description?: (string | null);
    long_description?: (string | null);
    general_domain?: (string | null);
    specific_domain?: (string | null);
    general_domain_high?: (string | null);
    specific_domain_high?: (string | null);
    id: string;
    created_at: string;
};

/**
 * Collection model for Personas API responses.
 */
export type PersonasPublic = {
    data: Array<PersonaPublic>;
    count: number;
};

export type PersonaUpdate = {
    name?: (string | null);
    description?: (string | null);
    long_description?: (string | null);
    general_domain?: (string | null);
    specific_domain?: (string | null);
    general_domain_high?: (string | null);
    specific_domain_high?: (string | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * Public API response model for ProgressSnapshot
 */
export type ProgressSnapshotPublic = {
    story_state: {
        [key: string]: unknown;
    };
    current_node_id: string;
    id: string;
    progress_id: string;
    choice_id: string;
    created_at: string;
};

/**
 * Collection response for ProgressSnapshots
 */
export type ProgressSnapshotsPublic = {
    data: Array<ProgressSnapshotPublic>;
    count: number;
};

/**
 * Collection model for Quality API responses.
 */
export type QualitiesPublic = {
    data: Array<QualityPublic>;
    count: number;
};

export type QualityCreate = {
    name: string;
    description?: (string | null);
};

/**
 * Public model for Quality API responses.
 */
export type QualityPublic = {
    name: string;
    description?: (string | null);
    id: string;
    created_at: string;
};

export type QualityTraitLinkCreate = {
    quality_id: string;
    trait_id: string;
    auto_enable?: boolean;
    is_required?: boolean;
};

export type QualityTraitLinkPublic = {
    quality_id: string;
    trait_id: string;
    id: string;
    created_at: string;
    auto_enable: boolean;
    is_required: boolean;
    trait?: (TraitPublic | null);
    quality?: (QualityPublic | null);
};

export type QualityUpdate = {
    name?: (string | null);
    description?: (string | null);
};

/**
 * Resolved panel config for a user in a room
 */
export type ResolvedPanelConfig = {
    panels: Array<{
        [key: string]: unknown;
    }>;
    source: string;
};

/**
 * Properties required when creating a room via API.
 */
export type RoomCreate = {
    title?: (string | null);
    story_id?: (string | null);
};

/**
 * Public message response model for API.
 */
export type RoomMessagePublic = {
    /**
     * Message text content
     */
    content: string;
    /**
     * Either 'user' or 'agent'
     */
    sender_type: string;
    message_id: string;
    room_id: string;
    sender_id: (string | null);
    agent_name: (string | null);
    created_at: string;
    edited_at?: (string | null);
    edited_by?: (string | null);
    is_pinned?: boolean;
    pinned_at?: (string | null);
    pinned_by?: (string | null);
    active_for_context?: boolean;
    can_edit?: boolean;
    can_delete?: boolean;
    can_pin?: boolean;
    sender_display_name?: (string | null);
    button_options?: ({
    [key: string]: unknown;
} | null);
};

/**
 * Properties required when sending a message via API.
 */
export type RoomMessageSend = {
    /**
     * Message text content
     */
    content: string;
};

/**
 * Paginated collection of messages.
 */
export type RoomMessagesPublic = {
    data: Array<RoomMessagePublic>;
    count: number;
};

/**
 * Public response for room panel defaults
 */
export type RoomPanelDefaultsPublic = {
    panels?: Array<{
        [key: string]: unknown;
    }>;
    id: string;
    room_id: string;
    updated_at: string;
};

export type RoomParticipantBindingPublic = {
    /**
     * Either 'user' or 'agent'
     */
    participant_type: string;
    /**
     * UUID string for users; AgentConfig.slug for agents
     */
    participant_id: string;
    persona_id?: (string | null);
    /**
     * Same format as AgentConfig.model_name (e.g., 'openai:gpt-4o-mini')
     */
    model_name?: (string | null);
    /**
     * User-owned provider config to use (must belong to current user)
     */
    user_llm_provider_id?: (string | null);
    id: string;
    room_id: string;
    user_id: (string | null);
    agent_id: (string | null);
    effective_at: string;
    ended_at: (string | null);
    created_at: string;
};

export type RoomParticipantBindingsPublic = {
    data: Array<RoomParticipantBindingPublic>;
    count: number;
};

/**
 * Public participant response model for API.
 */
export type RoomParticipantPublic = {
    /**
     * UUID string for users, AgentConfig.slug for agents
     */
    participant_id: string;
    /**
     * Either 'user' or 'agent'
     */
    participant_type: string;
    /**
     * Either 'owner' or 'member'
     */
    role?: string;
    id: string;
    room_id: string;
    joined_at: string;
    left_at: (string | null);
    active: boolean;
};

/**
 * Paginated collection of room participants.
 */
export type RoomParticipantsPublic = {
    data: Array<RoomParticipantPublic>;
    count: number;
};

/**
 * Public room response model for API.
 */
export type RoomPublic = {
    title?: (string | null);
    story_id?: (string | null);
    room_id: string;
    creator_id: string;
    created_at: string;
    last_activity: string;
};

/**
 * Paginated collection of rooms.
 */
export type RoomsPublic = {
    data: Array<RoomPublic>;
    count: number;
};

/**
 * Properties that can be updated via API.
 */
export type RoomUpdate = {
    title?: (string | null);
};

export type StateSchemaValidationError = {
    variable_key: string;
    used_in: string;
    choice_id: string;
    choice_text: string;
    from_node_id: string;
    from_node_title: string;
};

export type StateSchemaValidationResult = {
    is_valid: boolean;
    errors: Array<StateSchemaValidationError>;
    defined_variables: Array<(string)>;
    used_variables: Array<(string)>;
    undefined_variables: Array<(string)>;
};

export type StateValueType = 'boolean' | 'number' | 'string' | 'enum';

/**
 * Collection response for Story templates
 */
export type StoriesPublic = {
    data: Array<StoryPublic>;
    count: number;
};

/**
 * Input model for creating a new Story template
 */
export type StoryCreate = {
    title: string;
    content_format?: (ContentFormat | null);
    description?: (string | null);
    is_published?: boolean;
};

/**
 * Input model for creating a StoryNode
 */
export type StoryNodeCreate = {
    title: string;
    content?: string;
    content_format?: ContentFormat;
    node_type?: (string | null);
    is_start_node?: boolean;
    is_end_node?: boolean;
    story_id: string;
    story_version: number;
};

/**
 * Public API response model for StoryNode
 */
export type StoryNodePublic = {
    title: string;
    content?: string;
    content_format?: (ContentFormat | null);
    node_type?: (string | null);
    is_start_node?: boolean;
    is_end_node?: boolean;
    id: string;
    story_id: string;
    story_version: number;
    created_at: string;
    updated_at: string;
};

/**
 * Collection response for StoryNodes
 */
export type StoryNodesPublic = {
    data: Array<StoryNodePublic>;
    count: number;
};

/**
 * Pre-computed tree structure for a story version.
 */
export type StoryNodeTree = {
    root?: (StoryNodeTreeNode | null);
    orphaned_nodes?: Array<StoryNodeTreeNode>;
    total_nodes: number;
    reachable_nodes: number;
};

/**
 * A node in the pre-computed story tree structure.
 */
export type StoryNodeTreeNode = {
    id: string;
    title: string;
    is_start_node: boolean;
    is_end_node: boolean;
    level: number;
    children?: Array<StoryNodeTreeNode>;
};

/**
 * Input model for updating StoryNode (all fields optional)
 */
export type StoryNodeUpdate = {
    title?: (string | null);
    content?: (string | null);
    content_format?: (ContentFormat | null);
    node_type?: (string | null);
    is_start_node?: (boolean | null);
    is_end_node?: (boolean | null);
};

/**
 * Public API response model for Story template
 */
export type StoryPublic = {
    title: string;
    content_format?: (ContentFormat | null);
    description?: (string | null);
    is_published: boolean;
    id: string;
    owner_id: string;
    current_version: number;
    published_version: (number | null);
    created_at: string;
    updated_at: string;
};

/**
 * Base model for Story access requirements
 */
export type StoryRequirementBase = {
    requirement_type: string;
    target_id: string;
    description?: (string | null);
};

/**
 * Public API response model for StoryRequirement
 */
export type StoryRequirementPublic = {
    requirement_type: string;
    target_id: string;
    description?: (string | null);
    id: string;
    story_id: string;
};

/**
 * Collection response for StoryRequirements
 */
export type StoryRequirementsPublic = {
    data: Array<StoryRequirementPublic>;
    count: number;
};

export type StoryStateVariableBase = {
    key: string;
    value_type?: StateValueType;
    default_value?: (unknown | null);
    enum_values?: (Array<(string)> | null);
    description?: (string | null);
    category?: (string | null);
};

export type StoryStateVariablePublic = {
    key: string;
    value_type?: StateValueType;
    default_value?: (unknown | null);
    enum_values?: (Array<(string)> | null);
    description?: (string | null);
    category?: (string | null);
    id: string;
    story_id: string;
    story_version: number;
};

export type StoryStateVariablesPublic = {
    data: Array<StoryStateVariablePublic>;
    count: number;
};

export type StoryStateVariableUpdate = {
    key?: (string | null);
    value_type?: (StateValueType | null);
    default_value?: (unknown | null);
    enum_values?: (Array<(string)> | null);
    description?: (string | null);
    category?: (string | null);
};

/**
 * Input model for updating Story template (all fields optional)
 */
export type StoryUpdate = {
    title?: (string | null);
    description?: (string | null);
    content_format?: (ContentFormat | null);
};

/**
 * Result of validating a story's graph structure for publishing.
 */
export type StoryValidationResult = {
    is_valid: boolean;
    errors: Array<(string)>;
    warnings: Array<(string)>;
    node_count: number;
    choice_count: number;
    start_node_count: number;
    end_node_count: number;
    orphaned_node_count: number;
    state_schema_validation?: (StateSchemaValidationResult | null);
};

/**
 * Active timeline from root → head.
 *
 * Contains only the ancestor chain (root to current head).
 * Siblings and abandoned branches are filtered out.
 */
export type Timeline = {
    events: Array<TimelineEvent>;
    /**
     * Current head version for optimistic locking
     */
    head_version: number;
};

/**
 * Timeline entry for UI breadcrumbs.
 *
 * Represents a single event in the player's active timeline.
 * Abandoned branches are NOT included in timeline responses.
 */
export type TimelineEvent = {
    /**
     * Choice ID (null for story start event)
     */
    choice_id: (string | null);
    /**
     * Text of the choice made
     */
    choice_text: string;
    /**
     * Title of the node reached
     */
    node_title: string;
    /**
     * When choice was made
     */
    choice_time: string;
    /**
     * Is this the current head position?
     */
    is_current: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * Input model for creating a TraitConflictGroup.
 */
export type TraitConflictGroupCreate = {
    name: string;
    description?: (string | null);
    /**
     * Type of logical conflict: 'contradictory', 'contrary', or 'subcontrary'
     */
    conflict_type: string;
    /**
     * Explanation of why these traits conflict - aids author judgment for edge cases
     */
    reason?: (string | null);
    /**
     * Optional list of trait IDs to add as members during creation
     */
    trait_ids?: (Array<(string)> | null);
};

/**
 * Input model for adding a trait to a conflict group.
 */
export type TraitConflictGroupMemberCreate = {
    /**
     * ID of the trait to add to this conflict group
     */
    trait_id: string;
};

/**
 * Public model for TraitConflictGroupMember API responses.
 */
export type TraitConflictGroupMemberPublic = {
    id: string;
    group_id: string;
    trait_id: string;
    created_at: string;
};

/**
 * Collection model for paginated member responses.
 */
export type TraitConflictGroupMembersPublic = {
    data: Array<TraitConflictGroupMemberPublic>;
    count: number;
};

/**
 * Public model for TraitConflictGroup API responses.
 */
export type TraitConflictGroupPublic = {
    name: string;
    description?: (string | null);
    /**
     * Type of logical conflict: 'contradictory', 'contrary', or 'subcontrary'
     */
    conflict_type: string;
    /**
     * Explanation of why these traits conflict - aids author judgment for edge cases
     */
    reason?: (string | null);
    id: string;
    created_at: string;
    updated_at: (string | null);
};

/**
 * Collection model for paginated TraitConflictGroup responses.
 */
export type TraitConflictGroupsPublic = {
    data: Array<TraitConflictGroupPublic>;
    count: number;
};

/**
 * Update model for TraitConflictGroup - all fields optional.
 */
export type TraitConflictGroupUpdate = {
    name?: (string | null);
    description?: (string | null);
    conflict_type?: (string | null);
    reason?: (string | null);
};

export type TraitCreate = {
    name: string;
    description?: (string | null);
};

/**
 * Public model for Trait API responses.
 */
export type TraitPublic = {
    name: string;
    description?: (string | null);
    id: string;
    created_at: string;
};

/**
 * Collection model for Trait API responses.
 */
export type TraitsPublic = {
    data: Array<TraitPublic>;
    count: number;
};

export type TraitUpdate = {
    name?: (string | null);
    description?: (string | null);
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

/**
 * Public API response for user agent settings.
 */
export type UserAgentSettingsPublic = {
    /**
     * Override the agent's default model (e.g., 'openai:gpt-4o' or 'anthropic:claude-3-5-sonnet')
     */
    model_name_override?: (string | null);
    /**
     * User's chosen LLM provider for this agent (must match model's provider type)
     */
    provider_id?: (string | null);
    /**
     * Optional user override for system prompt
     */
    custom_system_prompt?: (string | null);
    is_favorite?: boolean;
    id: string;
    user_id: string;
    agent_config_id: string;
    created_at: string;
    updated_at: string;
};

/**
 * Update model for user agent settings - all fields optional.
 */
export type UserAgentSettingsUpdate = {
    model_name_override?: (string | null);
    provider_id?: (string | null);
    custom_system_prompt?: (string | null);
    is_favorite?: (boolean | null);
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

/**
 * Input model for creating provider - accepts plain API key.
 */
export type UserLLMProviderCreate = {
    provider_type?: (LLMProviderType | null);
    /**
     * User-friendly name like 'My OpenAI' or 'Work Azure'
     */
    name: string;
    /**
     * Whether this provider is active
     */
    is_enabled?: boolean;
    /**
     * Default provider for this type
     */
    is_default?: boolean;
    /**
     * Custom endpoint URL for Azure, Ollama, etc.
     */
    base_url?: (string | null);
    description?: (string | null);
    /**
     * Plain text API key (will be encrypted)
     */
    api_key: string;
};

/**
 * Public API response - NEVER includes API key.
 */
export type UserLLMProviderPublic = {
    provider_type?: (LLMProviderType | null);
    /**
     * User-friendly name like 'My OpenAI' or 'Work Azure'
     */
    name: string;
    /**
     * Whether this provider is active
     */
    is_enabled?: boolean;
    /**
     * Default provider for this type
     */
    is_default?: boolean;
    /**
     * Custom endpoint URL for Azure, Ollama, etc.
     */
    base_url?: (string | null);
    description?: (string | null);
    id: string;
    user_id: string;
    created_at: string;
    updated_at: string;
    last_tested_at: (string | null);
    last_test_success: (boolean | null);
};

/**
 * Collection response for UserLLMProviders.
 */
export type UserLLMProvidersPublic = {
    data: Array<UserLLMProviderPublic>;
    count: number;
};

/**
 * Update model - all fields optional.
 */
export type UserLLMProviderUpdate = {
    name?: (string | null);
    is_enabled?: (boolean | null);
    is_default?: (boolean | null);
    base_url?: (string | null);
    description?: (string | null);
    /**
     * New API key to encrypt, if changing
     */
    api_key?: (string | null);
};

export type UserPersonaCreate = {
    nickname?: (string | null);
    is_active?: boolean;
    persona_id: string;
};

/**
 * Public model for UserPersona API responses
 */
export type UserPersonaPublic = {
    nickname?: (string | null);
    is_active?: boolean;
    id: string;
    user_id: string;
    persona_id: string;
    created_at: string;
    updated_at: string;
};

/**
 * Collection model for UserPersona API responses
 */
export type UserPersonasPublic = {
    data: Array<UserPersonaPublic>;
    count: number;
};

export type UserPersonaUpdate = {
    nickname?: (string | null);
    is_active?: (boolean | null);
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

/**
 * Public response for user panel config
 */
export type UserRoomPanelConfigPublic = {
    panels?: (Array<{
    [key: string]: unknown;
}> | null);
    use_room_defaults?: boolean;
    id: string;
    user_id: string;
    room_id: string;
    updated_at: string;
};

/**
 * Collection model for User API responses.
 */
export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

/**
 * Collection response for UserStoryProgresses
 */
export type UserStoryProgressesPublic = {
    data: Array<UserStoryProgressPublic>;
    count: number;
};

/**
 * Public API response model for UserStoryProgress
 */
export type UserStoryProgressPublic = {
    current_node_id?: (string | null);
    is_completed?: boolean;
    story_state?: ({
    [key: string]: unknown;
} | null);
    id: string;
    user_persona_id: string;
    story_id: string;
    story_version: number;
    head_choice_id: (string | null);
    head_version: number;
    started_at: string;
    updated_at: string;
};

/**
 * Input model for updating progress (all fields optional)
 */
export type UserStoryProgressUpdate = {
    current_node_id?: (string | null);
    is_completed?: (boolean | null);
    story_state?: ({
    [key: string]: unknown;
} | null);
    head_choice_id?: (string | null);
    head_version?: (number | null);
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AgentPersonasReadAgentPersonasData = {
    agentId: string;
    limit?: number;
    skip?: number;
};

export type AgentPersonasReadAgentPersonasResponse = (AgentPersonasPublic);

export type AgentPersonasCreateAgentPersonaData = {
    agentId: string;
    requestBody: AgentPersonaCreate;
};

export type AgentPersonasCreateAgentPersonaResponse = (AgentPersonaPublic);

export type AgentPersonasReadAgentPersonaData = {
    agentId: string;
    id: string;
};

export type AgentPersonasReadAgentPersonaResponse = (AgentPersonaPublic);

export type AgentPersonasUpdateAgentPersonaData = {
    agentId: string;
    id: string;
    requestBody: AgentPersonaUpdate;
};

export type AgentPersonasUpdateAgentPersonaResponse = (AgentPersonaPublic);

export type AgentPersonasDeleteAgentPersonaData = {
    agentId: string;
    id: string;
};

export type AgentPersonasDeleteAgentPersonaResponse = (Message);

export type AgentsListAgentsData = {
    limit?: number;
    scope?: (string | null);
    skip?: number;
};

export type AgentsListAgentsResponse = (AgentConfigsPublic);

export type AgentsCreateAgentData = {
    requestBody: AgentConfigCreate;
};

export type AgentsCreateAgentResponse = (AgentConfigPublic);

export type AgentsListAvailableAgentsData = {
    limit?: number;
    scope?: (string | null);
    skip?: number;
};

export type AgentsListAvailableAgentsResponse = (AgentConfigsPublic);

export type AgentsGetAgentData = {
    agentId: string;
};

export type AgentsGetAgentResponse = (AgentConfigPublic);

export type AgentsUpdateAgentData = {
    agentId: string;
    requestBody: AgentConfigUpdate;
};

export type AgentsUpdateAgentResponse = (AgentConfigPublic);

export type AgentsDeleteAgentData = {
    agentId: string;
};

export type AgentsDeleteAgentResponse = (Message);

export type AgentsGetMyAgentSettingsData = {
    agentId: string;
};

export type AgentsGetMyAgentSettingsResponse = ((UserAgentSettingsPublic | null));

export type AgentsUpdateMyAgentSettingsData = {
    agentId: string;
    requestBody: UserAgentSettingsUpdate;
};

export type AgentsUpdateMyAgentSettingsResponse = (UserAgentSettingsPublic);

export type AgentsDeleteMyAgentSettingsData = {
    agentId: string;
};

export type AgentsDeleteMyAgentSettingsResponse = (Message);

export type ArchetypesReadArchetypesData = {
    limit?: number;
    skip?: number;
};

export type ArchetypesReadArchetypesResponse = (ArchetypesPublic);

export type ArchetypesCreateArchetypeData = {
    requestBody: ArchetypeCreate;
};

export type ArchetypesCreateArchetypeResponse = (ArchetypePublic);

export type ArchetypesReadArchetypeData = {
    id: string;
};

export type ArchetypesReadArchetypeResponse = (ArchetypePublic);

export type ArchetypesUpdateArchetypeData = {
    id: string;
    requestBody: ArchetypeUpdate;
};

export type ArchetypesUpdateArchetypeResponse = (ArchetypePublic);

export type ArchetypesDeleteArchetypeData = {
    id: string;
};

export type ArchetypesDeleteArchetypeResponse = (Message);

export type CatalogReadCatalogData = {
    limit?: number;
    skip?: number;
};

export type CatalogReadCatalogResponse = (StoriesPublic);

export type CatalogReadCatalogStoryData = {
    storyId: string;
};

export type CatalogReadCatalogStoryResponse = (StoryPublic);

export type CatalogReadCatalogStoryNodesData = {
    limit?: number;
    skip?: number;
    storyId: string;
};

export type CatalogReadCatalogStoryNodesResponse = (StoryNodesPublic);

export type CatalogReadCatalogStoryRequirementsData = {
    storyId: string;
};

export type CatalogReadCatalogStoryRequirementsResponse = (StoryRequirementsPublic);

export type EventsReadEventsData = {
    limit?: number;
    skip?: number;
};

export type EventsReadEventsResponse = (EventsPublic);

export type EventsCreateEventData = {
    requestBody: EventCreate;
};

export type EventsCreateEventResponse = (EventPublic);

export type EventsReadEventData = {
    id: string;
};

export type EventsReadEventResponse = (EventPublic);

export type EventsUpdateEventData = {
    id: string;
    requestBody: EventUpdate;
};

export type EventsUpdateEventResponse = (EventPublic);

export type EventsDeleteEventData = {
    id: string;
};

export type EventsDeleteEventResponse = (Message);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LlmCatalogListProvidersData = {
    /**
     * Include soft-deleted providers
     */
    includeDeleted?: boolean;
    /**
     * Filter by enabled status
     */
    isEnabled?: (boolean | null);
    /**
     * Filter by system vs user-created
     */
    isSystem?: (boolean | null);
    limit?: number;
    providerType?: (LLMProviderType | null);
    skip?: number;
};

export type LlmCatalogListProvidersResponse = (LLMProvidersPublic);

export type LlmCatalogGetProviderData = {
    /**
     * Include if soft-deleted
     */
    includeDeleted?: boolean;
    providerId: string;
};

export type LlmCatalogGetProviderResponse = (LLMProviderPublic);

export type LlmCatalogListProviderModelsData = {
    /**
     * Include soft-deleted models
     */
    includeDeleted?: boolean;
    /**
     * Filter by deprecation status
     */
    isDeprecated?: (boolean | null);
    /**
     * Filter by enabled status
     */
    isEnabled?: (boolean | null);
    limit?: number;
    providerId: string;
    skip?: number;
};

export type LlmCatalogListProviderModelsResponse = (LLMModelsPublic);

export type LlmCatalogCreateCustomModelData = {
    requestBody: LLMModelCreate;
};

export type LlmCatalogCreateCustomModelResponse = (LLMModelPublic);

export type LlmCatalogListCustomModelsData = {
    /**
     * Filter by provider type
     */
    providerType?: (LLMProviderType | null);
};

export type LlmCatalogListCustomModelsResponse = (LLMModelsPublic);

export type LlmCatalogListModelsData = {
    /**
     * Filter by function calling
     */
    hasFunctionCalling?: (boolean | null);
    /**
     * Filter by JSON mode support
     */
    hasJsonMode?: (boolean | null);
    /**
     * Filter by streaming support
     */
    hasStreaming?: (boolean | null);
    /**
     * Filter by vision capability
     */
    hasVision?: (boolean | null);
    /**
     * Include soft-deleted models
     */
    includeDeleted?: boolean;
    /**
     * Filter by default model flag
     */
    isDefault?: (boolean | null);
    /**
     * Filter by deprecation status
     */
    isDeprecated?: (boolean | null);
    /**
     * Filter by enabled status
     */
    isEnabled?: (boolean | null);
    limit?: number;
    /**
     * Filter by provider ID
     */
    providerId?: (string | null);
    /**
     * Filter by provider type
     */
    providerType?: (LLMProviderType | null);
    skip?: number;
};

export type LlmCatalogListModelsResponse = (LLMModelsPublic);

export type LlmCatalogListModelsGroupedData = {
    /**
     * Include soft-deleted
     */
    includeDeleted?: boolean;
    /**
     * Filter by enabled status
     */
    isEnabled?: (boolean | null);
    /**
     * Filter by provider type
     */
    providerType?: (LLMProviderType | null);
};

export type LlmCatalogListModelsGroupedResponse = (LLMModelsGrouped);

export type LlmCatalogGetModelData = {
    /**
     * Include if soft-deleted
     */
    includeDeleted?: boolean;
    modelId: string;
};

export type LlmCatalogGetModelResponse = (LLMModelPublic);

export type LlmProvidersListProvidersData = {
    limit?: number;
    skip?: number;
};

export type LlmProvidersListProvidersResponse = (UserLLMProvidersPublic);

export type LlmProvidersCreateProviderData = {
    requestBody: UserLLMProviderCreate;
};

export type LlmProvidersCreateProviderResponse = (UserLLMProviderPublic);

export type LlmProvidersGetProviderData = {
    providerId: string;
};

export type LlmProvidersGetProviderResponse = (UserLLMProviderPublic);

export type LlmProvidersUpdateProviderData = {
    providerId: string;
    requestBody: UserLLMProviderUpdate;
};

export type LlmProvidersUpdateProviderResponse = (UserLLMProviderPublic);

export type LlmProvidersDeleteProviderData = {
    providerId: string;
};

export type LlmProvidersDeleteProviderResponse = (Message);

export type LlmProvidersTestProviderData = {
    providerId: string;
};

export type LlmProvidersTestProviderResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type NodeChoicesReadNodeChoicesData = {
    fromNodeId?: (string | null);
    limit?: number;
    skip?: number;
    storyId?: (string | null);
};

export type NodeChoicesReadNodeChoicesResponse = (NodeChoicesPublic);

export type NodeChoicesCreateNodeChoiceData = {
    requestBody: NodeChoiceCreate;
};

export type NodeChoicesCreateNodeChoiceResponse = (NodeChoicePublic);

export type NodeChoicesReadNodeChoiceData = {
    choiceId: string;
};

export type NodeChoicesReadNodeChoiceResponse = (NodeChoicePublic);

export type NodeChoicesUpdateNodeChoiceData = {
    choiceId: string;
    requestBody: NodeChoiceUpdate;
};

export type NodeChoicesUpdateNodeChoiceResponse = (NodeChoicePublic);

export type NodeChoicesDeleteNodeChoiceData = {
    choiceId: string;
};

export type NodeChoicesDeleteNodeChoiceResponse = (Message);

export type PersonaEventsProcessPersonaEventData = {
    eventId: string;
    personaId: string;
};

export type PersonaEventsProcessPersonaEventResponse = (Message);

export type PersonaQualitiesReadPersonaQualitiesData = {
    personaId: string;
};

export type PersonaQualitiesReadPersonaQualitiesResponse = (Array<QualityPublic>);

export type PersonaQualitiesAddQualityToPersonaData = {
    personaId: string;
    qualityId: string;
};

export type PersonaQualitiesAddQualityToPersonaResponse = (Message);

export type PersonaQualitiesRemoveQualityFromPersonaData = {
    personaId: string;
    qualityId: string;
};

export type PersonaQualitiesRemoveQualityFromPersonaResponse = (Message);

export type PersonasReadPersonasData = {
    limit?: number;
    skip?: number;
};

export type PersonasReadPersonasResponse = (PersonasPublic);

export type PersonasCreatePersonaData = {
    requestBody: PersonaCreate;
};

export type PersonasCreatePersonaResponse = (PersonaPublic);

export type PersonasReadPersonaData = {
    id: string;
};

export type PersonasReadPersonaResponse = (Persona);

export type PersonasUpdatePersonaData = {
    id: string;
    requestBody: PersonaUpdate;
};

export type PersonasUpdatePersonaResponse = (PersonaPublic);

export type PersonasDeletePersonaData = {
    id: string;
};

export type PersonasDeletePersonaResponse = (Message);

export type PersonasCreatePersonaFromArchetypeData = {
    archetypeId: string;
    requestBody: PersonaCreate;
};

export type PersonasCreatePersonaFromArchetypeResponse = (PersonaPublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type QualitiesReadQualitiesData = {
    limit?: number;
    skip?: number;
};

export type QualitiesReadQualitiesResponse = (QualitiesPublic);

export type QualitiesCreateQualityData = {
    requestBody: QualityCreate;
};

export type QualitiesCreateQualityResponse = (QualityPublic);

export type QualitiesReadQualityData = {
    id: string;
};

export type QualitiesReadQualityResponse = (QualityPublic);

export type QualitiesUpdateQualityData = {
    id: string;
    requestBody: QualityUpdate;
};

export type QualitiesUpdateQualityResponse = (QualityPublic);

export type QualitiesDeleteQualityData = {
    id: string;
};

export type QualitiesDeleteQualityResponse = (Message);

export type QualityTraitLinksReadQualityTraitsData = {
    qualityId: string;
};

export type QualityTraitLinksReadQualityTraitsResponse = (Array<TraitPublic>);

export type QualityTraitLinksReadTraitQualitiesData = {
    traitId: string;
};

export type QualityTraitLinksReadTraitQualitiesResponse = (Array<QualityPublic>);

export type QualityTraitLinksCreateQualityTraitLinkData = {
    requestBody: QualityTraitLinkCreate;
};

export type QualityTraitLinksCreateQualityTraitLinkResponse = (QualityTraitLinkPublic);

export type QualityTraitLinksDeleteQualityTraitLinkData = {
    qualityId: string;
    traitId: string;
};

export type QualityTraitLinksDeleteQualityTraitLinkResponse = (Message);

export type RoomPanelsGetResolvedPanelsData = {
    roomId: string;
};

export type RoomPanelsGetResolvedPanelsResponse = (ResolvedPanelConfig);

export type RoomPanelsGetRoomDefaultsData = {
    roomId: string;
};

export type RoomPanelsGetRoomDefaultsResponse = ((RoomPanelDefaultsPublic | null));

export type RoomPanelsUpdateRoomDefaultsData = {
    requestBody: Array<{
        [key: string]: unknown;
    }>;
    roomId: string;
};

export type RoomPanelsUpdateRoomDefaultsResponse = (RoomPanelDefaultsPublic);

export type RoomPanelsGetMyPanelConfigData = {
    roomId: string;
};

export type RoomPanelsGetMyPanelConfigResponse = ((UserRoomPanelConfigPublic | null));

export type RoomPanelsUpdateMyPanelConfigData = {
    requestBody: (Array<{
    [key: string]: unknown;
}> | null);
    roomId: string;
    useRoomDefaults: boolean;
};

export type RoomPanelsUpdateMyPanelConfigResponse = (UserRoomPanelConfigPublic);

export type RoomParticipantBindingsReadRoomBindingsData = {
    includeHistory?: boolean;
    roomId: string;
};

export type RoomParticipantBindingsReadRoomBindingsResponse = (RoomParticipantBindingsPublic);

export type RoomParticipantBindingsPutParticipantBindingData = {
    participantId: string;
    requestBody: ParticipantBindingChangeRequest;
    roomId: string;
};

export type RoomParticipantBindingsPutParticipantBindingResponse = (RoomParticipantBindingPublic);

export type RoomsCreateNewRoomData = {
    requestBody: RoomCreate;
};

export type RoomsCreateNewRoomResponse = (RoomPublic);

export type RoomsListUserRoomsData = {
    limit?: number;
    skip?: number;
};

export type RoomsListUserRoomsResponse = (RoomsPublic);

export type RoomsGetRoomData = {
    roomId: string;
};

export type RoomsGetRoomResponse = (RoomPublic);

export type RoomsUpdateRoomData = {
    requestBody: RoomUpdate;
    roomId: string;
};

export type RoomsUpdateRoomResponse = (RoomPublic);

export type RoomsAddRoomParticipantData = {
    requestBody: ParticipantAddRequest;
    roomId: string;
};

export type RoomsAddRoomParticipantResponse = (RoomParticipantPublic);

export type RoomsListRoomParticipantsData = {
    roomId: string;
};

export type RoomsListRoomParticipantsResponse = (RoomParticipantsPublic);

export type RoomsGetRoomsForStoryData = {
    limit?: number;
    skip?: number;
    storyId: string;
};

export type RoomsGetRoomsForStoryResponse = (RoomsPublic);

export type RoomsRemoveRoomParticipantData = {
    participantId: string;
    roomId: string;
};

export type RoomsRemoveRoomParticipantResponse = (MessageResponse);

export type RoomsChangeRoomParticipantRoleData = {
    participantId: string;
    requestBody: ParticipantRoleChangeRequest;
    roomId: string;
};

export type RoomsChangeRoomParticipantRoleResponse = (RoomParticipantPublic);

export type RoomsSendMessageData = {
    requestBody: RoomMessageSend;
    roomId: string;
};

export type RoomsSendMessageResponse = (RoomMessagePublic);

export type RoomsListMessagesData = {
    activeForContext?: (boolean | null);
    before?: (string | null);
    isPinned?: (boolean | null);
    limit?: number;
    roomId: string;
    senderId?: (string | null);
    senderType?: (string | null);
};

export type RoomsListMessagesResponse = (RoomMessagesPublic);

export type RoomsEditMessageEndpointData = {
    messageId: string;
    requestBody: MessageEdit;
    roomId: string;
};

export type RoomsEditMessageEndpointResponse = (RoomMessagePublic);

export type RoomsDeleteMessageEndpointData = {
    messageId: string;
    roomId: string;
};

export type RoomsDeleteMessageEndpointResponse = (void);

export type RoomsPinMessageEndpointData = {
    messageId: string;
    roomId: string;
};

export type RoomsPinMessageEndpointResponse = (RoomMessagePublic);

export type RoomsUnpinMessageEndpointData = {
    messageId: string;
    roomId: string;
};

export type RoomsUnpinMessageEndpointResponse = (RoomMessagePublic);

export type RoomsToggleMessageContextEndpointData = {
    messageId: string;
    requestBody: MessageContextToggle;
    roomId: string;
};

export type RoomsToggleMessageContextEndpointResponse = (RoomMessagePublic);

export type StoriesReadStoriesData = {
    limit?: number;
    skip?: number;
};

export type StoriesReadStoriesResponse = (StoriesPublic);

export type StoriesCreateStoryData = {
    requestBody: StoryCreate;
};

export type StoriesCreateStoryResponse = (StoryPublic);

export type StoriesReadStoryData = {
    id: string;
};

export type StoriesReadStoryResponse = (StoryPublic);

export type StoriesUpdateStoryData = {
    id: string;
    requestBody: StoryUpdate;
};

export type StoriesUpdateStoryResponse = (StoryPublic);

export type StoriesDeleteStoryData = {
    id: string;
};

export type StoriesDeleteStoryResponse = (Message);

export type StoriesValidateStoryData = {
    id: string;
    includeStateSchema?: boolean;
    version?: (number | null);
};

export type StoriesValidateStoryResponse = (StoryValidationResult);

export type StoriesGetStoryTreeData = {
    id: string;
    version?: (number | null);
};

export type StoriesGetStoryTreeResponse = (StoryNodeTree);

export type StoriesGetStoryStartNodeData = {
    id: string;
};

export type StoriesGetStoryStartNodeResponse = (StoryNodePublic);

export type StoriesPublishStoryData = {
    force?: boolean;
    id: string;
};

export type StoriesPublishStoryResponse = (StoryPublic);

export type StoriesUnpublishStoryData = {
    id: string;
};

export type StoriesUnpublishStoryResponse = (StoryPublic);

export type StoriesCreateNewStoryVersionData = {
    id: string;
};

export type StoriesCreateNewStoryVersionResponse = (StoryPublic);

export type StoriesReadStoryRequirementsData = {
    limit?: number;
    skip?: number;
    storyId: string;
};

export type StoriesReadStoryRequirementsResponse = (StoryRequirementsPublic);

export type StoriesCreateStoryRequirementData = {
    requestBody: StoryRequirementBase;
    storyId: string;
};

export type StoriesCreateStoryRequirementResponse = (StoryRequirementPublic);

export type StoriesDeleteStoryRequirementData = {
    requirementId: string;
    storyId: string;
};

export type StoriesDeleteStoryRequirementResponse = (Message);

export type StoriesReadStoryStateSchemaData = {
    limit?: number;
    skip?: number;
    storyId: string;
    version: number;
};

export type StoriesReadStoryStateSchemaResponse = (StoryStateVariablesPublic);

export type StoriesCreateStoryStateVariableData = {
    requestBody: StoryStateVariableBase;
    storyId: string;
    version: number;
};

export type StoriesCreateStoryStateVariableResponse = (StoryStateVariablePublic);

export type StoriesUpdateStoryStateVariableData = {
    requestBody: StoryStateVariableUpdate;
    storyId: string;
    variableId: string;
    version: number;
};

export type StoriesUpdateStoryStateVariableResponse = (StoryStateVariablePublic);

export type StoriesDeleteStoryStateVariableData = {
    storyId: string;
    variableId: string;
    version: number;
};

export type StoriesDeleteStoryStateVariableResponse = (Message);

export type StoriesValidateStoryStateSchemaData = {
    storyId: string;
    version: number;
};

export type StoriesValidateStoryStateSchemaResponse = (StateSchemaValidationResult);

export type StorynodesReadStorynodesData = {
    limit?: number;
    skip?: number;
};

export type StorynodesReadStorynodesResponse = (StoryNodesPublic);

export type StorynodesCreateStorynodeData = {
    requestBody: StoryNodeCreate;
};

export type StorynodesCreateStorynodeResponse = (StoryNodePublic);

export type StorynodesReadStorynodeData = {
    id: string;
};

export type StorynodesReadStorynodeResponse = (StoryNodePublic);

export type StorynodesUpdateStorynodeData = {
    id: string;
    requestBody: StoryNodeUpdate;
};

export type StorynodesUpdateStorynodeResponse = (StoryNodePublic);

export type StorynodesDeleteStorynodeData = {
    id: string;
};

export type StorynodesDeleteStorynodeResponse = (Message);

export type StorynodesReadNodeChoicesData = {
    limit?: number;
    nodeId: string;
    skip?: number;
};

export type StorynodesReadNodeChoicesResponse = (NodeChoicesPublic);

export type StorynodesCreateNodeChoiceFromNodeData = {
    nodeId: string;
    requestBody: NodeChoiceBase;
};

export type StorynodesCreateNodeChoiceFromNodeResponse = (NodeChoicePublic);

export type TraitConflictsReadTraitConflictGroupsData = {
    /**
     * Filter by conflict type: contradictory, contrary, subcontrary
     */
    conflictType?: (string | null);
    limit?: number;
    skip?: number;
};

export type TraitConflictsReadTraitConflictGroupsResponse = (TraitConflictGroupsPublic);

export type TraitConflictsCreateTraitConflictGroupData = {
    requestBody: TraitConflictGroupCreate;
};

export type TraitConflictsCreateTraitConflictGroupResponse = (TraitConflictGroupPublic);

export type TraitConflictsReadTraitConflictGroupData = {
    groupId: string;
};

export type TraitConflictsReadTraitConflictGroupResponse = (TraitConflictGroupPublic);

export type TraitConflictsUpdateTraitConflictGroupData = {
    groupId: string;
    requestBody: TraitConflictGroupUpdate;
};

export type TraitConflictsUpdateTraitConflictGroupResponse = (TraitConflictGroupPublic);

export type TraitConflictsDeleteTraitConflictGroupData = {
    groupId: string;
};

export type TraitConflictsDeleteTraitConflictGroupResponse = (Message);

export type TraitConflictsReadConflictGroupMembersData = {
    groupId: string;
};

export type TraitConflictsReadConflictGroupMembersResponse = (TraitConflictGroupMembersPublic);

export type TraitConflictsAddTraitToConflictGroupData = {
    groupId: string;
    requestBody: TraitConflictGroupMemberCreate;
};

export type TraitConflictsAddTraitToConflictGroupResponse = (TraitConflictGroupMemberPublic);

export type TraitConflictsRemoveTraitFromConflictGroupData = {
    groupId: string;
    traitId: string;
};

export type TraitConflictsRemoveTraitFromConflictGroupResponse = (Message);

export type TraitConflictsCheckPersonaTraitConflictsData = {
    personaId: string;
    /**
     * Trait ID to check for conflicts
     */
    traitId: string;
};

export type TraitConflictsCheckPersonaTraitConflictsResponse = (unknown);

export type TraitConflictsCheckArchetypeTraitConflictsData = {
    archetypeId: string;
    /**
     * Trait ID to check for conflicts
     */
    traitId: string;
};

export type TraitConflictsCheckArchetypeTraitConflictsResponse = (unknown);

export type TraitConflictsGetConflictGroupsByTraitData = {
    traitId: string;
};

export type TraitConflictsGetConflictGroupsByTraitResponse = (TraitConflictGroupsPublic);

export type TraitConflictsValidateConflictGroupData = {
    groupId: string;
};

export type TraitConflictsValidateConflictGroupResponse = (unknown);

export type TraitsReadTraitsData = {
    limit?: number;
    skip?: number;
};

export type TraitsReadTraitsResponse = (TraitsPublic);

export type TraitsCreateTraitData = {
    requestBody: TraitCreate;
};

export type TraitsCreateTraitResponse = (TraitPublic);

export type TraitsReadTraitData = {
    id: string;
};

export type TraitsReadTraitResponse = (TraitPublic);

export type TraitsUpdateTraitData = {
    id: string;
    requestBody: TraitUpdate;
};

export type TraitsUpdateTraitResponse = (TraitPublic);

export type TraitsDeleteTraitData = {
    id: string;
};

export type TraitsDeleteTraitResponse = (Message);

export type UserPersonasReadUserPersonasData = {
    limit?: number;
    skip?: number;
};

export type UserPersonasReadUserPersonasResponse = (UserPersonasPublic);

export type UserPersonasCreateUserPersonaData = {
    requestBody: UserPersonaCreate;
};

export type UserPersonasCreateUserPersonaResponse = (UserPersonaPublic);

export type UserPersonasReadUserPersonaData = {
    id: string;
};

export type UserPersonasReadUserPersonaResponse = (UserPersonaPublic);

export type UserPersonasUpdateUserPersonaData = {
    id: string;
    requestBody: UserPersonaUpdate;
};

export type UserPersonasUpdateUserPersonaResponse = (UserPersonaPublic);

export type UserPersonasDeleteUserPersonaData = {
    id: string;
};

export type UserPersonasDeleteUserPersonaResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UserStoryProgressReadUserStoryProgressesData = {
    limit?: number;
    skip?: number;
    userPersonaId: string;
};

export type UserStoryProgressReadUserStoryProgressesResponse = (UserStoryProgressesPublic);

export type UserStoryProgressReadUserStoryProgressData = {
    storyId: string;
    userPersonaId: string;
};

export type UserStoryProgressReadUserStoryProgressResponse = (UserStoryProgressPublic);

export type UserStoryProgressCreateUserStoryProgressData = {
    storyId: string;
    userPersonaId: string;
};

export type UserStoryProgressCreateUserStoryProgressResponse = (UserStoryProgressPublic);

export type UserStoryProgressUpdateUserStoryProgressData = {
    requestBody: UserStoryProgressUpdate;
    storyId: string;
    userPersonaId: string;
};

export type UserStoryProgressUpdateUserStoryProgressResponse = (UserStoryProgressPublic);

export type UserStoryProgressGetCurrentNodeData = {
    storyId: string;
    userPersonaId: string;
};

export type UserStoryProgressGetCurrentNodeResponse = (CurrentNodePublic);

export type UserStoryProgressMakeStoryChoiceData = {
    choiceId: string;
    storyId: string;
    userPersonaId: string;
};

export type UserStoryProgressMakeStoryChoiceResponse = (UserStoryProgressPublic);

export type UserStoryProgressValidateStoryStateData = {
    storyId: string;
    userPersonaId: string;
};

export type UserStoryProgressValidateStoryStateResponse = ({
    [key: string]: unknown;
});

export type UserStoryProgressUndoStoryChoiceData = {
    storyId: string;
    userPersonaId: string;
};

export type UserStoryProgressUndoStoryChoiceResponse = (UserStoryProgressPublic);

export type UserStoryProgressJumpStoryHeadData = {
    requestBody: JumpRequest;
    storyId: string;
    userPersonaId: string;
};

export type UserStoryProgressJumpStoryHeadResponse = (UserStoryProgressPublic);

export type UserStoryProgressReadStoryTimelineData = {
    storyId: string;
    userPersonaId: string;
};

export type UserStoryProgressReadStoryTimelineResponse = (Timeline);

export type UserStoryProgressReadStorySnapshotsData = {
    storyId: string;
    userPersonaId: string;
};

export type UserStoryProgressReadStorySnapshotsResponse = (ProgressSnapshotsPublic);

export type UserStoryProgressCreateStorySnapshotData = {
    storyId: string;
    userPersonaId: string;
};

export type UserStoryProgressCreateStorySnapshotResponse = (ProgressSnapshotPublic);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);