// This file is auto-generated by @hey-api/openapi-ts

/**
 * Public API response model for StoryNode
 */
export type app__models__StoryNodePublic__1 = {
    title: string;
    content?: string;
    node_type?: string;
    is_start_node?: boolean;
    is_end_node?: boolean;
    id: string;
    story_id: string;
    story_version: number;
    created_at: string;
    updated_at: string;
};

/**
 * Public Model for Story Node API responses
 */
export type app__models__StoryNodePublic__2 = {
    title: string;
    content?: string;
    node_type?: string;
    is_start_node?: boolean;
    is_end_node?: boolean;
    id: string;
    story_id: string;
    created_at: string;
    updated_at: string;
};

/**
 * Public API response model for Story template
 */
export type app__models__StoryPublic__1 = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    current_version: number;
    published_version: (number | null);
    is_published: boolean;
    created_at: string;
    updated_at: string;
};

/**
 * Public model for Story API responses.
 */
export type app__models__StoryPublic__2 = {
    title: string;
    description?: (string | null);
    is_published?: boolean;
    id: string;
    created_at: string;
    updated_at: string;
    owner_id: string;
};

export type ArchetypeCreate = {
    name: string;
    description?: (string | null);
};

/**
 * Public model for Archetype API responses.
 */
export type ArchetypePublic = {
    name: string;
    description?: (string | null);
    id: string;
    created_at: string;
};

/**
 * Collection model for Archetype API responses.
 */
export type ArchetypesPublic = {
    data: Array<ArchetypePublic>;
    count: number;
};

export type ArchetypeUpdate = {
    name?: (string | null);
    description?: (string | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

/**
 * Response model for getting current node with available choices.
 * Used by players to understand their current position in a story.
 */
export type CurrentNodePublic = {
    node: app__models__StoryNodePublic__2;
    available_choices: Array<NodeChoicePublic>;
    story_state: ({
    [key: string]: unknown;
} | null);
};

/**
 * Model for creating events
 */
export type EventCreate = {
    name: string;
    description?: (string | null);
    event_type: string;
};

/**
 * Public model for Event API responses.
 */
export type EventPublic = {
    name: string;
    description?: (string | null);
    event_type: string;
    id: string;
    created_at: string;
};

/**
 * Collection model for Event API responses.
 */
export type EventsPublic = {
    data: Array<EventPublic>;
    count: number;
};

/**
 * Model for updating events
 */
export type EventUpdate = {
    name?: (string | null);
    description?: (string | null);
    event_type?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    name: string;
    description?: (string | null);
};

export type ItemPublic = {
    name: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    name?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

/**
 * Generic success message response.
 *
 * Used for operations that need to return a simple success message.
 */
export type MessageResponse = {
    /**
     * Success message
     */
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type NodeChoicePublic = {
    text: string;
    order?: number;
    requires_state?: ({
    [key: string]: unknown;
} | null);
    sets_state?: ({
    [key: string]: unknown;
} | null);
    id: string;
    from_node_id: string;
    to_node_id: string;
};

/**
 * Request model for adding a participant to a room.
 *
 * Used by: POST /rooms/{room_id}/participants
 */
export type ParticipantAddRequest = {
    /**
     * UUID string for users, agent name for agents
     */
    participant_id: string;
    /**
     * Type of participant (user or agent)
     */
    participant_type: 'user' | 'agent';
    /**
     * Participant role (default: member)
     */
    role?: 'owner' | 'member';
};

/**
 * Type of participant (user or agent)
 */
export type participant_type = 'user' | 'agent';

/**
 * Participant role (default: member)
 */
export type role = 'owner' | 'member';

/**
 * Request model for changing a participant's role.
 *
 * Used by: PATCH /rooms/{room_id}/participants/{participant_id}/role
 */
export type ParticipantRoleChangeRequest = {
    /**
     * New role for the participant
     */
    new_role: 'owner' | 'member';
};

/**
 * New role for the participant
 */
export type new_role = 'owner' | 'member';

/**
 * Database model for Persona.
 * Relationships defined after model declarations.
 */
export type Persona = {
    name: string;
    description?: (string | null);
    long_description?: (string | null);
    general_domain?: (string | null);
    specific_domain?: (string | null);
    general_domain_high?: (string | null);
    specific_domain_high?: (string | null);
    id?: string;
    created_at?: string;
};

export type PersonaCreate = {
    name: string;
    description?: (string | null);
    long_description?: (string | null);
    general_domain?: (string | null);
    specific_domain?: (string | null);
    general_domain_high?: (string | null);
    specific_domain_high?: (string | null);
};

/**
 * Public model for Persona API responses.
 */
export type PersonaPublic = {
    name: string;
    description?: (string | null);
    long_description?: (string | null);
    general_domain?: (string | null);
    specific_domain?: (string | null);
    general_domain_high?: (string | null);
    specific_domain_high?: (string | null);
    id: string;
    created_at: string;
};

/**
 * Collection model for Personas API responses.
 */
export type PersonasPublic = {
    data: Array<PersonaPublic>;
    count: number;
};

export type PersonaUpdate = {
    name?: (string | null);
    description?: (string | null);
    long_description?: (string | null);
    general_domain?: (string | null);
    specific_domain?: (string | null);
    general_domain_high?: (string | null);
    specific_domain_high?: (string | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * Collection model for Quality API responses.
 */
export type QualitiesPublic = {
    data: Array<QualityPublic>;
    count: number;
};

export type QualityCreate = {
    name: string;
    description?: (string | null);
};

/**
 * Public model for Quality API responses.
 */
export type QualityPublic = {
    name: string;
    description?: (string | null);
    id: string;
    created_at: string;
};

export type QualityTraitLinkCreate = {
    quality_id: string;
    trait_id: string;
    auto_enable?: boolean;
    is_required?: boolean;
};

export type QualityTraitLinkPublic = {
    quality_id: string;
    trait_id: string;
    id: string;
    created_at: string;
    auto_enable: boolean;
    is_required: boolean;
    trait?: (TraitPublic | null);
    quality?: (QualityPublic | null);
};

export type QualityUpdate = {
    name?: (string | null);
    description?: (string | null);
};

/**
 * Properties required when creating a room via API.
 */
export type RoomCreate = {
    title?: (string | null);
    story_id?: (string | null);
};

/**
 * Public message response model for API.
 */
export type RoomMessagePublic = {
    /**
     * Message text content
     */
    content: string;
    /**
     * Either 'user' or 'agent'
     */
    sender_type: string;
    message_id: string;
    room_id: string;
    sender_id: (string | null);
    agent_name: (string | null);
    created_at: string;
    button_options?: ({
    [key: string]: unknown;
} | null);
};

/**
 * Properties required when sending a message via API.
 */
export type RoomMessageSend = {
    /**
     * Message text content
     */
    content: string;
};

/**
 * Paginated collection of messages.
 */
export type RoomMessagesPublic = {
    data: Array<RoomMessagePublic>;
    count: number;
};

/**
 * Public participant response model for API.
 */
export type RoomParticipantPublic = {
    /**
     * UUID string for users, agent name for agents
     */
    participant_id: string;
    /**
     * Either 'user' or 'agent'
     */
    participant_type: string;
    /**
     * Either 'owner' or 'member'
     */
    role?: string;
    id: string;
    room_id: string;
    joined_at: string;
    left_at: (string | null);
    active: boolean;
};

/**
 * Paginated collection of room participants.
 */
export type RoomParticipantsPublic = {
    data: Array<RoomParticipantPublic>;
    count: number;
};

/**
 * Public room response model for API.
 */
export type RoomPublic = {
    title?: (string | null);
    story_id?: (string | null);
    room_id: string;
    creator_id: string;
    created_at: string;
    last_activity: string;
};

/**
 * Paginated collection of rooms.
 */
export type RoomsPublic = {
    data: Array<RoomPublic>;
    count: number;
};

/**
 * Properties that can be updated via API.
 */
export type RoomUpdate = {
    title?: (string | null);
};

/**
 * Collection response for Story templates
 */
export type StoriesPublic = {
    data: Array<app__models__StoryPublic__1>;
    count: number;
};

/**
 * Input model for creating a new Story template
 */
export type StoryCreate = {
    title: string;
    description?: (string | null);
};

/**
 * Input model for creating a StoryNode
 */
export type StoryNodeCreate = {
    title: string;
    content?: string;
    node_type?: string;
    is_start_node?: boolean;
    is_end_node?: boolean;
    story_id: string;
    story_version: number;
};

/**
 * Collection response for StoryNodes
 */
export type StoryNodesPublic = {
    data: Array<app__models__StoryNodePublic__1>;
    count: number;
};

/**
 * Input model for updating StoryNode (all fields optional)
 */
export type StoryNodeUpdate = {
    title?: (string | null);
    content?: (string | null);
    node_type?: (string | null);
    is_start_node?: (boolean | null);
    is_end_node?: (boolean | null);
};

/**
 * Public API response model for StoryRequirement
 */
export type StoryRequirementPublic = {
    requirement_type: string;
    target_id: string;
    description?: (string | null);
    id: string;
    story_id: string;
};

/**
 * Collection response for StoryRequirements
 */
export type StoryRequirementsPublic = {
    data: Array<StoryRequirementPublic>;
    count: number;
};

/**
 * Input model for updating Story template (all fields optional)
 */
export type StoryUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type TraitCreate = {
    name: string;
    description?: (string | null);
};

/**
 * Public model for Trait API responses.
 */
export type TraitPublic = {
    name: string;
    description?: (string | null);
    id: string;
    created_at: string;
};

/**
 * Collection model for Trait API responses.
 */
export type TraitsPublic = {
    data: Array<TraitPublic>;
    count: number;
};

export type TraitUpdate = {
    name?: (string | null);
    description?: (string | null);
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPersonaCreate = {
    nickname?: (string | null);
    is_active?: boolean;
    persona_id: string;
};

/**
 * Public model for UserPersona API responses
 */
export type UserPersonaPublic = {
    nickname?: (string | null);
    is_active?: boolean;
    id: string;
    user_id: string;
    persona_id: string;
    created_at: string;
    updated_at: string;
};

/**
 * Collection model for UserPersona API responses
 */
export type UserPersonasPublic = {
    data: Array<UserPersonaPublic>;
    count: number;
};

export type UserPersonaUpdate = {
    nickname?: (string | null);
    is_active?: (boolean | null);
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

/**
 * Collection model for User API responses.
 */
export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

/**
 * Collection response for UserStoryProgresses
 */
export type UserStoryProgressesPublic = {
    data: Array<UserStoryProgressPublic>;
    count: number;
};

/**
 * Public API response model for UserStoryProgress
 */
export type UserStoryProgressPublic = {
    current_node_id?: (string | null);
    is_completed?: boolean;
    story_state?: ({
    [key: string]: unknown;
} | null);
    id: string;
    user_persona_id: string;
    story_id: string;
    story_version: number;
    started_at: string;
    updated_at: string;
};

/**
 * Input model for updating progress (all fields optional)
 */
export type UserStoryProgressUpdate = {
    current_node_id?: (string | null);
    is_completed?: (boolean | null);
    story_state?: ({
    [key: string]: unknown;
} | null);
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AgentsRunAgentResponse = (unknown);

export type ArchetypesReadArchetypesData = {
    limit?: number;
    skip?: number;
};

export type ArchetypesReadArchetypesResponse = (ArchetypesPublic);

export type ArchetypesCreateArchetypeData = {
    requestBody: ArchetypeCreate;
};

export type ArchetypesCreateArchetypeResponse = (ArchetypePublic);

export type ArchetypesReadArchetypeData = {
    id: string;
};

export type ArchetypesReadArchetypeResponse = (ArchetypePublic);

export type ArchetypesUpdateArchetypeData = {
    id: string;
    requestBody: ArchetypeUpdate;
};

export type ArchetypesUpdateArchetypeResponse = (ArchetypePublic);

export type ArchetypesDeleteArchetypeData = {
    id: string;
};

export type ArchetypesDeleteArchetypeResponse = (Message);

export type CatalogReadCatalogData = {
    limit?: number;
    skip?: number;
};

export type CatalogReadCatalogResponse = (StoriesPublic);

export type CatalogReadCatalogStoryData = {
    storyId: string;
};

export type CatalogReadCatalogStoryResponse = (app__models__StoryPublic__2);

export type CatalogReadCatalogStoryNodesData = {
    limit?: number;
    skip?: number;
    storyId: string;
};

export type CatalogReadCatalogStoryNodesResponse = (StoryNodesPublic);

export type CatalogReadCatalogStoryRequirementsData = {
    storyId: string;
};

export type CatalogReadCatalogStoryRequirementsResponse = (StoryRequirementsPublic);

export type EventsReadEventsData = {
    limit?: number;
    skip?: number;
};

export type EventsReadEventsResponse = (EventsPublic);

export type EventsCreateEventData = {
    requestBody: EventCreate;
};

export type EventsCreateEventResponse = (EventPublic);

export type EventsReadEventData = {
    id: string;
};

export type EventsReadEventResponse = (EventPublic);

export type EventsUpdateEventData = {
    id: string;
    requestBody: EventUpdate;
};

export type EventsUpdateEventResponse = (EventPublic);

export type EventsDeleteEventData = {
    id: string;
};

export type EventsDeleteEventResponse = (Message);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PersonaEventsProcessPersonaEventData = {
    eventId: string;
    personaId: string;
};

export type PersonaEventsProcessPersonaEventResponse = (Message);

export type PersonaQualitiesReadPersonaQualitiesData = {
    personaId: string;
};

export type PersonaQualitiesReadPersonaQualitiesResponse = (Array<QualityPublic>);

export type PersonaQualitiesAddQualityToPersonaData = {
    personaId: string;
    qualityId: string;
};

export type PersonaQualitiesAddQualityToPersonaResponse = (Message);

export type PersonaQualitiesRemoveQualityFromPersonaData = {
    personaId: string;
    qualityId: string;
};

export type PersonaQualitiesRemoveQualityFromPersonaResponse = (Message);

export type PersonasReadPersonasData = {
    limit?: number;
    skip?: number;
};

export type PersonasReadPersonasResponse = (PersonasPublic);

export type PersonasCreatePersonaData = {
    requestBody: PersonaCreate;
};

export type PersonasCreatePersonaResponse = (PersonaPublic);

export type PersonasReadPersonaData = {
    id: string;
};

export type PersonasReadPersonaResponse = (Persona);

export type PersonasUpdatePersonaData = {
    id: string;
    requestBody: PersonaUpdate;
};

export type PersonasUpdatePersonaResponse = (PersonaPublic);

export type PersonasDeletePersonaData = {
    id: string;
};

export type PersonasDeletePersonaResponse = (Message);

export type PersonasCreatePersonaFromArchetypeData = {
    archetypeId: string;
    requestBody: PersonaCreate;
};

export type PersonasCreatePersonaFromArchetypeResponse = (PersonaPublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type QualitiesReadQualitiesData = {
    limit?: number;
    skip?: number;
};

export type QualitiesReadQualitiesResponse = (QualitiesPublic);

export type QualitiesCreateQualityData = {
    requestBody: QualityCreate;
};

export type QualitiesCreateQualityResponse = (QualityPublic);

export type QualitiesReadQualityData = {
    id: string;
};

export type QualitiesReadQualityResponse = (QualityPublic);

export type QualitiesUpdateQualityData = {
    id: string;
    requestBody: QualityUpdate;
};

export type QualitiesUpdateQualityResponse = (QualityPublic);

export type QualitiesDeleteQualityData = {
    id: string;
};

export type QualitiesDeleteQualityResponse = (Message);

export type QualityTraitLinksReadQualityTraitsData = {
    qualityId: string;
};

export type QualityTraitLinksReadQualityTraitsResponse = (Array<TraitPublic>);

export type QualityTraitLinksReadTraitQualitiesData = {
    traitId: string;
};

export type QualityTraitLinksReadTraitQualitiesResponse = (Array<QualityPublic>);

export type QualityTraitLinksCreateQualityTraitLinkData = {
    requestBody: QualityTraitLinkCreate;
};

export type QualityTraitLinksCreateQualityTraitLinkResponse = (QualityTraitLinkPublic);

export type QualityTraitLinksDeleteQualityTraitLinkData = {
    qualityId: string;
    traitId: string;
};

export type QualityTraitLinksDeleteQualityTraitLinkResponse = (Message);

export type RoomsCreateNewRoomData = {
    requestBody: RoomCreate;
};

export type RoomsCreateNewRoomResponse = (RoomPublic);

export type RoomsListUserRoomsData = {
    limit?: number;
    skip?: number;
};

export type RoomsListUserRoomsResponse = (RoomsPublic);

export type RoomsGetRoomData = {
    roomId: string;
};

export type RoomsGetRoomResponse = (RoomPublic);

export type RoomsUpdateRoomData = {
    requestBody: RoomUpdate;
    roomId: string;
};

export type RoomsUpdateRoomResponse = (RoomPublic);

export type RoomsAddRoomParticipantData = {
    requestBody: ParticipantAddRequest;
    roomId: string;
};

export type RoomsAddRoomParticipantResponse = (RoomParticipantPublic);

export type RoomsListRoomParticipantsData = {
    roomId: string;
};

export type RoomsListRoomParticipantsResponse = (RoomParticipantsPublic);

export type RoomsRemoveRoomParticipantData = {
    participantId: string;
    roomId: string;
};

export type RoomsRemoveRoomParticipantResponse = (MessageResponse);

export type RoomsChangeRoomParticipantRoleData = {
    participantId: string;
    requestBody: ParticipantRoleChangeRequest;
    roomId: string;
};

export type RoomsChangeRoomParticipantRoleResponse = (RoomParticipantPublic);

export type RoomsSendMessageData = {
    requestBody: RoomMessageSend;
    roomId: string;
};

export type RoomsSendMessageResponse = (RoomMessagePublic);

export type RoomsListMessagesData = {
    before?: (string | null);
    limit?: number;
    roomId: string;
};

export type RoomsListMessagesResponse = (RoomMessagesPublic);

export type StoriesReadStoriesData = {
    limit?: number;
    skip?: number;
};

export type StoriesReadStoriesResponse = (StoriesPublic);

export type StoriesCreateStoryData = {
    requestBody: StoryCreate;
};

export type StoriesCreateStoryResponse = (app__models__StoryPublic__2);

export type StoriesReadStoryData = {
    id: string;
};

export type StoriesReadStoryResponse = (app__models__StoryPublic__2);

export type StoriesUpdateStoryData = {
    id: string;
    requestBody: StoryUpdate;
};

export type StoriesUpdateStoryResponse = (app__models__StoryPublic__2);

export type StoriesDeleteStoryData = {
    id: string;
};

export type StoriesDeleteStoryResponse = (Message);

export type StoriesGetStoryStartNodeData = {
    id: string;
};

export type StoriesGetStoryStartNodeResponse = (app__models__StoryNodePublic__2);

export type StoriesPublishStoryData = {
    id: string;
};

export type StoriesPublishStoryResponse = (app__models__StoryPublic__2);

export type StoriesUnpublishStoryData = {
    id: string;
};

export type StoriesUnpublishStoryResponse = (app__models__StoryPublic__2);

export type StoriesCreateNewStoryVersionData = {
    id: string;
};

export type StoriesCreateNewStoryVersionResponse = (app__models__StoryPublic__2);

export type StorynodesReadStorynodesData = {
    limit?: number;
    skip?: number;
};

export type StorynodesReadStorynodesResponse = (StoryNodesPublic);

export type StorynodesCreateStorynodeData = {
    requestBody: StoryNodeCreate;
};

export type StorynodesCreateStorynodeResponse = (app__models__StoryNodePublic__2);

export type StorynodesReadStorynodeData = {
    id: string;
};

export type StorynodesReadStorynodeResponse = (app__models__StoryNodePublic__2);

export type StorynodesUpdateStorynodeData = {
    id: string;
    requestBody: StoryNodeUpdate;
};

export type StorynodesUpdateStorynodeResponse = (app__models__StoryNodePublic__2);

export type StorynodesDeleteStorynodeData = {
    id: string;
};

export type StorynodesDeleteStorynodeResponse = (Message);

export type TraitsReadTraitsData = {
    limit?: number;
    skip?: number;
};

export type TraitsReadTraitsResponse = (TraitsPublic);

export type TraitsCreateTraitData = {
    requestBody: TraitCreate;
};

export type TraitsCreateTraitResponse = (TraitPublic);

export type TraitsReadTraitData = {
    id: string;
};

export type TraitsReadTraitResponse = (TraitPublic);

export type TraitsUpdateTraitData = {
    id: string;
    requestBody: TraitUpdate;
};

export type TraitsUpdateTraitResponse = (TraitPublic);

export type TraitsDeleteTraitData = {
    id: string;
};

export type TraitsDeleteTraitResponse = (Message);

export type UserPersonasReadUserPersonasData = {
    limit?: number;
    skip?: number;
};

export type UserPersonasReadUserPersonasResponse = (UserPersonasPublic);

export type UserPersonasCreateUserPersonaData = {
    requestBody: UserPersonaCreate;
};

export type UserPersonasCreateUserPersonaResponse = (UserPersonaPublic);

export type UserPersonasReadUserPersonaData = {
    id: string;
};

export type UserPersonasReadUserPersonaResponse = (UserPersonaPublic);

export type UserPersonasUpdateUserPersonaData = {
    id: string;
    requestBody: UserPersonaUpdate;
};

export type UserPersonasUpdateUserPersonaResponse = (UserPersonaPublic);

export type UserPersonasDeleteUserPersonaData = {
    id: string;
};

export type UserPersonasDeleteUserPersonaResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UserStoryProgressReadUserStoryProgressesData = {
    limit?: number;
    skip?: number;
    userPersonaId: string;
};

export type UserStoryProgressReadUserStoryProgressesResponse = (UserStoryProgressesPublic);

export type UserStoryProgressReadUserStoryProgressData = {
    storyId: string;
    userPersonaId: string;
};

export type UserStoryProgressReadUserStoryProgressResponse = (UserStoryProgressPublic);

export type UserStoryProgressCreateUserStoryProgressData = {
    storyId: string;
    userPersonaId: string;
};

export type UserStoryProgressCreateUserStoryProgressResponse = (UserStoryProgressPublic);

export type UserStoryProgressUpdateUserStoryProgressData = {
    requestBody: UserStoryProgressUpdate;
    storyId: string;
    userPersonaId: string;
};

export type UserStoryProgressUpdateUserStoryProgressResponse = (UserStoryProgressPublic);

export type UserStoryProgressGetCurrentNodeData = {
    storyId: string;
    userPersonaId: string;
};

export type UserStoryProgressGetCurrentNodeResponse = (CurrentNodePublic);

export type UserStoryProgressMakeStoryChoiceData = {
    choiceId: string;
    storyId: string;
    userPersonaId: string;
};

export type UserStoryProgressMakeStoryChoiceResponse = (UserStoryProgressPublic);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);