#!/usr/bin/env python3
"""
Seed Script: The Enchanted Library

Creates the same demo story as seed_demo_story_runtime.py but uses
the HTTP API instead of direct DB access. UUIDs are generated by the
server and returned in a structured dict.

Creates:
- Story: "The Enchanted Library" (5 nodes, branching narrative)
- State variable: has_key (boolean)
- Node choices with state management (sets_state / requires_state)
- 2 Agent configs: Narrator + Guide
- Room associated with the story
- Agent participants in the room
- Persona + UserPersona
- Room runtime (initializes RoomStoryProgress + UserStoryProgress)

Usage:
    python seed_enchanted_library.py
    python seed_enchanted_library.py --verbose
    python seed_enchanted_library.py --json   # Output IDs as JSON only
"""

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path

import requests

sys.path.append(str(Path(__file__).parent))
from auth_helper import AuthenticationError, get_authenticated_session

BASE_URL = "http://localhost:8000/api/v1"


def log(message: str, verbose: bool = True):
    if verbose:
        timestamp = datetime.now().strftime("%H:%M:%S")
        print(f"[{timestamp}] {message}")


def seed_enchanted_library(
    session: requests.Session, verbose: bool = True
) -> dict:
    """
    Create the Enchanted Library demo via API calls.

    Returns a dict of all generated entity IDs.
    """
    ids = {}

    # ─── 1. Create Story ────────────────────────────────────────────────
    log("Creating story: The Enchanted Library...", verbose)
    resp = session.post(f"{BASE_URL}/stories", json={
        "title": "The Enchanted Library",
        "description": "A short branching narrative with 5 nodes exploring a magical library.",
    })
    resp.raise_for_status()
    story = resp.json()
    ids["story_id"] = story["id"]
    ids["story_version"] = story["current_version"]
    log(f"  ✅ Story created: {story['id'][:8]}... (v{story['current_version']})", verbose)

    story_id = story["id"]
    version = story["current_version"]

    # ─── 2. Create Story Nodes ──────────────────────────────────────────
    nodes_data = [
        {
            "title": "The Library Entrance",
            "content": (
                "You stand before an ancient library. The heavy oak doors creak open, "
                "revealing dusty shelves stretching into darkness. A faint glow emanates "
                "from somewhere deep within."
            ),
            "is_start_node": True,
            "is_end_node": False,
        },
        {
            "title": "The Reading Room",
            "content": (
                "Rows of leather-bound books line the walls. A large tome sits open on a "
                "central pedestal, its pages glowing with soft golden light. A brass key "
                "hangs from a hook near the window."
            ),
            "is_start_node": False,
            "is_end_node": False,
        },
        {
            "title": "The Restricted Section",
            "content": (
                "Behind a velvet rope, towering shelves hold books bound in strange materials. "
                "The air hums with latent energy. A spectral librarian materializes, watching "
                "you carefully."
            ),
            "is_start_node": False,
            "is_end_node": False,
        },
        {
            "title": "The Secret Chamber",
            "content": (
                "The brass key turns smoothly in the hidden lock. The wall slides open to "
                "reveal a small chamber filled with floating orbs of light. Each orb contains "
                "a swirling memory."
            ),
            "is_start_node": False,
            "is_end_node": False,
        },
        {
            "title": "The Library's Heart",
            "content": (
                "You've discovered the library's deepest secret -- a living book that writes "
                "itself, recording every visitor's story. Your journey is now part of its "
                "eternal pages."
            ),
            "is_start_node": False,
            "is_end_node": True,
        },
    ]

    log("Creating 5 story nodes...", verbose)
    node_ids = []
    for node_data in nodes_data:
        node_data["story_id"] = story_id
        node_data["story_version"] = version
        resp = session.post(f"{BASE_URL}/storynodes", json=node_data)
        resp.raise_for_status()
        node = resp.json()
        node_ids.append(node["id"])
        log(f"  ✅ Node: \"{node['title']}\" ({node['id'][:8]}...)", verbose)

    ids["node_ids"] = node_ids

    # ─── 3. Create State Variable (before publishing!) ──────────────────
    log("Creating state variable: has_key...", verbose)
    resp = session.post(
        f"{BASE_URL}/stories/{story_id}/versions/{version}/state-schema",
        json={
            "key": "has_key",
            "value_type": "boolean",
            "default_value": False,
            "description": "Whether the player has picked up the brass key",
        },
    )
    resp.raise_for_status()
    state_var = resp.json()
    ids["state_variable_id"] = state_var["id"]
    log(f"  ✅ State var: has_key ({state_var['id'][:8]}...)", verbose)

    # ─── 4. Create Node Choices ─────────────────────────────────────────
    # Node indices: 0=Entrance, 1=Reading Room, 2=Restricted, 3=Secret Chamber, 4=Heart
    choices_data = [
        # From Node 0 (Entrance)
        {
            "from_node_id": node_ids[0],
            "to_node_id": node_ids[1],
            "text": "Enter the Reading Room",
            "order": 0,
        },
        {
            "from_node_id": node_ids[0],
            "to_node_id": node_ids[2],
            "text": "Go directly to the Restricted Section",
            "order": 1,
        },
        # From Node 1 (Reading Room)
        {
            "from_node_id": node_ids[1],
            "to_node_id": node_ids[2],
            "text": "Take the brass key and proceed",
            "order": 0,
            "sets_state": {"has_key": True},
        },
        {
            "from_node_id": node_ids[1],
            "to_node_id": node_ids[2],
            "text": "Leave the key and proceed",
            "order": 1,
        },
        # From Node 2 (Restricted Section)
        {
            "from_node_id": node_ids[2],
            "to_node_id": node_ids[3],
            "text": "Try the hidden door",
            "order": 0,
            "requires_state": {"has_key": True},
        },
        {
            "from_node_id": node_ids[2],
            "to_node_id": node_ids[4],
            "text": "Speak with the librarian",
            "order": 1,
        },
        # From Node 3 (Secret Chamber)
        {
            "from_node_id": node_ids[3],
            "to_node_id": node_ids[4],
            "text": "Touch an orb",
            "order": 0,
        },
    ]

    log("Creating 7 node choices...", verbose)
    choice_ids = []
    for choice_data in choices_data:
        resp = session.post(f"{BASE_URL}/node-choices", json=choice_data)
        resp.raise_for_status()
        choice = resp.json()
        choice_ids.append(choice["id"])
        log(f"  ✅ Choice: \"{choice_data['text']}\" ({choice['id'][:8]}...)", verbose)

    ids["choice_ids"] = choice_ids

    # ─── 5. Publish Story ───────────────────────────────────────────────
    log("Publishing story...", verbose)
    resp = session.put(f"{BASE_URL}/stories/{story_id}/publish")
    resp.raise_for_status()
    published = resp.json()
    ids["published_version"] = published["published_version"]
    log(f"  ✅ Published: v{published['published_version']}", verbose)

    # ─── 6. Create Agent Configs ────────────────────────────────────────
    agents_data = [
        {
            "slug": "demo-narrator",
            "name": "Narrator",
            "description": "Atmospheric storytelling agent for interactive fiction",
            "model_name": "openai:gpt-4o-mini",
            "system_prompt": (
                "You are the Narrator, an atmospheric storytelling agent in an interactive "
                "fiction experience. You react to the player's current position in the story, "
                "describe the atmosphere, and hint at consequences of their choices. Keep "
                "responses to 2-3 sentences. Reference the current node content and available "
                "choices naturally. If the player is at an end node, provide a satisfying "
                "conclusion."
            ),
            "participation_mode": "always",
            "scope": "system",
            "is_enabled": True,
        },
        {
            "slug": "demo-guide",
            "name": "Guide",
            "description": "Helpful companion agent for interactive fiction",
            "model_name": "openai:gpt-4o-mini",
            "system_prompt": (
                "You are the Guide, a helpful companion in an interactive fiction experience. "
                "You reference the player's story state (items collected, choices made) and "
                "suggest which choices might align with their journey so far. Keep responses "
                "to 2-3 sentences. If the player has the brass key, hint that it might be "
                "useful. Track the path they've taken via the node chain."
            ),
            "participation_mode": "always",
            "scope": "system",
            "is_enabled": True,
        },
    ]

    log("Creating agent configs...", verbose)
    agent_ids = []
    agent_slugs = []
    for agent_data in agents_data:
        resp = session.post(f"{BASE_URL}/agents", json=agent_data)
        resp.raise_for_status()
        agent = resp.json()
        agent_ids.append(agent["id"])
        agent_slugs.append(agent["slug"])
        log(f"  ✅ Agent: \"{agent['name']}\" slug={agent['slug']} ({agent['id'][:8]}...)", verbose)

    ids["agent_ids"] = agent_ids
    ids["agent_slugs"] = agent_slugs

    # ─── 7. Create Room ─────────────────────────────────────────────────
    log("Creating room...", verbose)
    resp = session.post(f"{BASE_URL}/rooms", json={
        "title": "Story Runtime Demo Room",
        "story_id": story_id,
    })
    resp.raise_for_status()
    room = resp.json()
    room_id = room["room_id"]
    ids["room_id"] = room_id
    log(f"  ✅ Room: \"{room['title']}\" ({room_id[:8]}...)", verbose)

    # ─── 8. Add Agent Participants ──────────────────────────────────────
    log("Adding agents to room...", verbose)
    for slug in agent_slugs:
        resp = session.post(f"{BASE_URL}/rooms/{room_id}/participants", json={
            "participant_id": slug,
            "participant_type": "agent",
            "role": "member",
        })
        resp.raise_for_status()
        log(f"  ✅ Participant: {slug}", verbose)

    # ─── 9. Create Persona + UserPersona ────────────────────────────────
    log("Creating persona...", verbose)
    resp = session.post(f"{BASE_URL}/personas", json={
        "name": "Demo Explorer",
        "description": "A curious explorer of enchanted places",
    })
    resp.raise_for_status()
    persona = resp.json()
    ids["persona_id"] = persona["id"]
    log(f"  ✅ Persona: \"{persona['name']}\" ({persona['id'][:8]}...)", verbose)

    log("Creating user-persona...", verbose)
    resp = session.post(f"{BASE_URL}/user-personas", json={
        "persona_id": persona["id"],
    })
    resp.raise_for_status()
    user_persona = resp.json()
    ids["user_persona_id"] = user_persona["id"]
    log(f"  ✅ UserPersona: {user_persona['id'][:8]}...", verbose)

    # ─── 10. Initialize Room Runtime ────────────────────────────────────
    log("Initializing room runtime...", verbose)
    resp = session.put(f"{BASE_URL}/rooms/{room_id}/runtime", json={
        "user_persona_id": user_persona["id"],
        "story_version": ids["published_version"],
    })
    resp.raise_for_status()
    runtime = resp.json()
    ids["room_runtime"] = {
        "active_progress_id": runtime.get("active_progress_id"),
        "revision": runtime.get("revision"),
        "current_node_id": runtime.get("current_node_id"),
    }
    log(f"  ✅ Runtime initialized (progress: {runtime.get('active_progress_id', '?')[:8]}...)", verbose)

    return ids


def main():
    parser = argparse.ArgumentParser(description="Seed: The Enchanted Library")
    parser.add_argument("--verbose", "-v", action="store_true", help="Verbose output")
    parser.add_argument("--json", action="store_true", help="Output only JSON (for piping)")
    args = parser.parse_args()

    verbose = not args.json  # Suppress logs if --json
    if args.verbose:
        verbose = True

    try:
        session = get_authenticated_session()

        if verbose:
            print("=" * 60)
            print("  SEED: The Enchanted Library")
            print("  Creating demo story via API (server-generated UUIDs)")
            print("=" * 60)
            print()

        ids = seed_enchanted_library(session, verbose=verbose)

        if verbose:
            print()
            print("=" * 60)
            print("  SEED COMPLETE")
            print("=" * 60)
            print()
            print("Generated IDs:")
            print(json.dumps(ids, indent=2))
            print()
            print(f"  Story:       {ids['story_id']}")
            print(f"  Room:        {ids['room_id']}")
            print(f"  Persona:     {ids['user_persona_id']}")
            print(f"  Agents:      {', '.join(ids['agent_slugs'])}")
            print()
        else:
            # --json mode: just dump the IDs
            print(json.dumps(ids, indent=2))

        return ids

    except AuthenticationError as e:
        print(f"❌ Authentication failed: {e}", file=sys.stderr)
        sys.exit(1)
    except requests.exceptions.HTTPError as e:
        print(f"❌ API error: {e.response.status_code} - {e.response.text}", file=sys.stderr)
        sys.exit(1)
    except requests.exceptions.ConnectionError:
        print("❌ Cannot connect to backend. Is it running?", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"❌ Unexpected error: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
