/**
 * Agent Service - Data Integration Layer
 *
 * Purpose: Provide a clean, type-safe abstraction over the OpenAPI client
 * for agent-related operations. Transforms backend response models to
 * frontend ViewModels optimized for UI consumption.
 *
 * Architecture:
 * - Wraps OpenAPI client methods for UserAgentConfig CRUD
 * - Transforms backend UserAgentConfigPublic to AgentViewModel
 * - Normalizes nullable fields and provides UI-friendly defaults
 * - Centralizes API endpoint usage
 * - Provides type-safe interfaces with strict union types
 *
 * Note: This service manages UserAgentConfig entities (configuration templates),
 * NOT runtime Agent processes. AgentViewModel represents the config used to
 * instantiate Agents, not the Agents themselves.
 *
 * Dependencies:
 * - OpenAPI auto-generated client (@/client)
 * - llmCatalogService (for LLMProviderType type)
 */

// REMEMBER: a UserAgentConfig creates a construct that is used to generate an Agent.
// An Agent is a process that uses that config, and constructs the message it passes to the API.
// The way that message is constructed is dependent on the ProviderType - will the agent generated by this config need to talk 'openai' or will it need to talk 'anthropic' or something else?
// the useraccessprovider is how the user specifies the channel that the conversation will happen over -
// for the conversation to happen between our system and the main openai endpoint
// requires that the user have a useraccessprovider set with a) the openai endpoint and b) their sdk key to access that openai endpoint.
// for a UserAgentConfig to be used by the Agent generation process, it needs an association with
// a) a valid useraccessprovider,
// b) a model that is supported by that specific useraccessprovider -> for their account with that access provider, and c) an association with a model that is valid for
// c) a provider type that is valid for that useraccessprovider and that model.
//  if any of these are not aligned, then the Agent generated will not be successful in the work it attempts.
//  if the UserAgentConfig does not have a valid useraccessprovider, then there is no valid API for the Agent to connect to.
//  if the UserAgentConfig does not have a valid providertype:useraccessprovider, then the Agent generated from that UserAgentConfig will send messages to the API that the API can't process.
//  if the UserAgentConfig does not have a valid providertype:model association, then the Agent generated from that UserAgentConfig will send messages to the API that the model serving that endpoint can't process.
//  if the UserAgentConfig does not have a valid useraccessprovider:model association, then the Agent generated from that UserAgentConfig will send messages that are rejected by the API because that endpoint doesn't serve that model.

// ARCHITECTURE SUMMARY - Three-Way Binding:
//
// UserAgentConfig stores THREE critical associations that must align:
//   1. user_access_provider (UUID) → Which UserAccessProvider entity to use
//   2. provider_type (string)      → Which API specification format (openai, anthropic, etc.)
//   3. model_name (string)         → Which model to request
//
// When an Agent is instantiated from a UserAgentConfig:
//   - user_access_provider provides: base_url, api_key (WHERE and WITH WHAT CREDENTIALS)
//   - provider_type provides: message format, API schema (HOW to structure requests)
//   - model_name provides: which model to invoke (WHAT to talk to)
//
// All three must be mutually compatible or the Agent will fail at runtime.
// Backend performs authoritative validation, but client-side validation improves UX.
// See userAccessProviderService for validation utilities.

import {
  type UserAgentConfigCreate,
  type UserAgentConfigPublic,
  type UserAgentConfigsPublic,
  type UserAgentConfigUpdate,
  AgentsService,
  OpenAPI,
} from "@/client"
import type { ApiRequestOptions } from "@/client/core/ApiRequestOptions"
import { request as __request } from "@/client/core/request"
// import type { LLMProviderType } from "@/services/llmCatalogService"

// ============================================================================
// Type Definitions - ViewModels
// ============================================================================

/**
 * Agent scope - determines visibility and ownership
 */
export type AgentScope = "system" | "personal"

/**
 * Agent participation mode - how the agent engages in rooms by default
 * - "always": Agent responds to all messages
 * - "on_mention": Agent responds when mentioned
 * - "manual": Agent only responds when explicitly invoked
 */
export type ParticipationMode = "always" | "on_mention" | "manual"

/**
 * AgentViewModel
 *
 * UI-optimized view of UserAgentConfig. This is NOT the Agent itself -
 * it's the configuration template used to instantiate runtime Agents.
 *
 * Critical Associations:
 * - user_access_provider: UUID reference to UserAccessProvider (the access channel)
 * - provider_type: the API message format
 * - model_name: string (the model identifier)
 *
 * ⚠️  VALIDATION: When using this config to create an Agent, validate:
 *     1. UserAccessProvider exists and is enabled
 *     2. ProviderType matches what UserAccessProvider supports
 *     3. Model is available at UserAccessProvider and supports ProviderType
 *
 * See userAccessProviderService for validation utilities (TODO: implement)
 *
 * Transformations from backend UserAgentConfigPublic:
 * - Provides strict union types for scope and participation_mode
 * - Normalizes nullable fields
 * - Parses ISO timestamp strings to Date objects
 */
export interface AgentViewModel {
  id: string
  name: string
  slug: string
  description: string | null

  // Model Configuration
  model_id: string | null              // Model UUID reference (for catalog models)
  model_name: string                   // Model identifier string (e.g., "gpt-4o-mini")
  provider_type: string       // API specification type (e.g., "openai", "anthropic")
  user_access_provider: string | null  // UUID reference to UserAccessProvider

  // Prompts and Instructions
  system_prompt: string | null         // Base system prompt from agent config
  custom_system_prompt: string | null  // User override for system prompt
  instructions: string | null          // Large text field for detailed instructions

  // Configuration
  tool_config: Record<string, unknown> | null
  deps_config: Record<string, unknown> | null
  agent_metadata: Record<string, unknown> | null

  // Behavior Settings
  is_enabled: boolean
  is_clonable: boolean                 // Whether this config can be cloned by others
  is_visible: boolean                  // Visibility setting
  scope: AgentScope                    // "system" | "personal"
  participation_mode: ParticipationMode // "always" | "on_mention" | "manual"
  is_coordinator: boolean              // Whether agent can coordinate other agents
  max_tool_iterations: number | null   // Maximum tool call iterations
  capabilities: string[]               // Agent capability tags

  // Metadata
  owner_id: string | null
  created_at: Date
  updated_at: Date | null
  version: number
}

/**
 * Agent creation input
 *
 * ⚠️  THREE-WAY BINDING: When creating an agent, ensure:
 *     - user_access_provider references a valid, enabled UserAccessProvider
 *     - ?? (not sure on this one) provider_type matches what that UserAccessProvider supports
 *     - ?? (not sure on this one) model_name is available at that UserAccessProvider
 *
 * Validation should happen:
 *     - Client-side: Before calling createAgent (via userAccessProviderService utilities)
 *     - Server-side: Backend validates these relationships (will return 400 if invalid)
 */
export interface CreateAgentInput {
  name: string
  slug: string
  description?: string | null
  model_name?: string
  provider_type?: string
  user_access_provider?: string | null  // UUID of UserAccessProvider entity
  system_prompt?: string | null
  participation_mode?: ParticipationMode
  scope?: AgentScope
  is_enabled?: boolean
}

/**
 * Agent update input
 */
export interface UpdateAgentInput {
  name?: string | null
  description?: string | null
  model_name?: string | null
  provider_type?: string | null
  user_access_provider?: string | null
  system_prompt?: string | null
  participation_mode?: ParticipationMode | null
  is_enabled?: boolean | null
}

/**
 * Paginated agents response
 */
export interface PaginatedAgents {
  agents: AgentViewModel[]
  total_count: number
}

interface GeneratedSlugResponse {
  slug: string
}

// ============================================================================
// Transformation Functions
// ============================================================================

/**
 * Transform backend UserAgentConfigPublic to AgentViewModel
 *
 * ⚠️  INPUT TYPE: Must be UserAgentConfigPublic (API response), NOT UserAgentConfigUpdate
 *
 * Transformations:
 * - Parses created_at, updated_at ISO strings to Date objects
 * - Provides defaults for nullable fields
 * - Casts scope and participation_mode to strict union types
 *
 * @param agent - Backend UserAgentConfigPublic (from API response)
 * @returns Transformed AgentViewModel optimized for UI
 */
function transformAgent(agent: UserAgentConfigPublic): AgentViewModel {
  return {
    id: agent.id,
    name: agent.name ?? "",
    slug: agent.slug ?? "",
    description: agent.description ?? null,

    // Model Configuration
    model_id: agent.model_id ?? null,
    model_name: agent.model_name ?? "gpt-4o-mini",
    provider_type: agent.provider_type ?? "openai",
    user_access_provider: agent.user_access_provider ?? null,

    // Prompts and Instructions
    system_prompt: agent.system_prompt ?? null,
    custom_system_prompt: agent.custom_system_prompt ?? null,
    instructions: agent.instructions ?? null,

    // Configuration
    tool_config: agent.tool_config ?? null,
    deps_config: agent.deps_config ?? null,
    agent_metadata: agent.agent_metadata ?? null,

    // Behavior Settings
    is_enabled: agent.is_enabled ?? true,
    is_clonable: agent.is_clonable ?? true,
    is_visible: agent.is_visible ?? true,
    scope: (agent.scope as AgentScope) ?? "personal",
    participation_mode:
      (agent.participation_mode as ParticipationMode) ?? "on_mention",
    is_coordinator: agent.is_coordinator ?? false,
    max_tool_iterations: agent.max_tool_iterations ?? null,
    capabilities: agent.capabilities ?? [],

    // Metadata
    owner_id: agent.owner_id ?? null,
    created_at: new Date(agent.created_at),
    updated_at: agent.updated_at ? new Date(agent.updated_at) : null,
    version: agent.version,
  }
}

// ============================================================================
// Agent Service - Public API
// ============================================================================

/**
 * Agent Service
 *
 * Provides all agent-related data operations with clean, type-safe interfaces.
 * All methods return ViewModels optimized for UI consumption.
 *
 * Error Handling:
 * - All methods can throw ApiError from the OpenAPI client
 * - Callers should handle errors appropriately (see handleError utility)
 *
 * Authentication:
 * - All methods require valid JWT token (handled by OpenAPI client)
 * - 401 errors indicate authentication failure
 * - 403 errors indicate authorization failure
 */
export const AgentService = {
  // ==========================================================================
  // Agent Operations
  // ==========================================================================

  /**
   * List all agents (UserAgentConfigs) accessible to the current user
   *
   * Returns both personal agents owned by the user and system agents.
   *
   * @param options - Pagination options
   * @returns Paginated agents response
   * @throws ApiError on network or server errors
   */
  async listAgents(options?: {
    skip?: number
    limit?: number
  }): Promise<PaginatedAgents> {
    const response: UserAgentConfigsPublic = await AgentsService.listAgents({
      skip: options?.skip ?? 0,
      limit: options?.limit ?? 100,
    })

    return {
      agents: response.data.map(transformAgent),
      total_count: response.count,
    }
  },

  /**
   * List available agents for room participation
   *
   * Returns agents that can be added to rooms (enabled agents only).
   *
   * @param options - Pagination options
   * @returns Paginated agents response
   * @throws ApiError on network or server errors
   */
  async listAvailableAgents(options?: {
    skip?: number
    limit?: number
  }): Promise<PaginatedAgents> {
    const response: UserAgentConfigsPublic =
      await AgentsService.listAvailableAgents({
        skip: options?.skip ?? 0,
        limit: options?.limit ?? 100,
      })

    return {
      agents: response.data.map(transformAgent),
      total_count: response.count,
    }
  },

  /**
   * Get a single agent by ID
   *
   * @param agentId - Agent UUID
   * @returns AgentViewModel
   * @throws ApiError - 404 if agent not found
   */
  async getAgent(agentId: string): Promise<AgentViewModel> {
    const agent: UserAgentConfigPublic = await AgentsService.getAgent({ agentId })
    return transformAgent(agent)
  },

  /**
   * Get a single agent by slug
   *
   * @param slug - Agent slug
   * @returns AgentViewModel
   * @throws ApiError - 404 if agent not found
   */
  async getAgentBySlug(slug: string): Promise<AgentViewModel> {
    const options: ApiRequestOptions<UserAgentConfigPublic> = {
      method: "GET",
      url: `/api/v1/agents/slug/${slug}`,
    }
    const agent = await __request(OpenAPI, options)
    return transformAgent(agent)
  },

  /**
   * Generate a unique agent slug
   *
   * @returns Generated slug
   * @throws ApiError on network or server errors
   */
  async generateSlug(): Promise<string> {
    const options: ApiRequestOptions<GeneratedSlugResponse> = {
      method: "GET",
      url: "/api/v1/agents/generate-slug",
    }
    const response = await __request(OpenAPI, options)
    return response.slug
  },

  /**
   * Create a new personal agent
   *
   * System agents can only be created by superusers via backend.
   * Personal agents are owned by the creating user.
   * TODO: Cloning of other user's agents and system agents.
   *
   * ⚠️  VALIDATION REQUIRED BEFORE CALLING:
   *     1. Validate user_access_provider exists and is enabled
   *        → Use: userAccessProviderService.getProvider(id)
   *     2. Validate provider_type is supported by that UserAccessProvider
   *        → Use: userAccessProviderService.validateProviderType(providerId, type)
   *     3. Validate model is available for that UserAccessProvider + ProviderType
   *        → Use: llmCatalogService or userAccessProviderService.getAvailableModels(...)
   *
   *     Backend will return 400 Bad Request if validation fails, but client-side
   *     validation provides better UX.
   *
   * @param data - Agent creation parameters
   * @returns Newly created AgentViewModel
   * @throws ApiError - 400 if validation fails, other server errors
   */
  async createAgent(data: CreateAgentInput): Promise<AgentViewModel> {
    // Build UserAgentConfigCreate from input
    // Note: Backend validation will ensure user_access_provider + provider_type + model_name
    //       form a valid combination. Client-side validation recommended for better UX.
    const providerType = data.provider_type ?? "openai"

    const createData: UserAgentConfigCreate = {
      name: data.name,
      slug: data.slug,
      description: data.description,
      model_name: data.model_name,
      provider_type: providerType, // LLMProviderType - the API message format spec (e.g., "openai", "anthropic")
      user_access_provider: data.user_access_provider,
      system_prompt: data.system_prompt,
      participation_mode: data.participation_mode,
      scope: data.scope ?? "personal",
      is_enabled: data.is_enabled ?? true,
    }

    const agent: UserAgentConfigPublic = await AgentsService.createAgent({
      requestBody: createData,
    })

    return transformAgent(agent)
  },

  /**
   * Update an existing agent
   *
   * Only the agent owner or superusers can update agents.
   * System agents can only be updated by superusers.
   *
   * @param agentId - Agent UUID
   * @param data - Fields to update
   * @returns Updated AgentViewModel
   * @throws ApiError - 403 if not authorized, 404 if agent not found
   */
  async updateAgent(
    agentId: string,
    data: UpdateAgentInput,
  ): Promise<AgentViewModel> {
    const updateData: UserAgentConfigUpdate = {
      name: data.name,
      description: data.description,
      model_name: data.model_name,
      provider_type: data.provider_type,
      user_access_provider: data.user_access_provider,
      system_prompt: data.system_prompt,
      participation_mode: data.participation_mode,
      is_enabled: data.is_enabled,
    }

    const agent: UserAgentConfigPublic = await AgentsService.updateAgent({
      agentId,
      requestBody: updateData,
    })

    return transformAgent(agent)
  },

  /**
   * Delete an agent
   *
   * Only the agent owner or superusers can delete agents.
   * System agents can only be deleted by superusers.
   *
   * @param agentId - Agent UUID
   * @returns Promise that resolves when deletion is complete
   * @throws ApiError - 403 if not authorized, 404 if agent not found
   */
  async deleteAgent(agentId: string): Promise<void> {
    await AgentsService.deleteAgent({ agentId })
  },

  // ==========================================================================
  // Filtering Utilities
  // ==========================================================================

  /**
   * Filter agents by scope
   *
   * @param agents - Array of agents to filter
   * @param scope - Scope to filter by
   * @returns Filtered agents
   */
  filterByScope(agents: AgentViewModel[], scope: AgentScope): AgentViewModel[] {
    return agents.filter((agent) => agent.scope === scope)
  },

  /**
   * Filter agents by enabled status
   *
   * @param agents - Array of agents to filter
   * @param enabled - Enabled status to filter by
   * @returns Filtered agents
   */
  filterByEnabled(
    agents: AgentViewModel[],
    enabled: boolean,
  ): AgentViewModel[] {
    return agents.filter((agent) => agent.is_enabled === enabled)
  },

  /**
   * Separate agents into personal and system groups
   *
   * @param agents - Array of agents to group
   * @returns Object with personal and system agent arrays
   */
  groupByScope(agents: AgentViewModel[]): {
    personal: AgentViewModel[]
    system: AgentViewModel[]
  } {
    return {
      personal: agents.filter((a) => a.scope === "personal"),
      system: agents.filter((a) => a.scope === "system"),
    }
  },
}

// ============================================================================
// Utility Functions
// ============================================================================

/**
 * Check if an agent can be edited by the current user
 *
 * Personal agents can be edited by their owner.
 * System agents can only be edited by superusers.
 *
 * @param agent - Agent to check
 * @param currentUserId - Current user's ID
 * @param isSuperuser - Whether current user is a superuser
 * @returns Whether the agent can be edited
 */
export function canEditAgent(
  agent: AgentViewModel,
  currentUserId: string | null,
  isSuperuser: boolean,
): boolean {
  if (isSuperuser) return true
  if (agent.scope === "system") return false
  return agent.owner_id === currentUserId
}

/**
 * Check if an agent can be deleted by the current user
 *
 * Same rules as editing.
 *
 * @param agent - Agent to check
 * @param currentUserId - Current user's ID
 * @param isSuperuser - Whether current user is a superuser
 * @returns Whether the agent can be deleted
 */
export function canDeleteAgent(
  agent: AgentViewModel,
  currentUserId: string | null,
  isSuperuser: boolean,
): boolean {
  return canEditAgent(agent, currentUserId, isSuperuser)
}
