# coding: utf-8

"""
    slug-loves-beans

    this description is required

    The version of the OpenAPI document: 13.0.4+gitea-1.22.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.repository import Repository
from openapi_client.models.user import User
from typing import Optional, Set
from typing_extensions import Self

class ActionRun(BaseModel):
    """
    ActionRun represents an action run
    """ # noqa: E501
    schedule_id: Optional[StrictInt] = Field(default=None, description="the cron id for the schedule trigger", alias="ScheduleID")
    approved_by: Optional[StrictInt] = Field(default=None, description="who approved this action run")
    commit_sha: Optional[StrictStr] = Field(default=None, description="the commit sha the action run ran on")
    created: Optional[datetime] = Field(default=None, description="when the action run was created")
    duration: Optional[StrictInt] = Field(default=None, description="A Duration represents the elapsed time between two instants as an int64 nanosecond count. The representation limits the largest representable duration to approximately 290 years.")
    event: Optional[StrictStr] = Field(default=None, description="the webhook event that causes the workflow to run")
    event_payload: Optional[StrictStr] = Field(default=None, description="the payload of the webhook event that causes the workflow to run")
    html_url: Optional[StrictStr] = Field(default=None, description="the url of this action run")
    id: Optional[StrictInt] = Field(default=None, description="the action run id")
    index_in_repo: Optional[StrictInt] = Field(default=None, description="a unique number for each run of a repository")
    is_fork_pull_request: Optional[StrictBool] = Field(default=None, description="If this is triggered by a PR from a forked repository or an untrusted user, we need to check if it is approved and limit permissions when running the workflow.")
    is_ref_deleted: Optional[StrictBool] = Field(default=None, description="has the commit/tag/… the action run ran on been deleted")
    need_approval: Optional[StrictBool] = Field(default=None, description="may need approval if it's a fork pull request")
    prettyref: Optional[StrictStr] = Field(default=None, description="the commit/tag/… the action run ran on")
    repository: Optional[Repository] = None
    started: Optional[datetime] = Field(default=None, description="when the action run was started")
    status: Optional[StrictStr] = Field(default=None, description="the current status of this run")
    stopped: Optional[datetime] = Field(default=None, description="when the action run was stopped")
    title: Optional[StrictStr] = Field(default=None, description="the action run's title")
    trigger_event: Optional[StrictStr] = Field(default=None, description="the trigger event defined in the `on` configuration of the triggered workflow")
    trigger_user: Optional[User] = None
    updated: Optional[datetime] = Field(default=None, description="when the action run was last updated")
    workflow_id: Optional[StrictStr] = Field(default=None, description="the name of workflow file")
    __properties: ClassVar[List[str]] = ["ScheduleID", "approved_by", "commit_sha", "created", "duration", "event", "event_payload", "html_url", "id", "index_in_repo", "is_fork_pull_request", "is_ref_deleted", "need_approval", "prettyref", "repository", "started", "status", "stopped", "title", "trigger_event", "trigger_user", "updated", "workflow_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ActionRun from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of repository
        if self.repository:
            _dict['repository'] = self.repository.to_dict()
        # override the default output from pydantic by calling `to_dict()` of trigger_user
        if self.trigger_user:
            _dict['trigger_user'] = self.trigger_user.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ActionRun from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ScheduleID": obj.get("ScheduleID"),
            "approved_by": obj.get("approved_by"),
            "commit_sha": obj.get("commit_sha"),
            "created": obj.get("created"),
            "duration": obj.get("duration"),
            "event": obj.get("event"),
            "event_payload": obj.get("event_payload"),
            "html_url": obj.get("html_url"),
            "id": obj.get("id"),
            "index_in_repo": obj.get("index_in_repo"),
            "is_fork_pull_request": obj.get("is_fork_pull_request"),
            "is_ref_deleted": obj.get("is_ref_deleted"),
            "need_approval": obj.get("need_approval"),
            "prettyref": obj.get("prettyref"),
            "repository": Repository.from_dict(obj["repository"]) if obj.get("repository") is not None else None,
            "started": obj.get("started"),
            "status": obj.get("status"),
            "stopped": obj.get("stopped"),
            "title": obj.get("title"),
            "trigger_event": obj.get("trigger_event"),
            "trigger_user": User.from_dict(obj["trigger_user"]) if obj.get("trigger_user") is not None else None,
            "updated": obj.get("updated"),
            "workflow_id": obj.get("workflow_id")
        })
        return _obj


