"""Add quality model

Revision ID: 068d9af88ca2
Revises: e6e1a6683462
Create Date: 2025-04-19 01:59:36.549805

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '068d9af88ca2'
down_revision = 'e6e1a6683462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('persona', 'persona_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('persona', 'archetype_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('persona', 'archetype_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('persona', 'persona_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
