"""add indexes to usernodechoice and userstoryprogress

Revision ID: 135dd2454c3d
Revises: df9f66d000a5
Create Date: 2026-01-02 00:14:56.388261

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '135dd2454c3d'
down_revision = 'df9f66d000a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add indexes
    op.create_index('idx_usernodechoice_parent', 'usernodechoice', ['parent_choice_id'])
    op.create_index('idx_userstoryprogress_head', 'userstoryprogress', ['head_choice_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add before drop_column operations:
    op.drop_index('idx_userstoryprogress_head', table_name='userstoryprogress')
    op.drop_index('idx_usernodechoice_parent', table_name='usernodechoice')
    # ### end Alembic commands ###