"""persona updates to the data model

Revision ID: 16c9584a8f10
Revises: 1f81c90e8703
Create Date: 2025-05-03 16:07:14.983444

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '16c9584a8f10'
down_revision = '1f81c90e8703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persona', sa.Column('long_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('persona', sa.Column('general_domain', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('persona', sa.Column('specific_domain', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('persona', sa.Column('general_domain_high', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('persona', sa.Column('specific_domain_high', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persona', 'specific_domain_high')
    op.drop_column('persona', 'general_domain_high')
    op.drop_column('persona', 'specific_domain')
    op.drop_column('persona', 'general_domain')
    op.drop_column('persona', 'long_description')
