"""UserPersona work - extensions for user management and audience resolution

Revision ID: 217e959c137c
Revises: 6d6f9b2c5d2a
Create Date: 2026-03-08 10:35:06.335929

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '217e959c137c'
down_revision = '6d6f9b2c5d2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userpersonapresentation',
    sa.Column('audience_scope', sa.Enum('PUBLIC', 'TRUSTED', 'COLLABORATORS', 'CUSTOM', name='audiencescope'), nullable=False),
    sa.Column('audience_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('audience_label', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('headline', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('framing_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('visible_work_ids_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('relation_call_to_action', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('publication_state', sa.Enum('DRAFT', 'PUBLISHED', name='presentationpublicationstate'), nullable=False),
    sa.Column('presentation_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_persona_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_persona_id'], ['userpersona.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_persona_id', 'audience_scope', 'audience_key', name='uq_userpersona_presentation_audience')
    )

    # Create enum types before using them in alter_column
    op.execute("CREATE TYPE accessgrantsubjecttype AS ENUM ('user', 'group')")
    op.execute("CREATE TYPE accessgrantrole AS ENUM ('viewer', 'editor', 'manager')")

    # Use USING clause to cast existing VARCHAR values to enum
    op.execute("ALTER TABLE access_grants ALTER COLUMN subject_type TYPE accessgrantsubjecttype USING subject_type::accessgrantsubjecttype")
    op.execute("ALTER TABLE access_grants ALTER COLUMN role TYPE accessgrantrole USING role::accessgrantrole")

    op.drop_index(op.f('ix_access_grants_resource'), table_name='access_grants')
    op.drop_index(op.f('ix_access_grants_subject'), table_name='access_grants')
    op.create_index(op.f('ix_access_grants_resource_id'), 'access_grants', ['resource_id'], unique=False)
    op.create_index(op.f('ix_access_grants_resource_type'), 'access_grants', ['resource_type'], unique=False)
    # Create enum type before adding column (with default for existing rows)
    op.execute("CREATE TYPE personavisibility AS ENUM ('PRIVATE', 'SYSTEM')")
    op.add_column('persona', sa.Column('visibility', sa.Enum('PRIVATE', 'SYSTEM', name='personavisibility', create_constraint=False), nullable=False, server_default='PRIVATE'))
    op.add_column('persona', sa.Column('owner_user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'persona', 'user', ['owner_user_id'], ['id'])
    op.drop_index(op.f('ix_project_resources_resource'), table_name='project_resources')
    op.create_index(op.f('ix_project_resources_resource_id'), 'project_resources', ['resource_id'], unique=False)
    op.create_index(op.f('ix_project_resources_resource_type'), 'project_resources', ['resource_type'], unique=False)
    # Create enum type and alter column with USING clause
    op.execute("CREATE TYPE usergroupmembershiprole AS ENUM ('member', 'manager')")
    op.execute("ALTER TABLE user_group_memberships ALTER COLUMN role TYPE usergroupmembershiprole USING role::usergroupmembershiprole")
    op.add_column('userpersona', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('userpersona', sa.Column('short_bio', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('userpersona', sa.Column('long_bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('userpersona', sa.Column('tags_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    # Create enum type before adding column
    op.execute("CREATE TYPE userpersonapublicationstate AS ENUM ('DRAFT', 'PUBLISHED')")
    op.add_column('userpersona', sa.Column('publication_state', sa.Enum('DRAFT', 'PUBLISHED', name='userpersonapublicationstate', create_constraint=False), nullable=False, server_default='DRAFT'))
    op.add_column('userpersona', sa.Column('is_primary', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('userpersona', sa.Column('sort_order', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('userpersona', sa.Column('presentation_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    op.create_unique_constraint('uq_userpersona_user_persona', 'userpersona', ['user_id', 'persona_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_userpersona_user_persona', 'userpersona', type_='unique')
    op.drop_column('userpersona', 'presentation_json')
    op.drop_column('userpersona', 'sort_order')
    op.drop_column('userpersona', 'is_primary')
    op.drop_column('userpersona', 'publication_state')
    op.execute("DROP TYPE userpersonapublicationstate")
    op.drop_column('userpersona', 'tags_json')
    op.drop_column('userpersona', 'long_bio')
    op.drop_column('userpersona', 'short_bio')
    op.drop_column('userpersona', 'description')
    # Convert enum back to VARCHAR and drop the type
    op.execute("ALTER TABLE user_group_memberships ALTER COLUMN role TYPE VARCHAR USING role::text")
    op.execute("DROP TYPE usergroupmembershiprole")
    op.drop_index(op.f('ix_project_resources_resource_type'), table_name='project_resources')
    op.drop_index(op.f('ix_project_resources_resource_id'), table_name='project_resources')
    op.create_index(op.f('ix_project_resources_resource'), 'project_resources', ['resource_type', 'resource_id'], unique=False)
    op.drop_constraint(None, 'persona', type_='foreignkey')
    op.drop_column('persona', 'owner_user_id')
    op.drop_column('persona', 'visibility')
    op.execute("DROP TYPE personavisibility")
    op.drop_index(op.f('ix_access_grants_resource_type'), table_name='access_grants')
    op.drop_index(op.f('ix_access_grants_resource_id'), table_name='access_grants')
    op.create_index(op.f('ix_access_grants_subject'), 'access_grants', ['subject_type', 'subject_id'], unique=False)
    op.create_index(op.f('ix_access_grants_resource'), 'access_grants', ['resource_type', 'resource_id'], unique=False)
    # Convert enums back to VARCHAR and drop the types
    op.execute("ALTER TABLE access_grants ALTER COLUMN role TYPE VARCHAR USING role::text")
    op.execute("ALTER TABLE access_grants ALTER COLUMN subject_type TYPE VARCHAR USING subject_type::text")
    op.execute("DROP TYPE accessgrantrole")
    op.execute("DROP TYPE accessgrantsubjecttype")
    op.drop_table('userpersonapresentation')
    # ### end Alembic commands ###
