"""Add capabilities field to agent_configs

Revision ID: 22f64e12f0b0
Revises: bcfd1062bbdb
Create Date: 2026-01-16 14:23:09.726738

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '22f64e12f0b0'
down_revision = 'bcfd1062bbdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_configs', sa.Column('capabilities', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_configs', 'capabilities')
    # ### end Alembic commands ###
