"""complete refactor of archetypes, traits, qualities, and personas

Revision ID: 26efbad597c5
Revises: 900d4a2b40b5
Create Date: 2025-04-22 17:18:35.845672

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '26efbad597c5'
down_revision = '900d4a2b40b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archetypepersonalink',
    sa.Column('archetype_id', sa.Uuid(), nullable=False),
    sa.Column('persona_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['archetype_id'], ['archetype.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archetypequalitylink',
    sa.Column('archetype_id', sa.Uuid(), nullable=False),
    sa.Column('quality_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['archetype_id'], ['archetype.id'], ),
    sa.ForeignKeyConstraint(['quality_id'], ['quality.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personatraitlink',
    sa.Column('persona_id', sa.Uuid(), nullable=False),
    sa.Column('traid_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['traid_id'], ['trait.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('archetype', sa.Column('archetype_description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.alter_column('archetype', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('ix_archetype_archetype_name', table_name='archetype')
    op.drop_column('archetype', 'enabled')
    op.drop_column('archetype', 'description')
    op.drop_column('archetype', 'title')
    op.add_column('archetypetraitlink', sa.Column('id', sa.Uuid(), nullable=False))
    op.drop_constraint('archetypetraitlink_archetype_id_fkey', 'archetypetraitlink', type_='foreignkey')
    op.drop_constraint('archetypetraitlink_trait_id_fkey', 'archetypetraitlink', type_='foreignkey')
    op.create_foreign_key(None, 'archetypetraitlink', 'archetype', ['archetype_id'], ['id'])
    op.create_foreign_key(None, 'archetypetraitlink', 'trait', ['trait_id'], ['id'])
    op.drop_column('archetypetraitlink', 'is_required')
    op.drop_column('archetypetraitlink', 'updated_at')
    op.drop_column('archetypetraitlink', 'is_modifiable')
    op.drop_column('archetypetraitlink', 'modifiable_at_creation_only')
    op.add_column('persona', sa.Column('persona_description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('persona', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('persona', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('persona', 'persona_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_persona_archetype_id', table_name='persona')
    op.drop_index('ix_persona_persona_name', table_name='persona')
    op.drop_constraint('persona_owner_id_fkey', 'persona', type_='foreignkey')
    op.drop_constraint('persona_archetype_id_fkey', 'persona', type_='foreignkey')
    op.drop_column('persona', 'owner_id')
    op.drop_column('persona', 'description')
    op.drop_column('persona', 'title')
    op.drop_column('persona', 'archetype_id')
    op.drop_column('persona', 'enabled')
    op.add_column('quality', sa.Column('quality_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('quality', sa.Column('quality_description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.alter_column('quality', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('quality', 'description')
    op.drop_column('quality', 'name')
    op.add_column('trait', sa.Column('trait_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('trait', sa.Column('trait_description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.alter_column('trait', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('trait', 'max_active_personas')
    op.drop_column('trait', 'description')
    op.drop_column('trait', 'archetype_only')
    op.drop_column('trait', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trait', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('trait', sa.Column('archetype_only', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('trait', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('trait', sa.Column('max_active_personas', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('trait', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('trait', 'trait_description')
    op.drop_column('trait', 'trait_name')
    op.add_column('quality', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('quality', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('quality', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('quality', 'quality_description')
    op.drop_column('quality', 'quality_name')
    op.add_column('persona', sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('persona', sa.Column('archetype_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('persona', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('persona', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('persona', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('persona_archetype_id_fkey', 'persona', 'archetype', ['archetype_id'], ['id'])
    op.create_foreign_key('persona_owner_id_fkey', 'persona', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_persona_persona_name', 'persona', ['persona_name'], unique=False)
    op.create_index('ix_persona_archetype_id', 'persona', ['archetype_id'], unique=False)
    op.alter_column('persona', 'persona_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('persona', 'updated_at')
    op.drop_column('persona', 'created_at')
    op.drop_column('persona', 'persona_description')
    op.add_column('archetypetraitlink', sa.Column('modifiable_at_creation_only', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('archetypetraitlink', sa.Column('is_modifiable', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('archetypetraitlink', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('archetypetraitlink', sa.Column('is_required', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'archetypetraitlink', type_='foreignkey')
    op.drop_constraint(None, 'archetypetraitlink', type_='foreignkey')
    op.create_foreign_key('archetypetraitlink_trait_id_fkey', 'archetypetraitlink', 'trait', ['trait_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('archetypetraitlink_archetype_id_fkey', 'archetypetraitlink', 'archetype', ['archetype_id'], ['id'], ondelete='CASCADE')
    op.drop_column('archetypetraitlink', 'id')
    op.add_column('archetype', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('archetype', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('archetype', sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index('ix_archetype_archetype_name', 'archetype', ['archetype_name'], unique=False)
    op.alter_column('archetype', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('archetype', 'archetype_description')
    op.drop_table('personatraitlink')
    op.drop_table('archetypequalitylink')
    op.drop_table('archetypepersonalink')
    # ### end Alembic commands ###
