"""llm providers and models and monstering oh my

Revision ID: 2c8ddf0e6e08
Revises: e17fab10bef8
Create Date: 2026-01-30 19:08:29.123206

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2c8ddf0e6e08'
down_revision = 'e17fab10bef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('frontier_access_provider', 'testing_api_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('llmmodel', sa.Column('multiple_provider_type_support', sa.Boolean(), nullable=False))
    op.add_column('llmmodel', sa.Column('primary_provider_type_id', sa.Uuid(), nullable=False))
    op.drop_index(op.f('ix_llmmodel_provider_id'), table_name='llmmodel')
    op.create_index(op.f('ix_llmmodel_primary_provider_type_id'), 'llmmodel', ['primary_provider_type_id'], unique=False)
    op.create_unique_constraint('uq_llmmodel_provider_model', 'llmmodel', ['primary_provider_type_id', 'model_id'])
    op.drop_constraint(op.f('llmmodel_provider_id_fkey'), 'llmmodel', type_='foreignkey')
    op.create_foreign_key(None, 'llmmodel', 'provider_type', ['primary_provider_type_id'], ['id'])
    op.drop_column('llmmodel', 'provider_id')
    op.add_column('user_access_provider', sa.Column('provider_type_multiple', sa.Boolean(), nullable=False))
    op.add_column('user_access_provider', sa.Column('alpha_provider_type_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_user_access_provider_alpha_provider_type_id'), 'user_access_provider', ['alpha_provider_type_id'], unique=False)
    op.create_foreign_key(None, 'user_access_provider', 'provider_type', ['alpha_provider_type_id'], ['id'])
    op.add_column('user_agent_configs', sa.Column('provider_type_id', sa.Uuid(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_agent_configs', 'provider_type_id')
    op.drop_constraint(None, 'user_access_provider', type_='foreignkey')
    op.drop_index(op.f('ix_user_access_provider_alpha_provider_type_id'), table_name='user_access_provider')
    op.drop_column('user_access_provider', 'alpha_provider_type_id')
    op.drop_column('user_access_provider', 'provider_type_multiple')
    op.add_column('llmmodel', sa.Column('provider_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'llmmodel', type_='foreignkey')
    op.create_foreign_key(op.f('llmmodel_provider_id_fkey'), 'llmmodel', 'provider_type', ['provider_id'], ['id'])
    op.drop_constraint('uq_llmmodel_provider_model', 'llmmodel', type_='unique')
    op.drop_index(op.f('ix_llmmodel_primary_provider_type_id'), table_name='llmmodel')
    op.create_index(op.f('ix_llmmodel_provider_id'), 'llmmodel', ['provider_id'], unique=False)
    op.drop_column('llmmodel', 'primary_provider_type_id')
    op.drop_column('llmmodel', 'multiple_provider_type_support')
    op.alter_column('frontier_access_provider', 'testing_api_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
