"""adding models for stuff

Revision ID: 33ac08b003d5
Revises: 0995d27cc387
Create Date: 2026-02-24 13:14:44.486613

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '33ac08b003d5'
down_revision = '0995d27cc387'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_configs',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('latest_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_configs_owner_id'), 'prompt_configs', ['owner_id'], unique=False)
    op.create_table('prompt_config_versions',
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('parent_version_id', sa.Uuid(), nullable=True),
    sa.Column('commit_message', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('prompt_config_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['prompt_config_id'], ['prompt_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt_config_id', 'version_number')
    )
    op.create_index(op.f('ix_prompt_config_versions_prompt_config_id'), 'prompt_config_versions', ['prompt_config_id'], unique=False)
    op.create_table('prompt_config_working_copies',
    sa.Column('base_version', sa.Integer(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('has_uncommitted_changes', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('prompt_config_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['prompt_config_id'], ['prompt_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt_config_id')
    )
    op.create_index(op.f('ix_prompt_config_working_copies_prompt_config_id'), 'prompt_config_working_copies', ['prompt_config_id'], unique=False)
    op.drop_table('api_code_chunks')
    op.drop_index(op.f('idx_api_areas_ivf'), table_name='api_areas', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_table('api_areas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_areas',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('tag_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tag_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('chunk_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('service', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('api_areas_pkey')),
    sa.UniqueConstraint('service', 'version', 'tag_name', name=op.f('api_areas_service_version_tag_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_api_areas_ivf'), 'api_areas', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_table('api_code_chunks',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('corpus', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('chunk_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source_file', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('kind', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('start_line', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('end_line', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('raw_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embed_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('api_code_chunks_pkey')),
    sa.UniqueConstraint('corpus', 'chunk_key', name=op.f('api_code_chunks_corpus_chunk_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index(op.f('ix_prompt_config_working_copies_prompt_config_id'), table_name='prompt_config_working_copies')
    op.drop_table('prompt_config_working_copies')
    op.drop_index(op.f('ix_prompt_config_versions_prompt_config_id'), table_name='prompt_config_versions')
    op.drop_table('prompt_config_versions')
    op.drop_index(op.f('ix_prompt_configs_owner_id'), table_name='prompt_configs')
    op.drop_table('prompt_configs')
    # ### end Alembic commands ###
