"""some fixes on trait-personal-rel-model branch

Revision ID: 3701683c820f
Revises: 26efbad597c5
Create Date: 2025-04-22 19:23:17.107245

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3701683c820f'
down_revision = '26efbad597c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archetype', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('archetype', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.drop_column('archetype', 'archetype_description')
    op.drop_column('archetype', 'updated_at')
    op.drop_column('archetype', 'archetype_name')
    op.add_column('persona', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('persona', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.drop_column('persona', 'updated_at')
    op.drop_column('persona', 'persona_description')
    op.drop_column('persona', 'persona_name')
    op.add_column('personatraitlink', sa.Column('trait_id', sa.Uuid(), nullable=False))
    op.drop_constraint('personatraitlink_traid_id_fkey', 'personatraitlink', type_='foreignkey')
    op.create_foreign_key(None, 'personatraitlink', 'trait', ['trait_id'], ['id'])
    op.drop_column('personatraitlink', 'traid_id')
    op.add_column('quality', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('quality', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.drop_column('quality', 'updated_at')
    op.drop_column('quality', 'quality_name')
    op.drop_column('quality', 'quality_description')
    op.add_column('trait', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('trait', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.drop_column('trait', 'trait_name')
    op.drop_column('trait', 'updated_at')
    op.drop_column('trait', 'trait_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trait', sa.Column('trait_description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('trait', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('trait', sa.Column('trait_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('trait', 'description')
    op.drop_column('trait', 'title')
    op.add_column('quality', sa.Column('quality_description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('quality', sa.Column('quality_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('quality', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('quality', 'description')
    op.drop_column('quality', 'title')
    op.add_column('personatraitlink', sa.Column('traid_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'personatraitlink', type_='foreignkey')
    op.create_foreign_key('personatraitlink_traid_id_fkey', 'personatraitlink', 'trait', ['traid_id'], ['id'])
    op.drop_column('personatraitlink', 'trait_id')
    op.add_column('persona', sa.Column('persona_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('persona', sa.Column('persona_description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('persona', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('persona', 'description')
    op.drop_column('persona', 'title')
    op.add_column('archetype', sa.Column('archetype_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('archetype', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('archetype', sa.Column('archetype_description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('archetype', 'description')
    op.drop_column('archetype', 'title')
    # ### end Alembic commands ###
