"""Refactor story system with versioning

Revision ID: 4454c294c606
Revises: 16c9584a8f10
Create Date: 2025-12-09 23:45:38.118653

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4454c294c606'
down_revision = '16c9584a8f10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userpersona',
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('persona_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storyrequirement',
    sa.Column('requirement_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('story_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userstoryprogress',
    sa.Column('current_node_id', sa.Uuid(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('story_state', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_persona_id', sa.Uuid(), nullable=False),
    sa.Column('story_id', sa.Uuid(), nullable=False),
    sa.Column('story_version', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_persona_id'], ['userpersona.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usernodechoice',
    sa.Column('choice_text', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('from_node_id', sa.Uuid(), nullable=False),
    sa.Column('to_node_id', sa.Uuid(), nullable=False),
    sa.Column('state_changes', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('progress_id', sa.Uuid(), nullable=False),
    sa.Column('choice_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['progress_id'], ['userstoryprogress.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('nodechoice', sa.Column('requires_state', sa.JSON(), nullable=True))
    op.add_column('nodechoice', sa.Column('sets_state', sa.JSON(), nullable=True))
    op.add_column('nodechoice', sa.Column('from_node_id', sa.Uuid(), nullable=False))
    op.add_column('nodechoice', sa.Column('to_node_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'nodechoice', 'storynode', ['to_node_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'nodechoice', 'storynode', ['from_node_id'], ['id'], ondelete='CASCADE')
    op.add_column('story', sa.Column('current_version', sa.Integer(), nullable=False))
    op.add_column('story', sa.Column('published_version', sa.Integer(), nullable=True))
    op.add_column('storynode', sa.Column('story_version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storynode', 'story_version')
    op.drop_column('story', 'published_version')
    op.drop_column('story', 'current_version')
    op.drop_constraint(None, 'nodechoice', type_='foreignkey')
    op.drop_constraint(None, 'nodechoice', type_='foreignkey')
    op.drop_column('nodechoice', 'to_node_id')
    op.drop_column('nodechoice', 'from_node_id')
    op.drop_column('nodechoice', 'sets_state')
    op.drop_column('nodechoice', 'requires_state')
    op.drop_table('usernodechoice')
    op.drop_table('userstoryprogress')
    op.drop_table('storyrequirement')
    op.drop_table('userpersona')
    # ### end Alembic commands ###