"""changing llmprovidertype gracefully

Revision ID: 45d2c594279d
Revises: 8b26bd02b081
Create Date: 2026-01-28 01:13:10.957102

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '45d2c594279d'
down_revision = '8b26bd02b081'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_type',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('details', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('agent_configs', 'provider_type',
               existing_type=postgresql.ENUM('OPENAI', 'ANTHROPIC', 'GOOGLE', 'OPENAI_COMPATIBLE', 'EMPTY', name='llmprovidertype'),
               type_=sqlmodel.sql.sqltypes.AutoString(length=30),
               existing_nullable=False)
    op.add_column('llmprovider', sa.Column('provider_type_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'llmprovider', 'provider_type', ['provider_type_id'], ['id'])
    op.drop_column('llmprovider', 'provider_type')
    op.alter_column('userllmprovider', 'provider_type',
               existing_type=postgresql.ENUM('OPENAI', 'ANTHROPIC', 'GOOGLE', 'OPENAI_COMPATIBLE', 'EMPTY', name='llmprovidertype'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userllmprovider', 'provider_type',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('OPENAI', 'ANTHROPIC', 'GOOGLE', 'OPENAI_COMPATIBLE', 'EMPTY', name='llmprovidertype'),
               nullable=True)
    op.add_column('llmprovider', sa.Column('provider_type', postgresql.ENUM('OPENAI', 'ANTHROPIC', 'GOOGLE', 'OPENAI_COMPATIBLE', 'EMPTY', name='llmprovidertype'), server_default=sa.text("'EMPTY'::llmprovidertype"), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'llmprovider', type_='foreignkey')
    op.drop_column('llmprovider', 'provider_type_id')
    op.alter_column('agent_configs', 'provider_type',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=30),
               type_=postgresql.ENUM('OPENAI', 'ANTHROPIC', 'GOOGLE', 'OPENAI_COMPATIBLE', 'EMPTY', name='llmprovidertype'),
               existing_nullable=False)
    op.drop_table('provider_type')
    # ### end Alembic commands ###