"""mucking about day 124

Revision ID: 49635eb74747
Revises: 906c96b34cb2
Create Date: 2026-02-01 19:38:33.791972

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '49635eb74747'
down_revision = '906c96b34cb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
