"""changing provider_type_id on useragentconfigbase to provider_type, changing all inheriting classes to use UUID instead of str w/ default_factory

Revision ID: 4b3398004e6e
Revises: 49635eb74747
Create Date: 2026-02-02 17:49:24.107349

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4b3398004e6e'
down_revision = '49635eb74747'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'user_agent_configs',
        'provider_type',
        existing_type=sa.VARCHAR(length=30),
        type_=sa.Uuid(),
        existing_nullable=True,
        postgresql_using='provider_type::uuid',  # explicit cast to avoid USING hint error
    )
    op.drop_column('user_agent_configs', 'provider_type_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_agent_configs', sa.Column('provider_type_id', sa.UUID(), autoincrement=False, nullable=False))
    op.alter_column('user_agent_configs', 'provider_type',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###
