"""attempting to address owner_user_id problems

Revision ID: 59f7fd6267a9
Revises: bf35502fbf84
Create Date: 2026-03-04 08:47:09.630613

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '59f7fd6267a9'
down_revision = 'bf35502fbf84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
