"""modifications (additions) to models for UserAgentConfig for presentation layer

Revision ID: 5a0eec5b752e
Revises: dd33073093aa
Create Date: 2026-02-07 10:39:44.219071

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5a0eec5b752e'
down_revision = 'dd33073093aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_agent_configs', sa.Column('agent_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_agent_configs', sa.Column('presentation', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_agent_configs', 'presentation')
    op.drop_column('user_agent_configs', 'agent_type')
    # ### end Alembic commands ###
