"""add prompt config slugger

Revision ID: 5a4a4336bdeb
Revises: 9ec82d3b46c4
Create Date: 2026-02-27 14:26:41.966631

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5a4a4336bdeb'
down_revision = '9ec82d3b46c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_configs', sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    op.create_unique_constraint('uq_prompt_config_slug', 'prompt_configs', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_prompt_config_slug', 'prompt_configs', type_='unique')
    op.drop_column('prompt_configs', 'slug')
    # ### end Alembic commands ###
