"""LLMModel and LLMProvider adjusted for User Funtimes

Revision ID: 611c94f8a039
Revises: 8ad6e6ed4183
Create Date: 2026-01-18 18:01:05.579609

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '611c94f8a039'
down_revision = '8ad6e6ed4183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llmmodel', sa.Column('is_system', sa.Boolean(), nullable=False))
    op.add_column('llmmodel', sa.Column('created_by_user_id', sa.Uuid(), nullable=True))
    op.alter_column('llmmodel', 'provider_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('uq_provider_model'), 'llmmodel', type_='unique')
    op.create_unique_constraint('uq_provider_model', 'llmmodel', ['provider_id', 'model_id', 'created_by_user_id'])
    op.create_index(op.f('ix_llmmodel_is_system'), 'llmmodel', ['is_system'], unique=False)
    op.create_foreign_key(None, 'llmmodel', 'user', ['created_by_user_id'], ['id'])
    op.add_column('llmprovider', sa.Column('created_by_user_id', sa.Uuid(), nullable=True))
    op.alter_column('llmprovider', 'provider_type',
               existing_type=postgresql.ENUM('OPENAI', 'ANTHROPIC', 'GOOGLE', 'OPENAI_COMPATIBLE', 'EMPTY', name='llmprovidertype'),
               nullable=True,
               existing_server_default=sa.text("'EMPTY'::llmprovidertype"))
    op.create_foreign_key(None, 'llmprovider', 'user', ['created_by_user_id'], ['id'])
    op.alter_column('userllmprovider', 'provider_type',
               existing_type=postgresql.ENUM('OPENAI', 'ANTHROPIC', 'GOOGLE', 'OPENAI_COMPATIBLE', 'EMPTY', name='llmprovidertype'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userllmprovider', 'provider_type',
               existing_type=postgresql.ENUM('OPENAI', 'ANTHROPIC', 'GOOGLE', 'OPENAI_COMPATIBLE', 'EMPTY', name='llmprovidertype'),
               nullable=False)
    op.drop_constraint(None, 'llmprovider', type_='foreignkey')
    op.alter_column('llmprovider', 'provider_type',
               existing_type=postgresql.ENUM('OPENAI', 'ANTHROPIC', 'GOOGLE', 'OPENAI_COMPATIBLE', 'EMPTY', name='llmprovidertype'),
               nullable=False,
               existing_server_default=sa.text("'EMPTY'::llmprovidertype"))
    op.drop_column('llmprovider', 'created_by_user_id')
    op.drop_constraint(None, 'llmmodel', type_='foreignkey')
    op.drop_index(op.f('ix_llmmodel_is_system'), table_name='llmmodel')
    op.drop_constraint('uq_provider_model', 'llmmodel', type_='unique')
    op.create_unique_constraint(op.f('uq_provider_model'), 'llmmodel', ['provider_id', 'model_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('llmmodel', 'provider_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('llmmodel', 'created_by_user_id')
    op.drop_column('llmmodel', 'is_system')
    # ### end Alembic commands ###