"""these changes, they changed me first

Revision ID: 62b2a26e9cc0
Revises: 4454c294c606
Create Date: 2025-12-19 14:44:07.811244

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '62b2a26e9cc0'
down_revision = '4454c294c606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('story_id', sa.Uuid(), nullable=True),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('creator_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_table('room_events',
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('room_sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], ),
    sa.PrimaryKeyConstraint('event_id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_room_events_created_at'), 'room_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_room_events_room_id'), 'room_events', ['room_id'], unique=False)
    op.create_table('room_messages',
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sender_type', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=True),
    sa.Column('agent_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_room_messages_created_at'), 'room_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_room_messages_room_id'), 'room_messages', ['room_id'], unique=False)
    op.create_table('room_participants',
    sa.Column('participant_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('participant_type', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_room_participants_room_id'), 'room_participants', ['room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_participants_room_id'), table_name='room_participants')
    op.drop_table('room_participants')
    op.drop_index(op.f('ix_room_messages_room_id'), table_name='room_messages')
    op.drop_index(op.f('ix_room_messages_created_at'), table_name='room_messages')
    op.drop_table('room_messages')
    op.drop_index(op.f('ix_room_events_room_id'), table_name='room_events')
    op.drop_index(op.f('ix_room_events_created_at'), table_name='room_events')
    op.drop_table('room_events')
    op.drop_table('rooms')
    # ### end Alembic commands ###