"""revising shadowmodels

Revision ID: 631420dcd727
Revises: 81f81ecedf0b
Create Date: 2026-01-16 16:53:58.789152

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '631420dcd727'
down_revision = '81f81ecedf0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shadowrepo', sa.Column('owner_id', sa.Uuid(), nullable=False))
    op.alter_column('shadowrepo', 'forgejo_repo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('shadowrepo_shadow_user_id_fkey'), 'shadowrepo', type_='foreignkey')
    op.create_foreign_key(None, 'shadowrepo', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('shadowrepo', 'shadow_user_id')
    op.add_column('shadowuser', sa.Column('forgejo_repo_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('shadowuser', sa.Column('forgejo_repo_id', sa.Integer(), nullable=True))
    op.drop_column('shadowuser', 'forgejo_token_encrypted')
    op.drop_column('shadowuser', 'forgejo_username')
    op.drop_column('shadowuser', 'forgejo_user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shadowuser', sa.Column('forgejo_user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('shadowuser', sa.Column('forgejo_username', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('shadowuser', sa.Column('forgejo_token_encrypted', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_column('shadowuser', 'forgejo_repo_id')
    op.drop_column('shadowuser', 'forgejo_repo_name')
    op.add_column('shadowrepo', sa.Column('shadow_user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'shadowrepo', type_='foreignkey')
    op.create_foreign_key(op.f('shadowrepo_shadow_user_id_fkey'), 'shadowrepo', 'shadowuser', ['shadow_user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('shadowrepo', 'forgejo_repo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('shadowrepo', 'owner_id')
    # ### end Alembic commands ###