"""add button_options to room messages, enrichment metadata to room_events

Revision ID: 6a8a3b609f86
Revises: 62b2a26e9cc0
Create Date: 2025-12-28 18:06:50.711839

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6a8a3b609f86'
down_revision = '62b2a26e9cc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_events', sa.Column('enrichment_metadata', sa.JSON(), nullable=True))
    op.add_column('room_messages', sa.Column('button_options', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_messages', 'button_options')
    op.drop_column('room_events', 'enrichment_metadata')
    # ### end Alembic commands ###