"""add all spec types

Revision ID: 6b854b57dbb5
Revises: a740ef4345ab
Create Date: 2026-02-21 09:21:35.286741

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6b854b57dbb5'
down_revision = 'a740ef4345ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo_page_compositions',
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('layout_mode', sa.Enum('panels', 'tabs', name='demolayoutmode'), nullable=False),
    sa.Column('runtime_policy', sa.Enum('auto', 'manual', 'owner_only', name='demoruntimepolicy'), nullable=False),
    sa.Column('persona_policy', sa.Enum('first_available', 'fixed_user_persona', 'manual_prompt', name='demopersonapolicy'), nullable=False),
    sa.Column('chat_mode', sa.Enum('participant', 'observer', name='demochatmode'), nullable=False),
    sa.Column('fixed_user_persona_id', sa.Uuid(), nullable=True),
    sa.Column('page_theme_id', sa.Uuid(), nullable=True),
    sa.Column('cards_theme_id', sa.Uuid(), nullable=True),
    sa.Column('panels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('blocks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('presentation_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_demo_page_composition_overrides',
    sa.Column('use_composition_defaults', sa.Boolean(), nullable=False),
    sa.Column('override_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_demo_page_composition_overrides')
    op.drop_table('demo_page_compositions')
    # ### end Alembic commands ###
