"""I guess we'll see

Revision ID: 6e1971b061e3
Revises: f69d55cc4dca
Create Date: 2025-04-22 22:44:08.547695
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6e1971b061e3'
down_revision = 'f69d55cc4dca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personaqualitylink',
    sa.Column('persona_id', sa.Uuid(), nullable=False),
    sa.Column('quality_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.Enum('TRAIT_DEPENDENT', 'DEFAULT', 'MANUALLY_ADDED', name='qualitysourcetype'), nullable=False),
    sa.Column('state', sa.Enum('ENABLED', 'DISABLED', 'REMOVED', name='qualitystate'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('source_trait_id', sa.Uuid(), nullable=True),
    sa.Column('source_archetype_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['quality_id'], ['quality.id'], ),
    sa.ForeignKeyConstraint(['source_archetype_id'], ['archetype.id'], ),
    sa.ForeignKeyConstraint(['source_trait_id'], ['trait.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qualityeventtrigger',
    sa.Column('quality_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('new_state', sa.Enum('ENABLED', 'DISABLED', 'REMOVED', name='qualitystate'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('condition_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['quality_id'], ['quality.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qualitytraitlink',
    sa.Column('quality_id', sa.Uuid(), nullable=False),
    sa.Column('trait_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('auto_enable', sa.Boolean(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['quality_id'], ['quality.id'], ),
    sa.ForeignKeyConstraint(['trait_id'], ['trait.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('personatraitlink', sa.Column('is_inherited', sa.Boolean(), nullable=False))
    op.add_column('personatraitlink', sa.Column('source_archetype_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'personatraitlink', 'archetype', ['source_archetype_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'personatraitlink', type_='foreignkey')
    op.drop_column('personatraitlink', 'source_archetype_id')
    op.drop_column('personatraitlink', 'is_inherited')
    op.drop_table('qualitytraitlink')
    op.drop_table('qualityeventtrigger')
    op.drop_table('personaqualitylink')
    op.drop_table('event')
    # ### end Alembic commands ###
