"""Add table things stuff this message annoys chatgpt

Revision ID: 73a3fa6d7428
Revises: befb94034e80
Create Date: 2026-03-09 07:16:39.724217

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '73a3fa6d7428'
down_revision = 'befb94034e80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
