"""add nonos

Revision ID: 790cfc1c0278
Revises: 5a4a4336bdeb
Create Date: 2026-02-27 15:16:54.803652

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '790cfc1c0278'
down_revision = '5a4a4336bdeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_agent_settings', sa.Column('prompt_config_id', sa.Uuid(), nullable=True))
    op.add_column('room_agent_settings', sa.Column('prompt_config_version_policy', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('room_agent_settings', sa.Column('prompt_config_version_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_agent_settings', 'prompt_config_version_number')
    op.drop_column('room_agent_settings', 'prompt_config_version_policy')
    op.drop_column('room_agent_settings', 'prompt_config_id')
    # ### end Alembic commands ###
