"""gogs repo cleanup

Revision ID: 7ba0ab8522ab
Revises: 8c4c5b6a1f2d
Create Date: 2026-03-03 04:26:54.935321

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ba0ab8522ab'
down_revision = '8c4c5b6a1f2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pages', 'presentation_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    
    # Create the enum type
    userrepoimportstatus = sa.Enum(
        "PENDING", "IMPORTING", "READY", "FAILED",
        name="userrepoimportstatus"
    )
    userrepoimportstatus.create(op.get_bind())
    
    # Drop the default first
    op.execute(
        "ALTER TABLE user_repos ALTER COLUMN import_status DROP DEFAULT"
    )

    # Now alter the column type
    op.execute("""
        ALTER TABLE user_repos
        ALTER COLUMN import_status
        TYPE userrepoimportstatus
        USING import_status::text::userrepoimportstatus
    """)

    # Optionally set a new default matching the enum
    op.execute(
        "ALTER TABLE user_repos ALTER COLUMN import_status "
        "SET DEFAULT 'PENDING'::userrepoimportstatus"
    )

    op.execute("""
        ALTER TABLE user_repos
        ALTER COLUMN import_status
        TYPE userrepoimportstatus
        USING import_status::text::userrepoimportstatus
    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_repos', 'import_status',
               existing_type=sa.Enum('PENDING', 'IMPORTING', 'READY', 'FAILED', name='userrepoimportstatus'),
               type_=sa.VARCHAR(length=255),
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('pages', 'presentation_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###
