"""updates for stuff, i forgetted

Revision ID: 842ce5c8827d
Revises: 8f2d2d7b3f44
Create Date: 2026-01-21 07:27:06.038074

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '842ce5c8827d'
down_revision = '8f2d2d7b3f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_story_progresses_room_id'), table_name='room_story_progresses')
    op.create_index(op.f('ix_room_story_progresses_room_id'), 'room_story_progresses', ['room_id'], unique=False)
    op.drop_constraint(op.f('room_story_progresses_story_id_fkey'), 'room_story_progresses', type_='foreignkey')
    op.drop_constraint(op.f('room_story_progresses_active_progress_id_fkey'), 'room_story_progresses', type_='foreignkey')
    op.create_foreign_key(None, 'room_story_progresses', 'story', ['story_id'], ['id'])
    op.create_foreign_key(None, 'room_story_progresses', 'userstoryprogress', ['active_progress_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'room_story_progresses', type_='foreignkey')
    op.drop_constraint(None, 'room_story_progresses', type_='foreignkey')
    op.create_foreign_key(op.f('room_story_progresses_active_progress_id_fkey'), 'room_story_progresses', 'userstoryprogress', ['active_progress_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('room_story_progresses_story_id_fkey'), 'room_story_progresses', 'story', ['story_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_room_story_progresses_room_id'), table_name='room_story_progresses')
    op.create_index(op.f('ix_room_story_progresses_room_id'), 'room_story_progresses', ['room_id'], unique=True)
    # ### end Alembic commands ###