"""LLM providers and models

Revision ID: 8ad6e6ed4183
Revises: 0531236bd820
Create Date: 2026-01-18 01:44:48.996510

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ad6e6ed4183'
down_revision = '0531236bd820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llmprovider',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llmprovider_is_deleted'), 'llmprovider', ['is_deleted'], unique=False)
    op.create_table('llmmodel',
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_deprecated', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('has_vision', sa.Boolean(), nullable=True),
    sa.Column('has_function_calling', sa.Boolean(), nullable=True),
    sa.Column('has_streaming', sa.Boolean(), nullable=True),
    sa.Column('has_json_mode', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('deprecated_at', sa.DateTime(), nullable=True),
    sa.Column('sunset_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('secondary_capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['llmprovider.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'model_id', name='uq_provider_model')
    )
    op.create_index(op.f('ix_llmmodel_is_deleted'), 'llmmodel', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_llmmodel_provider_id'), 'llmmodel', ['provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userllmprovider', 'provider_type',
               existing_type=postgresql.ENUM('OPENAI', 'ANTHROPIC', 'GOOGLE', 'OPENAI_COMPATIBLE', name='llmprovidertype'),
               nullable=False)
    op.drop_index(op.f('ix_llmmodel_provider_id'), table_name='llmmodel')
    op.drop_index(op.f('ix_llmmodel_is_deleted'), table_name='llmmodel')
    op.drop_table('llmmodel')
    op.drop_index(op.f('ix_llmprovider_is_deleted'), table_name='llmprovider')
    op.drop_table('llmprovider')
    # ### end Alembic commands ###