"""adding user_provider and provider_type to AgentConfig

Revision ID: 8b26bd02b081
Revises: d8e475bab15d
Create Date: 2026-01-26 00:42:49.603452

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8b26bd02b081'
down_revision = 'd8e475bab15d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_configs', sa.Column('user_provider', sa.Uuid(), nullable=False))
    op.add_column('agent_configs', sa.Column('provider_type', sa.Enum('EMPTY', 'OPENAI', 'ANTHROPIC', 'GOOGLE', 'OPENAI_COMPATIBLE', name='llmprovidertype'), nullable=False))
    op.create_foreign_key(None, 'agent_configs', 'userllmprovider', ['user_provider'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agent_configs', type_='foreignkey')
    op.drop_column('agent_configs', 'provider_type')
    op.drop_column('agent_configs', 'user_provider')
    # ### end Alembic commands ###