"""svg library wow

Revision ID: 8eef84204fa7
Revises: a9c3f1d2e4b7
Create Date: 2026-03-15 10:01:58.284256

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8eef84204fa7'
down_revision = 'a9c3f1d2e4b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('svgasset',
    sa.Column('visibility', sa.Enum('PRIVATE', 'PUBLIC', name='svgassetvisibility'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('svg_markup', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_private_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_private_id'], ['svgasset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_svgasset_name'), 'svgasset', ['name'], unique=False)
    op.create_index(op.f('ix_svgasset_owner_id'), 'svgasset', ['owner_id'], unique=False)
    op.create_index(op.f('ix_svgasset_source_private_id'), 'svgasset', ['source_private_id'], unique=False)
    op.create_index(op.f('ix_svgasset_updated_at'), 'svgasset', ['updated_at'], unique=False)
    op.create_index(op.f('ix_svgasset_visibility'), 'svgasset', ['visibility'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_svgasset_visibility'), table_name='svgasset')
    op.drop_index(op.f('ix_svgasset_updated_at'), table_name='svgasset')
    op.drop_index(op.f('ix_svgasset_source_private_id'), table_name='svgasset')
    op.drop_index(op.f('ix_svgasset_owner_id'), table_name='svgasset')
    op.drop_index(op.f('ix_svgasset_name'), table_name='svgasset')
    op.drop_table('svgasset')
    # ### end Alembic commands ###
