"""mucking about day 124

Revision ID: 906c96b34cb2
Revises: 4664db23b3b4
Create Date: 2026-02-01 16:24:14.354362

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '906c96b34cb2'
down_revision = '4664db23b3b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
