"""UserPersona work continued - adding persona record and registry

Revision ID: 95c0bbd024bd
Revises: 217e959c137c
Create Date: 2026-03-08 11:11:55.510953

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '95c0bbd024bd'
down_revision = '217e959c137c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
