"""Add tool enablement flags to user_agent_configs

Revision ID: 9ce32ca93c1d
Revises: 59f7fd6267a9
Create Date: 2026-03-04 15:06:40.070117

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9ce32ca93c1d'
down_revision = '59f7fd6267a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with server_default=False for existing rows
    op.add_column('user_agent_configs', sa.Column('enable_a2a_tool', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_agent_configs', sa.Column('enable_ag_ui_tool', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_agent_configs', 'enable_ag_ui_tool')
    op.drop_column('user_agent_configs', 'enable_a2a_tool')
    # ### end Alembic commands ###
