"""fixing alembic messup

Revision ID: 9e3e5fe1f359
Revises: 95c0bbd024bd
Create Date: 2026-03-08 11:38:09.548380

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '9e3e5fe1f359'
down_revision = '95c0bbd024bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persona_groups',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('group_type', sa.Enum('group', 'workspace', name='personagrouptype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_user_persona_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_persona_id'], ['userpersona.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_persona_id', 'name', name='uq_persona_groups_owner_persona_name')
    )
    op.create_index(op.f('ix_persona_groups_owner_user_persona_id'), 'persona_groups', ['owner_user_persona_id'], unique=False)
    op.create_table('persona_group_memberships',
    sa.Column('role', postgresql.ENUM('member', 'manager', name='usergroupmembershiprole', create_type=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('user_persona_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['persona_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_persona_id'], ['userpersona.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_persona_id', name='uq_persona_group_memberships_group_user_persona')
    )
    op.create_index(op.f('ix_persona_group_memberships_group_id'), 'persona_group_memberships', ['group_id'], unique=False)
    op.create_index(op.f('ix_persona_group_memberships_user_persona_id'), 'persona_group_memberships', ['user_persona_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_persona_group_memberships_user_persona_id'), table_name='persona_group_memberships')
    op.drop_index(op.f('ix_persona_group_memberships_group_id'), table_name='persona_group_memberships')
    op.drop_table('persona_group_memberships')
    op.drop_index(op.f('ix_persona_groups_owner_user_persona_id'), table_name='persona_groups')
    op.drop_table('persona_groups')
    # ### end Alembic commands ###
