"""add prompt config bindings to user agent configs

Revision ID: 9ec82d3b46c4
Revises: 33ac08b003d5
Create Date: 2026-02-27 14:07:39.169376

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9ec82d3b46c4'
down_revision = '33ac08b003d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_agent_configs', sa.Column('prompt_config_id', sa.Uuid(), nullable=True))
    op.add_column('user_agent_configs', sa.Column('prompt_config_version_policy', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('user_agent_configs', sa.Column('prompt_config_version_number', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_agent_configs_prompt_config_id'), 'user_agent_configs', ['prompt_config_id'], unique=False)
    op.create_foreign_key(None, 'user_agent_configs', 'prompt_configs', ['prompt_config_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_agent_configs', type_='foreignkey')
    op.drop_index(op.f('ix_user_agent_configs_prompt_config_id'), table_name='user_agent_configs')
    op.drop_column('user_agent_configs', 'prompt_config_version_number')
    op.drop_column('user_agent_configs', 'prompt_config_version_policy')
    op.drop_column('user_agent_configs', 'prompt_config_id')
    # ### end Alembic commands ###
