"""just a wee change to the contentformat enum which will probably break everything

Revision ID: a20d937be623
Revises: 0d9df4978995
Create Date: 2026-02-14 12:08:37.944020

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a20d937be623'
down_revision = '0d9df4978995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
