"""Add ProgressSnapshot model

Revision ID: aa244f8bb6c0
Revises: 135dd2454c3d
Create Date: 2026-01-05 14:19:20.586913

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'aa244f8bb6c0'
down_revision = '135dd2454c3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progresssnapshot',
    sa.Column('story_state', sa.JSON(), nullable=True),
    sa.Column('current_node_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('progress_id', sa.Uuid(), nullable=False),
    sa.Column('choice_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['choice_id'], ['usernodechoice.id'], ),
    sa.ForeignKeyConstraint(['progress_id'], ['userstoryprogress.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('idx_usernodechoice_parent'), table_name='usernodechoice')
    op.drop_index(op.f('idx_userstoryprogress_head'), table_name='userstoryprogress')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_userstoryprogress_head'), 'userstoryprogress', ['head_choice_id'], unique=False)
    op.create_index(op.f('idx_usernodechoice_parent'), 'usernodechoice', ['parent_choice_id'], unique=False)
    op.drop_table('progresssnapshot')
    # ### end Alembic commands ###