"""agent config to user agent config

Revision ID: b0b483904994
Revises: fdc189643ab5
Create Date: 2026-01-29 19:05:20.194551

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0b483904994'
down_revision = 'fdc189643ab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('room_participant_bindings_agent_id_fkey'), 'room_participant_bindings', type_='foreignkey')
    op.drop_constraint(op.f('agent_personas_agent_id_fkey'), 'agent_personas', type_='foreignkey')
    op.drop_constraint(op.f('uq_provider_model'), 'llmmodel', type_='unique')
    op.drop_constraint(op.f('llmmodel_provider_id_fkey'), 'llmmodel', type_='foreignkey')
    op.drop_constraint(op.f('room_participant_bindings_user_llm_provider_id_fkey'), 'room_participant_bindings', type_='foreignkey')
    op.drop_constraint(op.f(name='user_agent_settings_agent_config_id_fkey'), 'user_agent_settings', type_='foreignkey')
    op.drop_index(op.f('ix_user_agent_settings_agent_config_id'), table_name='user_agent_settings')
    op.drop_index(op.f('ix_user_agent_settings_user_id'), table_name='user_agent_settings')
    op.drop_table('user_agent_settings')
    op.drop_constraint(op.f('agent_configs_user_provider_fkey'), 'agent_configs', type_='foreignkey')
    op.drop_index(op.f('ix_userllmprovider_user_id'), table_name='userllmprovider')
    op.drop_table('userllmprovider')
    op.drop_index(op.f('ix_llmprovider_is_deleted'), table_name='llmprovider')
    op.drop_table('llmprovider')
    op.drop_table('agent_configs')
    op.create_table('user_access_provider',
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('api_key_encrypted', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_tested_at', sa.DateTime(), nullable=True),
    sa.Column('last_test_success', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_access_provider_user_id'), 'user_access_provider', ['user_id'], unique=False)
    op.create_table('user_agent_configs',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('user_access_provider', sa.Uuid(), nullable=True),
    sa.Column('provider_type', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('model_id', sa.Uuid(), nullable=True),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('system_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('custom_system_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tool_config', sa.JSON(), nullable=True),
    sa.Column('deps_config', sa.JSON(), nullable=True),
    sa.Column('agent_metadata', sa.JSON(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_clonable', sa.Boolean(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('participation_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_coordinator', sa.Boolean(), nullable=True),
    sa.Column('max_tool_iterations', sa.Integer(), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('llmmodel', 'provider_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_foreign_key(None, 'llmmodel', 'provider_type', ['provider_id'], ['id'])
    op.create_foreign_key(None, 'agent_personas', 'user_agent_configs', ['agent_id'], ['id'], ondelete='CASCADE')
    op.add_column('room_participant_bindings', sa.Column('user_access_provider_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'room_participant_bindings', 'user_access_provider', ['user_access_provider_id'], ['id'])
    op.create_foreign_key(None, 'room_participant_bindings', 'user_agent_configs', ['agent_id'], ['id'])
    op.drop_column('room_participant_bindings', 'user_llm_provider_id')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_participant_bindings', sa.Column('user_llm_provider_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'room_participant_bindings', type_='foreignkey')
    op.drop_constraint(None, 'room_participant_bindings', type_='foreignkey')
    op.create_foreign_key(op.f('room_participant_bindings_user_llm_provider_id_fkey'), 'room_participant_bindings', 'userllmprovider', ['user_llm_provider_id'], ['id'])
    op.create_foreign_key(op.f('room_participant_bindings_agent_id_fkey'), 'room_participant_bindings', 'agent_configs', ['agent_id'], ['id'])
    op.drop_column('room_participant_bindings', 'user_access_provider_id')
    op.drop_constraint(None, 'llmmodel', type_='foreignkey')
    op.create_unique_constraint(op.f('uq_provider_model'), 'llmmodel', ['provider_id', 'model_id', 'created_by_user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('llmmodel', 'provider_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(op.f('llmmodel_provider_id_fkey'), 'llmmodel', 'llmprovider', ['provider_id'], ['id'])
    op.drop_constraint(None, 'agent_personas', type_='foreignkey')
    op.create_foreign_key(op.f('agent_personas_agent_id_fkey'), 'agent_personas', 'agent_configs', ['agent_id'], ['id'], ondelete='CASCADE')
    op.create_table('userllmprovider',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('base_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('api_key_encrypted', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_tested_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_test_success', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('provider_type_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['provider_type_id'], ['provider_type.id'], name='userllmprovider_provider_type_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='userllmprovider_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='userllmprovider_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_userllmprovider_user_id'), 'userllmprovider', ['user_id'], unique=False)
    op.create_table('user_agent_settings',
    sa.Column('provider_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('custom_system_prompt', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_favorite', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_config_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('model_name_override', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('user_agent_settings_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_agent_settings_pkey')),
    sa.UniqueConstraint('user_id', 'agent_config_id', name=op.f('uq_user_agent_settings'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_agent_settings_user_id'), 'user_agent_settings', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_agent_settings_agent_config_id'), 'user_agent_settings', ['agent_config_id'], unique=False)
    op.create_table('llmprovider',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('base_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_system', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('provider_type_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], name=op.f('llmprovider_created_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['provider_type_id'], ['provider_type.id'], name=op.f('llmprovider_provider_type_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('llmprovider_pkey'))
    )
    op.create_index(op.f('ix_llmprovider_is_deleted'), 'llmprovider', ['is_deleted'], unique=False)
    op.create_table('agent_configs',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('model_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('system_prompt', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tool_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('deps_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('agent_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('scope', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('participation_mode', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('capabilities', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_coordinator', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('max_tool_iterations', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_provider', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('provider_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('agent_configs_owner_id_fkey')),
    sa.ForeignKeyConstraint(['user_provider'], ['userllmprovider.id'], name=op.f('agent_configs_user_provider_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_configs_pkey'))
    )
    sa.ForeignKeyConstraint(['agent_config_id'], ['agent_configs.id'], name=op.f('user_agent_settings_agent_config_id_fkey'), ondelete='CASCADE'),
    op.drop_table('user_agent_configs')
    op.drop_index(op.f('ix_user_access_provider_user_id'), table_name='user_access_provider')
    op.drop_table('user_access_provider')
    # ### end Alembic commands ###
