"""Add UserAgentSettings table

Revision ID: bcfd1062bbdb
Revises: 951af84085b1
Create Date: 2026-01-16 13:35:43.865931

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bcfd1062bbdb'
down_revision = '951af84085b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_agent_settings',
    sa.Column('provider_id', sa.Uuid(), nullable=True),
    sa.Column('custom_system_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('agent_config_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_config_id'], ['agent_configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'agent_config_id', name='uq_user_agent_settings')
    )
    op.create_index(op.f('ix_user_agent_settings_agent_config_id'), 'user_agent_settings', ['agent_config_id'], unique=False)
    op.create_index(op.f('ix_user_agent_settings_user_id'), 'user_agent_settings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_agent_settings_user_id'), table_name='user_agent_settings')
    op.drop_index(op.f('ix_user_agent_settings_agent_config_id'), table_name='user_agent_settings')
    op.drop_table('user_agent_settings')
    # ### end Alembic commands ###
