"""beepbeep

Revision ID: be1e5a2283da
Revises: 523a5805adf8
Create Date: 2026-03-01 17:03:02.879878

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'be1e5a2283da'
down_revision = '523a5805adf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('page_theme_id', sa.Uuid(), nullable=True))
    op.add_column('pages', sa.Column('cards_theme_id', sa.Uuid(), nullable=True))
    op.add_column('pages', sa.Column('presentation_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'presentation_json')
    op.drop_column('pages', 'cards_theme_id')
    op.drop_column('pages', 'page_theme_id')
    # ### end Alembic commands ###
