"""Add UserAccessProvider enhancements and UserModelPin table

Revision ID: befb94034e80
Revises: 9e3e5fe1f359
Create Date: 2026-03-09 04:14:25.023971

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'befb94034e80'
down_revision = '9e3e5fe1f359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_model_pin',
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('llm_model_id', sa.Uuid(), nullable=False),
    sa.Column('pinned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['llm_model_id'], ['llmmodel.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'llm_model_id', name='uq_user_model_pin_user_model')
    )
    op.create_index(op.f('ix_user_model_pin_llm_model_id'), 'user_model_pin', ['llm_model_id'], unique=False)
    op.create_index(op.f('ix_user_model_pin_user_id'), 'user_model_pin', ['user_id'], unique=False)
    op.add_column('provider_type', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False, server_default='custom'))
    op.add_column('provider_type', sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False, server_default=''))
    op.add_column('provider_type', sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('provider_type', sa.Column('docs_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('provider_type', sa.Column('default_base_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('provider_type', sa.Column('config_schema', sa.JSON(), nullable=True))
    op.add_column('provider_type', sa.Column('sort_order', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('user_access_provider', sa.Column('timeout_seconds', sa.Integer(), nullable=False, server_default='30'))
    op.add_column('user_access_provider', sa.Column('max_retries', sa.Integer(), nullable=False, server_default='3'))
    op.add_column('user_access_provider', sa.Column('retry_delay_ms', sa.Integer(), nullable=False, server_default='1000'))
    op.add_column('user_access_provider', sa.Column('proxy_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('user_access_provider', sa.Column('last_validated_at', sa.DateTime(), nullable=True))
    op.add_column('user_access_provider', sa.Column('validation_error', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True))
    op.add_column('user_access_provider', sa.Column('provider_config', sa.JSON(), nullable=True))
    op.add_column('user_access_provider', sa.Column('custom_headers', sa.JSON(), nullable=True))
    op.add_column('user_access_provider', sa.Column('available_models_cache', sa.JSON(), nullable=True))
    op.add_column('user_access_provider', sa.Column('models_cached_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_access_provider', 'models_cached_at')
    op.drop_column('user_access_provider', 'available_models_cache')
    op.drop_column('user_access_provider', 'custom_headers')
    op.drop_column('user_access_provider', 'provider_config')
    op.drop_column('user_access_provider', 'validation_error')
    op.drop_column('user_access_provider', 'last_validated_at')
    op.drop_column('user_access_provider', 'proxy_url')
    op.drop_column('user_access_provider', 'retry_delay_ms')
    op.drop_column('user_access_provider', 'max_retries')
    op.drop_column('user_access_provider', 'timeout_seconds')
    op.drop_column('provider_type', 'sort_order')
    op.drop_column('provider_type', 'config_schema')
    op.drop_column('provider_type', 'default_base_url')
    op.drop_column('provider_type', 'docs_url')
    op.drop_column('provider_type', 'logo_url')
    op.drop_column('provider_type', 'display_name')
    op.drop_column('provider_type', 'category')
    op.drop_index(op.f('ix_user_model_pin_user_id'), table_name='user_model_pin')
    op.drop_index(op.f('ix_user_model_pin_llm_model_id'), table_name='user_model_pin')
    op.drop_table('user_model_pin')
    # ### end Alembic commands ###
