"""manual upgrades for fun

Revision ID: c22bbe0f75b5
Revises: a20d937be623
Create Date: 2026-02-14 12:20:14.478551

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c22bbe0f75b5'
down_revision = 'a20d937be623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Wrap in autocommit_block so Postgres can execute these 
    # outside the main migration transaction.
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE contentformat ADD VALUE 'YAML'")
        op.execute("ALTER TYPE contentformat ADD VALUE 'MDX'")
        op.execute("ALTER TYPE contentformat ADD VALUE 'CODE'")
        op.execute("ALTER TYPE contentformat ADD VALUE 'SVG'")
        op.execute("ALTER TYPE contentformat ADD VALUE 'IMAGE'")
        op.execute("ALTER TYPE contentformat ADD VALUE 'AUDIO'")
        op.execute("ALTER TYPE contentformat ADD VALUE 'VIDEO'")
        op.execute("ALTER TYPE contentformat ADD VALUE 'EMPTY'")
        op.execute("ALTER TYPE contentformat ADD VALUE 'UNKNOWN'")
        op.execute("ALTER TYPE contentformat ADD VALUE 'TEST'")

    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
