"""changing title to name across the board

Revision ID: c7ada05c2877
Revises: 6e1971b061e3
Create Date: 2025-04-28 19:52:44.220315

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c7ada05c2877'
down_revision = '6e1971b061e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archetype', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.drop_column('archetype', 'title')
    op.add_column('item', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.drop_column('item', 'title')
    op.add_column('persona', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.drop_column('persona', 'title')
    op.add_column('quality', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.drop_column('quality', 'title')
    op.add_column('trait', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.drop_column('trait', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trait', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('trait', 'name')
    op.add_column('quality', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('quality', 'name')
    op.add_column('persona', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('persona', 'name')
    op.add_column('item', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('item', 'name')
    op.add_column('archetype', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('archetype', 'name')
    # ### end Alembic commands ###
