"""and now we do model for the special kids

Revision ID: d3b09fca8a6c
Revises: 4b3398004e6e
Create Date: 2026-02-02 18:01:12.390282

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd3b09fca8a6c'
down_revision = '4b3398004e6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
