"""add deleted_at to story and rooms - soft delete

Revision ID: d8e475bab15d
Revises: 3349fbf307db
Create Date: 2026-01-24 18:18:41.070886

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd8e475bab15d'
down_revision = '3349fbf307db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('story', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story', 'deleted_at')
    op.drop_column('rooms', 'deleted_at')
    # ### end Alembic commands ###