"""add traitconflictgroup and traitconflictgroupmember

Revision ID: dc4cc95e3533
Revises: 13b4c9134e55
Create Date: 2026-01-12 17:17:48.444647

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'dc4cc95e3533'
down_revision = '13b4c9134e55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traitconflictgroup',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('conflict_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traitconflictgroupmember',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('trait_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['traitconflictgroup.id'], ),
    sa.ForeignKeyConstraint(['trait_id'], ['trait.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traitconflictgroupmember_group_id'), 'traitconflictgroupmember', ['group_id'], unique=False)
    op.create_index(op.f('ix_traitconflictgroupmember_trait_id'), 'traitconflictgroupmember', ['trait_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traitconflictgroupmember_trait_id'), table_name='traitconflictgroupmember')
    op.drop_index(op.f('ix_traitconflictgroupmember_group_id'), table_name='traitconflictgroupmember')
    op.drop_table('traitconflictgroupmember')
    op.drop_table('traitconflictgroup')
    # ### end Alembic commands ###