"""Add user panel defaults and presets

Revision ID: dc799a990d4d
Revises: 2c6c3bb7f5f1
Create Date: 2026-01-20 14:11:42.973887

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'dc799a990d4d'
down_revision = '2c6c3bb7f5f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_panel_defaults',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('preset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('panels', sa.JSON(), nullable=True),
    sa.Column('reduce_motion', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_panel_defaults_user_id'), 'user_panel_defaults', ['user_id'], unique=True)
    op.create_table('panel_presets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('panels', sa.JSON(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('shared_to_room_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['shared_to_room_id'], ['rooms.room_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_panel_presets_owner_id'), 'panel_presets', ['owner_id'], unique=False)
    op.create_index(op.f('ix_panel_presets_shared_to_room_id'), 'panel_presets', ['shared_to_room_id'], unique=False)
    op.alter_column('shadow_outbox_attempts', 'error_message',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_constraint(op.f('shadow_outbox_attempts_outbox_job_id_fkey'), 'shadow_outbox_attempts', type_='foreignkey')
    op.create_foreign_key(None, 'shadow_outbox_attempts', 'shadow_outbox_jobs', ['outbox_job_id'], ['id'])
    op.alter_column('shadow_outbox_jobs', 'last_error',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_index(op.f('ix_shadow_outbox_jobs_shadow_repo_id_status'), table_name='shadow_outbox_jobs')
    op.drop_index(op.f('ix_shadow_outbox_jobs_status_run_after'), table_name='shadow_outbox_jobs')
    op.drop_constraint(op.f('uq_shadow_outbox_jobs_shadow_version_id'), 'shadow_outbox_jobs', type_='unique')
    op.drop_index(op.f('ix_shadow_outbox_jobs_shadow_version_id'), table_name='shadow_outbox_jobs')
    op.create_index(op.f('ix_shadow_outbox_jobs_shadow_version_id'), 'shadow_outbox_jobs', ['shadow_version_id'], unique=True)
    op.drop_constraint(op.f('shadow_outbox_jobs_shadow_version_id_fkey'), 'shadow_outbox_jobs', type_='foreignkey')
    op.drop_constraint(op.f('shadow_outbox_jobs_shadow_repo_id_fkey'), 'shadow_outbox_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'shadow_outbox_jobs', 'shadowrepo', ['shadow_repo_id'], ['id'])
    op.create_foreign_key(None, 'shadow_outbox_jobs', 'shadowversion', ['shadow_version_id'], ['id'])
    op.drop_constraint(op.f('shadow_outbox_repo_leases_shadow_repo_id_fkey'), 'shadow_outbox_repo_leases', type_='foreignkey')
    op.create_foreign_key(None, 'shadow_outbox_repo_leases', 'shadowrepo', ['shadow_repo_id'], ['id'])
    op.drop_constraint(op.f('shadow_repo_version_counters_shadow_repo_id_fkey'), 'shadow_repo_version_counters', type_='foreignkey')
    op.create_foreign_key(None, 'shadow_repo_version_counters', 'shadowrepo', ['shadow_repo_id'], ['id'])
    op.alter_column('shadowversion', 'last_error',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shadowversion', 'last_error',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'shadow_repo_version_counters', type_='foreignkey')
    op.create_foreign_key(op.f('shadow_repo_version_counters_shadow_repo_id_fkey'), 'shadow_repo_version_counters', 'shadowrepo', ['shadow_repo_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'shadow_outbox_repo_leases', type_='foreignkey')
    op.create_foreign_key(op.f('shadow_outbox_repo_leases_shadow_repo_id_fkey'), 'shadow_outbox_repo_leases', 'shadowrepo', ['shadow_repo_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'shadow_outbox_jobs', type_='foreignkey')
    op.drop_constraint(None, 'shadow_outbox_jobs', type_='foreignkey')
    op.create_foreign_key(op.f('shadow_outbox_jobs_shadow_repo_id_fkey'), 'shadow_outbox_jobs', 'shadowrepo', ['shadow_repo_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('shadow_outbox_jobs_shadow_version_id_fkey'), 'shadow_outbox_jobs', 'shadowversion', ['shadow_version_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_shadow_outbox_jobs_shadow_version_id'), table_name='shadow_outbox_jobs')
    op.create_index(op.f('ix_shadow_outbox_jobs_shadow_version_id'), 'shadow_outbox_jobs', ['shadow_version_id'], unique=False)
    op.create_unique_constraint(op.f('uq_shadow_outbox_jobs_shadow_version_id'), 'shadow_outbox_jobs', ['shadow_version_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_shadow_outbox_jobs_status_run_after'), 'shadow_outbox_jobs', ['status', 'run_after'], unique=False)
    op.create_index(op.f('ix_shadow_outbox_jobs_shadow_repo_id_status'), 'shadow_outbox_jobs', ['shadow_repo_id', 'status'], unique=False)
    op.alter_column('shadow_outbox_jobs', 'last_error',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'shadow_outbox_attempts', type_='foreignkey')
    op.create_foreign_key(op.f('shadow_outbox_attempts_outbox_job_id_fkey'), 'shadow_outbox_attempts', 'shadow_outbox_jobs', ['outbox_job_id'], ['id'], ondelete='CASCADE')
    op.alter_column('shadow_outbox_attempts', 'error_message',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_panel_presets_shared_to_room_id'), table_name='panel_presets')
    op.drop_index(op.f('ix_panel_presets_owner_id'), table_name='panel_presets')
    op.drop_table('panel_presets')
    op.drop_index(op.f('ix_user_panel_defaults_user_id'), table_name='user_panel_defaults')
    op.drop_table('user_panel_defaults')
    # ### end Alembic commands ###
