"""modifications (additions) to models for UserAgentConfig for presentation layer

Revision ID: dd33073093aa
Revises: 1c710085af4a
Create Date: 2026-02-07 10:39:08.920307

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'dd33073093aa'
down_revision = '1c710085af4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
