"""Add event tree structure to UserNodeChoice and UserStoryProgress

Revision ID: df9f66d000a5
Revises: 49a3ef34697c
Create Date: 2026-01-01 23:59:07.665051

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'df9f66d000a5'
down_revision = '49a3ef34697c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usernodechoice', sa.Column('parent_choice_id', sa.Uuid(), nullable=True))
    op.add_column('usernodechoice', sa.Column('rng_data', sa.JSON(), nullable=True))
    op.alter_column('usernodechoice', 'choice_text',
               existing_type=sa.VARCHAR(length=500),
               type_=sqlmodel.sql.sqltypes.AutoString(length=1000),
               existing_nullable=False)
    op.create_foreign_key(None, 'usernodechoice', 'usernodechoice', ['parent_choice_id'], ['id'])
    op.add_column('userstoryprogress', sa.Column('head_choice_id', sa.Uuid(), nullable=True))
    op.add_column('userstoryprogress', sa.Column('head_version', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'userstoryprogress', 'usernodechoice', ['head_choice_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userstoryprogress', type_='foreignkey')
    op.drop_column('userstoryprogress', 'head_version')
    op.drop_column('userstoryprogress', 'head_choice_id')
    op.drop_constraint(None, 'usernodechoice', type_='foreignkey')
    op.alter_column('usernodechoice', 'choice_text',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.drop_column('usernodechoice', 'rng_data')
    op.drop_column('usernodechoice', 'parent_choice_id')
    # ### end Alembic commands ###