"""refinement

Revision ID: ef569ce3c1f6
Revises: 72d5985f9334
Create Date: 2026-02-01 14:10:49.598099

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ef569ce3c1f6'
down_revision = '72d5985f9334'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
