/**
 * AgentForm Component
 *
 * Shared form for creating and editing agents.
 * Features:
 * - Name and slug inputs (slug auto-generated on create)
 * - Description textarea
 * - Model selector dropdown (populated from LLM catalog)
 * - System prompt textarea with character count
 * - Participation mode selector
 */

import { ChevronDownIcon } from "lucide-react"
import { useEffect, useState } from "react"

import {
  AgentProviderBadge,
  parseProviderFromModelName,
} from "@/components/Agents/AgentBadge"
import ModelCombobox from "@/components/Agents/providers/ModelCombobox"
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "@/components/ui/collapsible"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { cn } from "@/lib/utils"
import {
  AgentService,
  type AgentViewModel,
  type ParticipationMode,
} from "@/services/agentService"

// Participation modes
const PARTICIPATION_MODES = [
  {
    value: "on_mention",
    label: "On Mention",
    description: "Responds when @mentioned",
  },
  {
    value: "always",
    label: "Always Active",
    description: "Responds to all messages",
  },
  {
    value: "manual",
    label: "Manual",
    description: "Only responds when explicitly triggered",
  },
] as const

export interface AgentFormData {
  name: string
  slug: string
  description: string
  model_name: string
  system_prompt: string
  participation_mode: ParticipationMode
}

interface AgentFormProps {
  /** Initial values (for edit mode) */
  initialData?: Partial<AgentViewModel>
  /** Called when form data changes */
  onChange: (data: AgentFormData) => void
  /** Whether this is edit mode (affects slug editability) */
  isEditMode?: boolean
  /** Additional classes */
  className?: string
}

export default function AgentForm({
  initialData,
  onChange,
  isEditMode = false,
  className,
}: AgentFormProps) {
  const [name, setName] = useState(initialData?.name || "")
  const [slug, setSlug] = useState(initialData?.slug || "")
  const [description, setDescription] = useState(initialData?.description || "")
  const [modelName, setModelName] = useState(
    initialData?.model_name || "openai:gpt-4o-mini",
  )
  const [systemPrompt, setSystemPrompt] = useState(
    initialData?.system_prompt || "",
  )
  const [participationMode, setParticipationMode] = useState<ParticipationMode>(
    initialData?.participation_mode || "on_mention",
  )

  // Derive provider type from model (used for display and filtering in edit mode)
  const providerType = parseProviderFromModelName(modelName)

  // Auto-generate slug from backend (only in create mode)
  useEffect(() => {
    if (isEditMode || slug) return

    let isActive = true
    AgentService.generateSlug()
      .then((generatedSlug) => {
        if (isActive) setSlug(generatedSlug)
      })
      .catch(() => {})

    return () => {
      isActive = false
    }
  }, [isEditMode, slug])

  // Notify parent of changes
  useEffect(() => {
    onChange({
      name,
      slug,
      description,
      model_name: modelName,
      system_prompt: systemPrompt,
      participation_mode: participationMode,
    })
  }, [
    name,
    slug,
    description,
    modelName,
    systemPrompt,
    participationMode,
    onChange,
  ])

  return (
    <div className={cn("space-y-6", className)}>
      {/* Name */}
      <div className="space-y-2">
        <Label htmlFor="agent-name">
          Name <span className="text-destructive">*</span>
        </Label>
        <Input
          id="agent-name"
          value={name}
          onChange={(e) => setName(e.target.value)}
          placeholder="My Helpful Agent"
          maxLength={100}
        />
        <p className="text-xs text-muted-foreground">
          Display name for your agent
        </p>
      </div>

      {/* Slug (read-only, auto-generated by backend) */}
      <div className="space-y-2">
        <Label>Slug</Label>
        <p className="text-sm font-mono text-muted-foreground px-3 py-2 rounded-md bg-muted">
          {slug ? `@${slug}` : "Generating..."}
        </p>
      </div>

      {/* Description */}
      <div className="space-y-2">
        <Label htmlFor="agent-description">Description</Label>
        <Textarea
          id="agent-description"
          value={description}
          onChange={(e) => setDescription(e.target.value)}
          placeholder="Describe what this agent does..."
          maxLength={500}
          className="min-h-[80px]"
        />
        <p className="text-xs text-muted-foreground text-right">
          {description.length}/500
        </p>
      </div>

      {/* Model Selector */}
      <div className="space-y-2">
        <Label htmlFor="agent-model">Model</Label>
        {isEditMode && providerType && (
          <div className="flex items-center gap-2">
            <span className="text-xs text-muted-foreground">Provider:</span>
            <AgentProviderBadge providerType={providerType} />
          </div>
        )}
        <ModelCombobox
          value={modelName}
          onChange={setModelName}
          providerType={isEditMode ? (providerType ?? undefined) : undefined}
          placeholder="Select a model..."
        />
        <p className="text-xs text-muted-foreground">
          {isEditMode
            ? "Available models for this provider"
            : "Search catalog models or add a custom model"}
        </p>
      </div>

      {/* System Prompt */}
      <div className="space-y-2">
        <Label htmlFor="agent-prompt">System Prompt</Label>
        <Textarea
          id="agent-prompt"
          value={systemPrompt}
          onChange={(e) => setSystemPrompt(e.target.value)}
          placeholder="You are a helpful assistant that..."
          className="min-h-[150px] font-mono text-sm"
        />

        {/* Collapsible Preview */}
        {systemPrompt && (
          <Collapsible>
            <CollapsibleTrigger className="flex items-center gap-1 text-xs text-muted-foreground hover:text-foreground transition-colors">
              <ChevronDownIcon className="size-3" />
              Preview rendered prompt ({systemPrompt.length} chars)
            </CollapsibleTrigger>
            <CollapsibleContent>
              <div className="mt-2 p-3 rounded-md bg-muted text-sm whitespace-pre-wrap max-h-[200px] overflow-y-auto">
                {systemPrompt}
              </div>
            </CollapsibleContent>
          </Collapsible>
        )}

        <p className="text-xs text-muted-foreground">
          Instructions that define your agent's personality and behavior
        </p>
      </div>

      {/* Participation Mode */}
      <div className="space-y-2">
        <Label htmlFor="agent-mode">Participation Mode</Label>
        <Select
          value={participationMode}
          onValueChange={(v) => setParticipationMode(v as ParticipationMode)}
        >
          <SelectTrigger id="agent-mode" className="w-full">
            <SelectValue placeholder="Select mode" />
          </SelectTrigger>
          <SelectContent>
            {PARTICIPATION_MODES.map((mode) => (
              <SelectItem key={mode.value} value={mode.value}>
                <div className="flex flex-col">
                  <span>{mode.label}</span>
                  <span className="text-xs text-muted-foreground">
                    {mode.description}
                  </span>
                </div>
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>
    </div>
  )
}

// Export constants for reuse
export { PARTICIPATION_MODES }
