/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTraitsRouteImport } from './routes/_layout/traits'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutRoomsRouteImport } from './routes/_layout/rooms'
import { Route as LayoutQualitiesRouteImport } from './routes/_layout/qualities'
import { Route as LayoutPersonasRouteImport } from './routes/_layout/personas'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutChatsterRouteImport } from './routes/_layout/chatster'
import { Route as LayoutArchetypesRouteImport } from './routes/_layout/archetypes'
import { Route as LayoutAgentsRouteImport } from './routes/_layout/agents'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutStoriesIndexRouteImport } from './routes/_layout/stories/index'
import { Route as LayoutUSlugRouteImport } from './routes/_layout/u.$slug'
import { Route as LayoutTraitTraitIdRouteImport } from './routes/_layout/trait.$traitId'
import { Route as LayoutTeamSlugRouteImport } from './routes/_layout/team.$slug'
import { Route as LayoutRoomRoomIdRouteImport } from './routes/_layout/room.$roomId'
import { Route as LayoutRoomV2RoomIdRouteImport } from './routes/_layout/room-v2.$roomId'
import { Route as LayoutRRoomIdRouteImport } from './routes/_layout/r.$roomId'
import { Route as LayoutQualityQualityIdRouteImport } from './routes/_layout/quality.$qualityId'
import { Route as LayoutPersonaPersonaIdRouteImport } from './routes/_layout/persona.$personaId'
import { Route as LayoutDemoSlugRouteImport } from './routes/_layout/demo.$slug'
import { Route as LayoutArchetypeArchetypeIdRouteImport } from './routes/_layout/archetype.$archetypeId'
import { Route as LayoutAgentAgentIdRouteImport } from './routes/_layout/agent.$agentId'
import { Route as LayoutStoriesStoryIdEditRouteImport } from './routes/_layout/stories/$storyId/edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTraitsRoute = LayoutTraitsRouteImport.update({
  id: '/traits',
  path: '/traits',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRoomsRoute = LayoutRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutQualitiesRoute = LayoutQualitiesRouteImport.update({
  id: '/qualities',
  path: '/qualities',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPersonasRoute = LayoutPersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChatsterRoute = LayoutChatsterRouteImport.update({
  id: '/chatster',
  path: '/chatster',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutArchetypesRoute = LayoutArchetypesRouteImport.update({
  id: '/archetypes',
  path: '/archetypes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAgentsRoute = LayoutAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStoriesIndexRoute = LayoutStoriesIndexRouteImport.update({
  id: '/stories/',
  path: '/stories/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUSlugRoute = LayoutUSlugRouteImport.update({
  id: '/u/$slug',
  path: '/u/$slug',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTraitTraitIdRoute = LayoutTraitTraitIdRouteImport.update({
  id: '/trait/$traitId',
  path: '/trait/$traitId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTeamSlugRoute = LayoutTeamSlugRouteImport.update({
  id: '/team/$slug',
  path: '/team/$slug',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRoomRoomIdRoute = LayoutRoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRoomV2RoomIdRoute = LayoutRoomV2RoomIdRouteImport.update({
  id: '/room-v2/$roomId',
  path: '/room-v2/$roomId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRRoomIdRoute = LayoutRRoomIdRouteImport.update({
  id: '/r/$roomId',
  path: '/r/$roomId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutQualityQualityIdRoute = LayoutQualityQualityIdRouteImport.update({
  id: '/quality/$qualityId',
  path: '/quality/$qualityId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPersonaPersonaIdRoute = LayoutPersonaPersonaIdRouteImport.update({
  id: '/persona/$personaId',
  path: '/persona/$personaId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDemoSlugRoute = LayoutDemoSlugRouteImport.update({
  id: '/demo/$slug',
  path: '/demo/$slug',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutArchetypeArchetypeIdRoute =
  LayoutArchetypeArchetypeIdRouteImport.update({
    id: '/archetype/$archetypeId',
    path: '/archetype/$archetypeId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAgentAgentIdRoute = LayoutAgentAgentIdRouteImport.update({
  id: '/agent/$agentId',
  path: '/agent/$agentId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStoriesStoryIdEditRoute =
  LayoutStoriesStoryIdEditRouteImport.update({
    id: '/stories/$storyId/edit',
    path: '/stories/$storyId/edit',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/agents': typeof LayoutAgentsRoute
  '/archetypes': typeof LayoutArchetypesRoute
  '/chatster': typeof LayoutChatsterRoute
  '/items': typeof LayoutItemsRoute
  '/personas': typeof LayoutPersonasRoute
  '/qualities': typeof LayoutQualitiesRoute
  '/rooms': typeof LayoutRoomsRoute
  '/settings': typeof LayoutSettingsRoute
  '/traits': typeof LayoutTraitsRoute
  '/agent/$agentId': typeof LayoutAgentAgentIdRoute
  '/archetype/$archetypeId': typeof LayoutArchetypeArchetypeIdRoute
  '/demo/$slug': typeof LayoutDemoSlugRoute
  '/persona/$personaId': typeof LayoutPersonaPersonaIdRoute
  '/quality/$qualityId': typeof LayoutQualityQualityIdRoute
  '/r/$roomId': typeof LayoutRRoomIdRoute
  '/room-v2/$roomId': typeof LayoutRoomV2RoomIdRoute
  '/room/$roomId': typeof LayoutRoomRoomIdRoute
  '/team/$slug': typeof LayoutTeamSlugRoute
  '/trait/$traitId': typeof LayoutTraitTraitIdRoute
  '/u/$slug': typeof LayoutUSlugRoute
  '/stories/': typeof LayoutStoriesIndexRoute
  '/stories/$storyId/edit': typeof LayoutStoriesStoryIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/agents': typeof LayoutAgentsRoute
  '/archetypes': typeof LayoutArchetypesRoute
  '/chatster': typeof LayoutChatsterRoute
  '/items': typeof LayoutItemsRoute
  '/personas': typeof LayoutPersonasRoute
  '/qualities': typeof LayoutQualitiesRoute
  '/rooms': typeof LayoutRoomsRoute
  '/settings': typeof LayoutSettingsRoute
  '/traits': typeof LayoutTraitsRoute
  '/': typeof LayoutIndexRoute
  '/agent/$agentId': typeof LayoutAgentAgentIdRoute
  '/archetype/$archetypeId': typeof LayoutArchetypeArchetypeIdRoute
  '/demo/$slug': typeof LayoutDemoSlugRoute
  '/persona/$personaId': typeof LayoutPersonaPersonaIdRoute
  '/quality/$qualityId': typeof LayoutQualityQualityIdRoute
  '/r/$roomId': typeof LayoutRRoomIdRoute
  '/room-v2/$roomId': typeof LayoutRoomV2RoomIdRoute
  '/room/$roomId': typeof LayoutRoomRoomIdRoute
  '/team/$slug': typeof LayoutTeamSlugRoute
  '/trait/$traitId': typeof LayoutTraitTraitIdRoute
  '/u/$slug': typeof LayoutUSlugRoute
  '/stories': typeof LayoutStoriesIndexRoute
  '/stories/$storyId/edit': typeof LayoutStoriesStoryIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/agents': typeof LayoutAgentsRoute
  '/_layout/archetypes': typeof LayoutArchetypesRoute
  '/_layout/chatster': typeof LayoutChatsterRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/personas': typeof LayoutPersonasRoute
  '/_layout/qualities': typeof LayoutQualitiesRoute
  '/_layout/rooms': typeof LayoutRoomsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/traits': typeof LayoutTraitsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/agent/$agentId': typeof LayoutAgentAgentIdRoute
  '/_layout/archetype/$archetypeId': typeof LayoutArchetypeArchetypeIdRoute
  '/_layout/demo/$slug': typeof LayoutDemoSlugRoute
  '/_layout/persona/$personaId': typeof LayoutPersonaPersonaIdRoute
  '/_layout/quality/$qualityId': typeof LayoutQualityQualityIdRoute
  '/_layout/r/$roomId': typeof LayoutRRoomIdRoute
  '/_layout/room-v2/$roomId': typeof LayoutRoomV2RoomIdRoute
  '/_layout/room/$roomId': typeof LayoutRoomRoomIdRoute
  '/_layout/team/$slug': typeof LayoutTeamSlugRoute
  '/_layout/trait/$traitId': typeof LayoutTraitTraitIdRoute
  '/_layout/u/$slug': typeof LayoutUSlugRoute
  '/_layout/stories/': typeof LayoutStoriesIndexRoute
  '/_layout/stories/$storyId/edit': typeof LayoutStoriesStoryIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/agents'
    | '/archetypes'
    | '/chatster'
    | '/items'
    | '/personas'
    | '/qualities'
    | '/rooms'
    | '/settings'
    | '/traits'
    | '/agent/$agentId'
    | '/archetype/$archetypeId'
    | '/demo/$slug'
    | '/persona/$personaId'
    | '/quality/$qualityId'
    | '/r/$roomId'
    | '/room-v2/$roomId'
    | '/room/$roomId'
    | '/team/$slug'
    | '/trait/$traitId'
    | '/u/$slug'
    | '/stories/'
    | '/stories/$storyId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/agents'
    | '/archetypes'
    | '/chatster'
    | '/items'
    | '/personas'
    | '/qualities'
    | '/rooms'
    | '/settings'
    | '/traits'
    | '/'
    | '/agent/$agentId'
    | '/archetype/$archetypeId'
    | '/demo/$slug'
    | '/persona/$personaId'
    | '/quality/$qualityId'
    | '/r/$roomId'
    | '/room-v2/$roomId'
    | '/room/$roomId'
    | '/team/$slug'
    | '/trait/$traitId'
    | '/u/$slug'
    | '/stories'
    | '/stories/$storyId/edit'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/agents'
    | '/_layout/archetypes'
    | '/_layout/chatster'
    | '/_layout/items'
    | '/_layout/personas'
    | '/_layout/qualities'
    | '/_layout/rooms'
    | '/_layout/settings'
    | '/_layout/traits'
    | '/_layout/'
    | '/_layout/agent/$agentId'
    | '/_layout/archetype/$archetypeId'
    | '/_layout/demo/$slug'
    | '/_layout/persona/$personaId'
    | '/_layout/quality/$qualityId'
    | '/_layout/r/$roomId'
    | '/_layout/room-v2/$roomId'
    | '/_layout/room/$roomId'
    | '/_layout/team/$slug'
    | '/_layout/trait/$traitId'
    | '/_layout/u/$slug'
    | '/_layout/stories/'
    | '/_layout/stories/$storyId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/traits': {
      id: '/_layout/traits'
      path: '/traits'
      fullPath: '/traits'
      preLoaderRoute: typeof LayoutTraitsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/rooms': {
      id: '/_layout/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof LayoutRoomsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/qualities': {
      id: '/_layout/qualities'
      path: '/qualities'
      fullPath: '/qualities'
      preLoaderRoute: typeof LayoutQualitiesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/personas': {
      id: '/_layout/personas'
      path: '/personas'
      fullPath: '/personas'
      preLoaderRoute: typeof LayoutPersonasRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/chatster': {
      id: '/_layout/chatster'
      path: '/chatster'
      fullPath: '/chatster'
      preLoaderRoute: typeof LayoutChatsterRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/archetypes': {
      id: '/_layout/archetypes'
      path: '/archetypes'
      fullPath: '/archetypes'
      preLoaderRoute: typeof LayoutArchetypesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agents': {
      id: '/_layout/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof LayoutAgentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/stories/': {
      id: '/_layout/stories/'
      path: '/stories'
      fullPath: '/stories/'
      preLoaderRoute: typeof LayoutStoriesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/u/$slug': {
      id: '/_layout/u/$slug'
      path: '/u/$slug'
      fullPath: '/u/$slug'
      preLoaderRoute: typeof LayoutUSlugRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/trait/$traitId': {
      id: '/_layout/trait/$traitId'
      path: '/trait/$traitId'
      fullPath: '/trait/$traitId'
      preLoaderRoute: typeof LayoutTraitTraitIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/team/$slug': {
      id: '/_layout/team/$slug'
      path: '/team/$slug'
      fullPath: '/team/$slug'
      preLoaderRoute: typeof LayoutTeamSlugRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/room/$roomId': {
      id: '/_layout/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof LayoutRoomRoomIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/room-v2/$roomId': {
      id: '/_layout/room-v2/$roomId'
      path: '/room-v2/$roomId'
      fullPath: '/room-v2/$roomId'
      preLoaderRoute: typeof LayoutRoomV2RoomIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/r/$roomId': {
      id: '/_layout/r/$roomId'
      path: '/r/$roomId'
      fullPath: '/r/$roomId'
      preLoaderRoute: typeof LayoutRRoomIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/quality/$qualityId': {
      id: '/_layout/quality/$qualityId'
      path: '/quality/$qualityId'
      fullPath: '/quality/$qualityId'
      preLoaderRoute: typeof LayoutQualityQualityIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/persona/$personaId': {
      id: '/_layout/persona/$personaId'
      path: '/persona/$personaId'
      fullPath: '/persona/$personaId'
      preLoaderRoute: typeof LayoutPersonaPersonaIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/demo/$slug': {
      id: '/_layout/demo/$slug'
      path: '/demo/$slug'
      fullPath: '/demo/$slug'
      preLoaderRoute: typeof LayoutDemoSlugRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/archetype/$archetypeId': {
      id: '/_layout/archetype/$archetypeId'
      path: '/archetype/$archetypeId'
      fullPath: '/archetype/$archetypeId'
      preLoaderRoute: typeof LayoutArchetypeArchetypeIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agent/$agentId': {
      id: '/_layout/agent/$agentId'
      path: '/agent/$agentId'
      fullPath: '/agent/$agentId'
      preLoaderRoute: typeof LayoutAgentAgentIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/stories/$storyId/edit': {
      id: '/_layout/stories/$storyId/edit'
      path: '/stories/$storyId/edit'
      fullPath: '/stories/$storyId/edit'
      preLoaderRoute: typeof LayoutStoriesStoryIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutAgentsRoute: typeof LayoutAgentsRoute
  LayoutArchetypesRoute: typeof LayoutArchetypesRoute
  LayoutChatsterRoute: typeof LayoutChatsterRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutPersonasRoute: typeof LayoutPersonasRoute
  LayoutQualitiesRoute: typeof LayoutQualitiesRoute
  LayoutRoomsRoute: typeof LayoutRoomsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutTraitsRoute: typeof LayoutTraitsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAgentAgentIdRoute: typeof LayoutAgentAgentIdRoute
  LayoutArchetypeArchetypeIdRoute: typeof LayoutArchetypeArchetypeIdRoute
  LayoutDemoSlugRoute: typeof LayoutDemoSlugRoute
  LayoutPersonaPersonaIdRoute: typeof LayoutPersonaPersonaIdRoute
  LayoutQualityQualityIdRoute: typeof LayoutQualityQualityIdRoute
  LayoutRRoomIdRoute: typeof LayoutRRoomIdRoute
  LayoutRoomV2RoomIdRoute: typeof LayoutRoomV2RoomIdRoute
  LayoutRoomRoomIdRoute: typeof LayoutRoomRoomIdRoute
  LayoutTeamSlugRoute: typeof LayoutTeamSlugRoute
  LayoutTraitTraitIdRoute: typeof LayoutTraitTraitIdRoute
  LayoutUSlugRoute: typeof LayoutUSlugRoute
  LayoutStoriesIndexRoute: typeof LayoutStoriesIndexRoute
  LayoutStoriesStoryIdEditRoute: typeof LayoutStoriesStoryIdEditRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutAgentsRoute: LayoutAgentsRoute,
  LayoutArchetypesRoute: LayoutArchetypesRoute,
  LayoutChatsterRoute: LayoutChatsterRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutPersonasRoute: LayoutPersonasRoute,
  LayoutQualitiesRoute: LayoutQualitiesRoute,
  LayoutRoomsRoute: LayoutRoomsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutTraitsRoute: LayoutTraitsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAgentAgentIdRoute: LayoutAgentAgentIdRoute,
  LayoutArchetypeArchetypeIdRoute: LayoutArchetypeArchetypeIdRoute,
  LayoutDemoSlugRoute: LayoutDemoSlugRoute,
  LayoutPersonaPersonaIdRoute: LayoutPersonaPersonaIdRoute,
  LayoutQualityQualityIdRoute: LayoutQualityQualityIdRoute,
  LayoutRRoomIdRoute: LayoutRRoomIdRoute,
  LayoutRoomV2RoomIdRoute: LayoutRoomV2RoomIdRoute,
  LayoutRoomRoomIdRoute: LayoutRoomRoomIdRoute,
  LayoutTeamSlugRoute: LayoutTeamSlugRoute,
  LayoutTraitTraitIdRoute: LayoutTraitTraitIdRoute,
  LayoutUSlugRoute: LayoutUSlugRoute,
  LayoutStoriesIndexRoute: LayoutStoriesIndexRoute,
  LayoutStoriesStoryIdEditRoute: LayoutStoriesStoryIdEditRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
