// src/components/Demo/DemoShell.tsx

// NOTE: this file is actively being worked on.
// NOTE: I do not need this file to compile or build before DemoConfig is resolved.
// NOTE: the most important thing I can understand is what is needed to be in DemoConfig.

import { useCallback, useState } from "react"

import React from "react"
import { cn } from "@/lib/utils"
import 
  {
    type ThemeViewModel,
    themeTokensToStyle,
} from "@/services/themeService"
import { DemoHeader } from "./DemoHeader"
import { DemoLayout, type PanelConfig } from "./DemoLayout"
// import type { DemoConfig } from "@/config/demos"
// leaving this import here because I may wrap the DemoConfigPublic in a view model, unsure

// unsure about useRoomMessages and useRoomStream here. 
// we may want to import them through StoryPanel or DemoLayout - only use them when we need them.

// import { useRoomMessages } from "@/hooks/useRoomMessages"
// import { useRoomStream } from "@/hooks/useRoomStream"

// same goes for these - I need to review RoomMessages and see why it's needed if we have useRoomMessages?

// import MessageInput from "@/components/Room/RoomMessages/MessageInput"
// import MessageList from "@/components/Room/RoomMessages/MessageList"

// newly created, just finished, still needs review/integration.
import { DemoStoryPanel } from "./DemoStoryPanel"

export interface DemoShellProps {
// active work: migrating DemoConfig as a typed model to the backend.
//  
// see frontend/src/config/demos.ts/DemoConfig for legacy version: being actively deprecated, so that
// it can be API driven.  we will access the DemoConfig from exported types/schemas/services.
// these are generated by OpenAPI - I am prioritizing this work.

/** note: we're going to import and reuse PageThemes and extend/overload only when needed. */
  /** Page title */
  title: string
  /** Demo type - controls header icon and available actions */
  type: string
  /** Whether the current user can edit */
  canEdit: boolean
  /** Panel configurations */
  panels: PanelConfig[]
  /** Resolved page theme (from usePageThemes hook) */
  pageTheme: ThemeViewModel | null
  /** Resolved cards theme (from usePageThemes hook) */
  cardsTheme: ThemeViewModel | null
  /** Available page themes for picker */
  availablePageThemes: ThemeViewModel[]
  /** Available card themes for picker */
  availableCardThemes: ThemeViewModel[]
  /** Page theme change callback */
  onPageThemeChange: (themeId: string) => void
  /** Cards theme change callback */
  onCardsThemeChange: (themeId: string) => void
  /** Whether themes are still loading */
  isLoadingThemes?: boolean
  /** Additional className */
  className?: string
}


export function DemoShell ({
// TODO: finish adding
  title,
  type,
  canEdit,
  panels,
  pageTheme,
  cardsTheme,
  availablePageThemes,
  availableCardThemes,
  onPageThemeChange,
  onCardsThemeChange,
  className,
}: DemoShellProps) {
  const [layoutMode, setLayoutMode] = React.useState<"panels" | "tabs">(
    "panels",
  )

// Convert theme tokens to CSS style objects
  const pageThemeStyle = themeTokensToStyle(pageTheme?.tokens)
  const cardsThemeStyle = themeTokensToStyle(cardsTheme?.tokens)

  return (
    // Outermost: Page theme scope (affects header + content)
    // Transparent wrapper — only sets CSS variables, does not render a surface
    // Downstream components (Header, PanelContainer) render with inherited variables
    <div
      style={pageThemeStyle}
      className={cn("flex flex-col h-full", className)}
    >
      <DemoHeader
        // these don't resolve yet because democonfig doesn't exist, and so I can't yet pass it.
        // once DemoConfig is an active model, we can derive this from the exported schema
        // ie demo_config = DemoConfigPublic.id or DemoConfigPublic.slug
        title={democonfig.title}
        description={democonfig.description}
        // Pass theme info to header for picker
        pageTheme={pageTheme}
        cardsTheme={cardsTheme}
        availablePageThemes={availablePageThemes}
        availableCardThemes={availableCardThemes}
        onPageThemeChange={onPageThemeChange}
        onCardsThemeChange={onCardsThemeChange}
        layoutMode={layoutMode}
        onLayoutModeChange={setLayoutMode}
      />

      {/* Inner: Cards theme scope (overrides page theme for card areas) */}
      {/* Transparent wrapper — only sets CSS variables, does not render a surface */}
      <div style={cardsThemeStyle} className="flex-1 min-h-0">
        <DemoLayout panels={panels} mode={layoutMode} />
        {/* IF DemoConfig has StoryPanel then: <DemoStoryPanel/> :passing in props  */}
        {/* IF Democonfig has CanvasPanel  then: <DemoCanvasPanel/> */}
        {/* IF DemoConfig has ... then ... */}

      </div>
                  {/* these are here so I don't rewrite them when we need to integrate them.

                  <MessageList
                    roomId={config.roomId}
                    messages={messages}
                    hasMore={hasMore}
                    onLoadMore={loadMore}
                    isLoadingMore={isLoadingMore}
                    isLoading={isLoading}
                    streamingMessage={streamingMessage}
                  />
                </div>
                <MessageInput
                  roomId={config.roomId}
                  onSendMessage={sendMessage}
                  isSending={isSending}
                  isConnected={isConnected}
                  sendViaWebSocket={sendViaWebSocket}
                /> */}
    </div>
  )
}